/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const brazilian = {
  ...english,
  APIPageHeader: "API para programadores",
  ApplyPatchUse: /* csgo_brazilian.txt */"Aplicar emblema",
  ApplyPatchWarn: /* csgo_brazilian.txt */"Um emblema só pode ser usado uma vez",
  ApplyStickerCancel: /* csgo_brazilian.txt */"Cancelar",
  ApplyStickerUse: /* csgo_brazilian.txt */"Colar adesivo",
  ApplyStickerUseOn: /* csgo_brazilian.txt */"Usar em",
  ApplyStickerWarn: /* csgo_brazilian.txt */"Um adesivo pode ser aplicado apenas uma vez",
  CaseAdd: /* csgo_brazilian.txt */"Adicionar",
  CaseAddKeyConfirm: "Confirmar criação de chave",
  CaseClose: /* csgo_brazilian.txt */"Fechar",
  CaseContainsOne: /* csgo_brazilian.txt */"Contém um dos seguintes itens:",
  CaseNeed: /* csgo_brazilian.txt */"Esta ação requer uma",
  CaseOnceWarn: /* csgo_brazilian.txt */"Este recipiente só pode ser aberto uma vez",
  CaseRareItem: /* csgo_brazilian.txt */"★ Item raro e especial ★",
  CaseUnlock: /* csgo_brazilian.txt */"Destrancar",
  CaseUnlockContainer: /* csgo_brazilian.txt */"Destrancar recipiente",
  CaseUse: /* csgo_brazilian.txt */"Usar",
  CategoryAgent: /* csgo_brazilian.txt */"Agente",
  CategoryCase: /* csgo_brazilian.txt */"Recipiente",
  CategoryCollectible: /* csgo_brazilian.txt */"Colecionável",
  CategoryEquipment: /* csgo_brazilian.txt */"Equipamento",
  CategoryGlove: /* csgo_brazilian.txt */"Luvas",
  CategoryGraffiti: /* csgo_brazilian.txt */"Grafite",
  CategoryHeavy: /* csgo_brazilian.txt */"Pesadas",
  CategoryKey: /* csgo_brazilian.txt */"Chave",
  CategoryKnife: /* csgo_brazilian.txt */"Faca",
  CategoryMusicKit: /* csgo_brazilian.txt */"Trilha Sonora",
  CategoryPatch: /* csgo_brazilian.txt */"Emblema",
  CategoryPistol: /* csgo_brazilian.txt */"Pistola",
  CategoryRifle: /* csgo_brazilian.txt */"Rifle",
  CategorySMG: /* csgo_brazilian.txt */"Submetralhadora",
  CategorySticker: /* csgo_brazilian.txt */"Adesivo",
  CategoryTool: /* csgo_brazilian.txt */"Ferramenta",
  CraftBy: "Criação de",
  CraftConfirmHeader: "Confirmar criação",
  CraftSearchPlaceholder: "Procurar um item...",
  CraftSelectHeader: "Criando um item...",
  CraftSharedHeader: "Criação compartilhada",
  EditorCancel: /* csgo_brazilian.txt */"Cancelar",
  EditorCraft: "Criar",
  EditorNametag: /* csgo_brazilian.txt */"Etiqueta de Nome",
  EditorNametagPlaceholder: "Digite um nome...",
  EditorPatches: /* csgo_brazilian.txt */"Emblemas",
  EditorQuantity: /* csgo_brazilian.txt */"Quantidade",
  EditorRandom: /* csgo_brazilian.txt */"Aleatório",
  EditorReset: /* csgo_brazilian.txt */"Redefinir",
  EditorSave: /* csgo_brazilian.txt */"Salvar",
  EditorSeed: /* csgo_brazilian.txt */"Padrão",
  EditorStatTrak: /* csgo_brazilian.txt */"StatTrak™",
  EditorStickerWear: "Desgaste",
  EditorStickers: /* csgo_brazilian.txt */"Adesivos",
  EditorWear: /* csgo_brazilian.txt */"Desgaste",
  GridItemNoItemsToDisplay: "Nenhum item para exibir",
  HeaderCraftCannotCraft: "Você não pode criar itens.",
  HeaderCraftInventoryFull: "Seu inventário está cheio.",
  HeaderCraftLabel: "Criar Item",
  HeaderDonate: "Doar",
  HeaderInventoryLabel: "Inventário",
  HeaderSettingsLabel: "Configurações",
  HeaderSignInLabel: "Entrar e sincronizar",
  HeaderSignOutLabel: "Sair",
  HeaderSignedInAsLabel: "Entrou como",
  InspectClose: /* csgo_brazilian.txt */"Fechar",
  InventoryApplyPatch: /* csgo_brazilian.txt */"Aplicar emblema",
  InventoryApplySticker: /* csgo_brazilian.txt */"Aplicar adesivo",
  InventoryFilterAgents: /* csgo_brazilian.txt */"Agentes",
  InventoryFilterAll: /* csgo_brazilian.txt */"Todos",
  InventoryFilterAllEquipment: /* csgo_brazilian.txt */"Todos os equipamentos",
  InventoryFilterAllGraphicArt: /* csgo_brazilian.txt */"Todas as artes gráficas",
  InventoryFilterAlphabetical: /* csgo_brazilian.txt */"Nome (A–Z)",
  InventoryFilterCollection: /* csgo_brazilian.txt */"Coleção",
  InventoryFilterContainers: /* csgo_brazilian.txt */"RECIPIENTES",
  InventoryFilterDisplay: /* csgo_brazilian.txt */"DECORAÇÃO",
  InventoryFilterEquipment: /* csgo_brazilian.txt */"EQUIPAMENTO",
  InventoryFilterEquipped: /* csgo_brazilian.txt */"Equipado",
  InventoryFilterEverything: /* csgo_brazilian.txt */"TUDO",
  InventoryFilterGloves: /* csgo_brazilian.txt */"Luvas",
  InventoryFilterGraffiti: /* csgo_brazilian.txt */"Grafite",
  InventoryFilterGraffitiBoxes: /* csgo_brazilian.txt */"Caixas de Grafites",
  InventoryFilterGraphicArt: /* csgo_brazilian.txt */"ARTES GRÁFICAS",
  InventoryFilterMedals: /* csgo_brazilian.txt */"Medalhas",
  InventoryFilterMelee: /* csgo_brazilian.txt */"Corpo a corpo",
  InventoryFilterMidTier: /* csgo_brazilian.txt */"Intermediárias",
  InventoryFilterMisc: /* csgo_brazilian.txt */"Diversos",
  InventoryFilterMusicKits: /* csgo_brazilian.txt */"Trilhas Sonoras",
  InventoryFilterNewest: /* csgo_brazilian.txt */"Mais novos",
  InventoryFilterPatches: /* csgo_brazilian.txt */"Emblemas",
  InventoryFilterPistols: /* csgo_brazilian.txt */"Pistolas",
  InventoryFilterQuality: /* csgo_brazilian.txt */"Mais raros",
  InventoryFilterRifles: /* csgo_brazilian.txt */"Rifles",
  InventoryFilterSearch: /* csgo_brazilian.txt */"Buscar",
  InventoryFilterSouvenirCases: /* csgo_brazilian.txt */"Pacotes de Lembranças",
  InventoryFilterStickerCapsules: /* csgo_brazilian.txt */"Cápsulas de Adesivos",
  InventoryFilterStickers: /* csgo_brazilian.txt */"Adesivos",
  InventoryFilterTools: /* csgo_brazilian.txt */"Ferramentas",
  InventoryFilterType: /* csgo_brazilian.txt */"Tipo",
  InventoryFilterWeaponCases: /* csgo_brazilian.txt */"Caixas de Armas",
  InventoryItemContainsOne: /* csgo_brazilian.txt */"Contém um dos seguintes itens:",
  InventoryItemDelete: /* csgo_brazilian.txt */"Excluir",
  InventoryItemEdit: /* csgo_brazilian.txt */"Editar",
  InventoryItemEquip: /* csgo_brazilian.txt */"Equipar",
  InventoryItemEquipBothTeams: "Equipar Ambas Equipes",
  InventoryItemEquipCT: "Equipar CT",
  InventoryItemEquipT: "Equipar T",
  InventoryItemExterior: /* csgo_brazilian.txt */"Exterior:",
  InventoryItemInspect: /* csgo_brazilian.txt */"Inspecionar",
  InventoryItemInspectCopied: "Comando copiado!",
  InventoryItemInspectFinishCatalog: /* csgo_brazilian.txt */"Catálogo de revestimentos",
  InventoryItemInspectInGame: /* csgo_brazilian.txt */"Inspecionar no jogo...",
  InventoryItemInspectPatternTemplate: /* csgo_brazilian.txt */"Estilo do padrão",
  InventoryItemInspectWearRating: /* csgo_brazilian.txt */"Nível de desgaste",
  InventoryItemMVPStatTrakCount: /* csgo_brazilian.txt */"★ em partidas competitivas oficiais via StatTrak™:",
  InventoryItemNew: /* csgo_brazilian.txt */"Novo!",
  InventoryItemRareItem: /* csgo_brazilian.txt */"ou um item especial e excessivamente raro!",
  InventoryItemRarity: /* csgo_brazilian.txt */"Raridade:",
  InventoryItemRemovePatch: /* csgo_brazilian.txt */"Remover emblema",
  InventoryItemRename: /* csgo_brazilian.txt */"Renomear",
  InventoryItemRenameStorageUnit: /* csgo_brazilian.txt */"Renomear",
  InventoryItemScrapeSticker: /* csgo_brazilian.txt */"Raspar adesivo",
  InventoryItemShare: "Compartilhar",
  InventoryItemShareCopied: "Link copiado!",
  InventoryItemStatTrak: /* csgo_brazilian.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_brazilian.txt */"Vítimas confirmadas via StatTrak™:",
  InventoryItemStatTrakDesc: /* csgo_brazilian.txt */"Este item possui tecnologia StatTrak™, que contabiliza certas estatísticas quando equipado.",
  InventoryItemStorageUnitDeposit: /* csgo_brazilian.txt */"Guardar itens",
  InventoryItemStorageUnitEmptyBody: /* csgo_brazilian.txt */"Esta unidade de armazenamento permite armazenar até {1} itens além da capacidade do seu inventário. A unidade de armazenamento selecionada está vazia. A qualquer momento, é possível mover itens do seu inventário para a unidade, retirá-los dela ou usá-la para organizar as suas coleções.",
  InventoryItemStorageUnitEmptyClose: /* csgo_brazilian.txt */"OK",
  InventoryItemStorageUnitEmptyTitle: /* csgo_brazilian.txt */"Unidade de armazenamento vazia",
  InventoryItemStorageUnitInspect: /* csgo_brazilian.txt */"Inspecionar",
  InventoryItemStorageUnitRetrieve: /* csgo_brazilian.txt */"Retirar itens",
  InventoryItemSwapStatTrak: /* csgo_brazilian.txt */"Abrir Ferramenta de Troca StatTrak™",
  InventoryItemTeam: /* csgo_brazilian.txt */"Equipe:",
  InventoryItemTeamAny: /* csgo_brazilian.txt */"Qualquer",
  InventoryItemTeamCT: /* csgo_brazilian.txt */"Contraterrorista",
  InventoryItemTeamT: /* csgo_brazilian.txt */"Terrorista",
  InventoryItemUnequip: /* csgo_brazilian.txt */"Remover",
  InventoryItemUnequipCT: "Desequipar CT",
  InventoryItemUnequipT: "Desequipar T",
  InventoryItemUnlockContainer: /* csgo_brazilian.txt */"Destrancar recipiente",
  InventoryItemUseStorageUnit: /* csgo_brazilian.txt */"Começar a usar unidade",
  InventoryNoItemsToDisplay: "Nenhum item para exibir",
  InventorySelectAnItem: /* csgo_brazilian.txt */"Selecionar item para usar com:",
  InventorySelectInspectContents: /* csgo_brazilian.txt */"Inspecionando o conteúdo de",
  InventorySelectItemToDeposit: /* csgo_brazilian.txt */"Selecione quais itens guardar",
  InventorySelectItemToRetrieve: /* csgo_brazilian.txt */"Selecione quais itens retirar",
  InvnetoryFilterSearch: "Buscar",
  ItemRarityAncient: /* csgo_brazilian.txt */"Extraordinário",
  ItemRarityCommon: /* csgo_brazilian.txt */"Nível Básico",
  ItemRarityDefault: /* csgo_brazilian.txt */"Padrão",
  ItemRarityFormat: "{2} ({1})",
  ItemRarityImmortal: /* csgo_brazilian.txt */"Contrabandeado",
  ItemRarityLegendary: /* csgo_brazilian.txt */"Exótico",
  ItemRarityMythical: /* csgo_brazilian.txt */"Notável",
  ItemRarityNameAgent: /* csgo_brazilian.txt */"Agente",
  ItemRarityNameCollectible: /* csgo_brazilian.txt */"Colecionável",
  ItemRarityNameContainer: /* csgo_brazilian.txt */"Recipiente",
  ItemRarityNameContract: /* csgo_brazilian.txt */"Contrato",
  ItemRarityNameEquipment: /* csgo_brazilian.txt */"Equipamento",
  ItemRarityNameGloves: /* csgo_brazilian.txt */"Luvas",
  ItemRarityNameGraffiti: /* csgo_brazilian.txt */"Grafite",
  ItemRarityNameKey: /* csgo_brazilian.txt */"Chave",
  ItemRarityNameKnife: /* csgo_brazilian.txt */"Faca",
  ItemRarityNameMachinegun: /* csgo_brazilian.txt */"Metralhadora",
  ItemRarityNameMusicKit: /* csgo_brazilian.txt */"Trilha Sonora",
  ItemRarityNamePatch: /* csgo_brazilian.txt */"Emblema",
  ItemRarityNamePistol: /* csgo_brazilian.txt */"Pistola",
  ItemRarityNameRifle: /* csgo_brazilian.txt */"Rifle",
  ItemRarityNameSMG: /* csgo_brazilian.txt */"Submetralhadora",
  ItemRarityNameShotgun: /* csgo_brazilian.txt */"Escopeta",
  ItemRarityNameSniperRifle: /* csgo_brazilian.txt */"Rifle de Precisão",
  ItemRarityNameSticker: /* csgo_brazilian.txt */"Adesivo",
  ItemRarityNameTool: /* csgo_brazilian.txt */"Ferramenta",
  ItemRarityRare: /* csgo_brazilian.txt */"Alta Qualidade",
  ItemRarityUncommon: /* csgo_brazilian.txt */"Nível Moderado",
  ItemSwapStatTrakAccept: /* csgo_brazilian.txt */"ACEITAR",
  ItemSwapStatTrakClose: /* csgo_brazilian.txt */"Fechar",
  ItemSwapStatTrakDesc: /* csgo_brazilian.txt */"Este item troca as contagens StatTrak™ de dois itens do mesmo tipo.",
  ItemSwapStatTrakUse: /* csgo_brazilian.txt */"Ferramenta de Troca StatTrak™",
  ItemSwapStatTrakWarn: /* csgo_brazilian.txt */"Ferramentas de Troca StatTrak™ só podem ser usadas uma vez",
  ItemWeaponRarityAncient: /* csgo_brazilian.txt */"Oculto",
  ItemWeaponRarityCommon: /* csgo_brazilian.txt */"Nível Consumidor",
  ItemWeaponRarityDefault: /* csgo_brazilian.txt */"Padrão",
  ItemWeaponRarityImmortal: /* csgo_brazilian.txt */"Contrabandeado",
  ItemWeaponRarityLegendary: /* csgo_brazilian.txt */"Secreto",
  ItemWeaponRarityMythical: /* csgo_brazilian.txt */"Restrito",
  ItemWeaponRarityRare: /* csgo_brazilian.txt */"Nível Militar",
  ItemWeaponRarityUncommon: /* csgo_brazilian.txt */"Nível Industrial",
  ItemWearBS: /* csgo_brazilian.txt */"Veterana de Guerra",
  ItemWearFN: /* csgo_brazilian.txt */"Nova de Fábrica",
  ItemWearFT: /* csgo_brazilian.txt */"Testada em Campo",
  ItemWearMW: /* csgo_brazilian.txt */"Pouco Usada",
  ItemWearWW: /* csgo_brazilian.txt */"Bem Desgastada",
  JavaScriptRequired: "Por favor, habilite o JavaScript e atualize a página.",
  RemovePatchRemove: /* csgo_brazilian.txt */"Remover emblema",
  RemovePatchRemoveDesc: /* csgo_brazilian.txt */"Confirme que deseja remover este emblema do seu agente. O emblema removido será destruído.",
  RemovePatchUse: /* csgo_brazilian.txt */"Remover emblema",
  RemovePatchWarn: /* csgo_brazilian.txt */"Remover um emblema de",
  RenameCancel: /* csgo_brazilian.txt */"Cancelar",
  RenameEnterName: /* csgo_brazilian.txt */"Inserir novo nome para:",
  RenameRename: /* csgo_brazilian.txt */"Renomear",
  RenameStorageUnitClose: /* csgo_brazilian.txt */"Fechar",
  RenameStorageUnitEnterName: /* csgo_brazilian.txt */"Inserir novo nome para:",
  RenameStorageUnitFirstNameWarn: /* csgo_brazilian.txt */"Dê um nome descritivo para a unidade de armazenamento e use-a para guardar os seus itens.",
  RenameStorageUnitNewNameWarn: /* csgo_brazilian.txt */"Dê um novo nome descritivo para a unidade de armazenamento.",
  RenameStorageUnitRename: /* csgo_brazilian.txt */"Personalizar",
  RenameStorageUnitUse: /* csgo_brazilian.txt */"Personalize a sua unidade de armazenamento",
  RenameUse: /* csgo_brazilian.txt */"Usar Etiqueta de Nome",
  RenameWarn: /* csgo_brazilian.txt */"Etiquetas de Nome só podem ser usadas uma vez",
  ScrapeStickerCancel: /* csgo_brazilian.txt */"Cancelar",
  ScrapeStickerClose: /* csgo_brazilian.txt */"Fechar",
  ScrapeStickerRemove: /* csgo_brazilian.txt */"Remover adesivo",
  ScrapeStickerRemoveDesc: /* csgo_brazilian.txt */"Raspar este adesivo mais uma vez o removerá do item, fazendo com que seja destruído.",
  ScrapeStickerUse: /* csgo_brazilian.txt */"Raspar adesivo",
  ScrapeStickerWarn: /* csgo_brazilian.txt */"Raspar um adesivo de",
  SettingsBackground: "Plano de Fundo",
  SettingsBackgroundRandom: "Aleatório",
  SettingsConfirmRemoveAllItems: "Tem certeza de que deseja remover todos os itens do seu inventário?\nESSA AÇÃO NÃO PODE SER DESFEITA.",
  SettingsHeader: "Configurações",
  SettingsHideFilters: "Ocultar Filtros",
  SettingsHideFreeItems: "Ocultar Itens Gratuitos",
  SettingsLanguage: "Idioma",
  SettingsRemoveAllItems: "Redefinir meu inventário",
  SettingsSave: "Salvar",
  SettingsStatsForNerds: "Estatísticas para Nerds",
  StickerPickerFilterPlaceholder: "Filtrar por categoria...",
  StickerPickerHeader: "Escolha um adesivo...",
  StickerPickerRemove: /* csgo_brazilian.txt */"Remover",
  StickerPickerSearchPlaceholder: "Procurar adesivo...",
  SyncErrorContinue: "Tentar novamente",
  SyncErrorDesc: "Não foi possível sincronizar as suas mudanças.",
  SyncErrorTitle: "Erro de sincronização",
  SyncWarnText: "Você não está autenticado, suas mudanças não serão sincronizadas."
};
