/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const bulgarian = {
  ...english,
  ApplyPatchUse: /* csgo_bulgarian.txt */"Прилагане на нашивка",
  ApplyPatchWarn: /* csgo_bulgarian.txt */"Нашивката може да бъде приложена само веднъж",
  ApplyStickerCancel: /* csgo_bulgarian.txt */"Отказ",
  ApplyStickerUse: /* csgo_bulgarian.txt */"Прилагане на стикер",
  ApplyStickerUseOn: /* csgo_bulgarian.txt */"Използване върху",
  ApplyStickerWarn: /* csgo_bulgarian.txt */"Стикерът може да бъде приложен само веднъж",
  CaseAdd: /* csgo_bulgarian.txt */"Добавяне",
  CaseClose: /* csgo_bulgarian.txt */"Затваряне",
  CaseContainsOne: /* csgo_bulgarian.txt */"Съдържа един от следните артикули:",
  CaseNeed: /* csgo_bulgarian.txt */"Това действие изисква",
  CaseOnceWarn: /* csgo_bulgarian.txt */"Този контейнер може да бъде отворен само веднъж",
  CaseRareItem: /* csgo_bulgarian.txt */"★ Рядък специален артикул ★",
  CaseUnlock: /* csgo_bulgarian.txt */"Отключване на",
  CaseUnlockContainer: /* csgo_bulgarian.txt */"Отключване на контейнера",
  CaseUse: /* csgo_bulgarian.txt */"Използване на",
  CategoryAgent: /* csgo_bulgarian.txt */"Агент",
  CategoryCase: /* csgo_bulgarian.txt */"Контейнер",
  CategoryCollectible: /* csgo_bulgarian.txt */"Колекционерско",
  CategoryEquipment: /* csgo_bulgarian.txt */"Екипировка",
  CategoryGlove: /* csgo_bulgarian.txt */"Ръкавици",
  CategoryGraffiti: /* csgo_bulgarian.txt */"Графити",
  CategoryHeavy: /* csgo_bulgarian.txt */"Тежка артилерия",
  CategoryKey: /* csgo_bulgarian.txt */"Ключ",
  CategoryKeychain: /* csgo_bulgarian.txt */"Джунджурия",
  CategoryKnife: /* csgo_bulgarian.txt */"Нож",
  CategoryMusicKit: /* csgo_bulgarian.txt */"Музикален комплект",
  CategoryPatch: /* csgo_bulgarian.txt */"Нашивка",
  CategoryPistol: /* csgo_bulgarian.txt */"Пистолет",
  CategoryRifle: /* csgo_bulgarian.txt */"Винтовка",
  CategorySMG: /* csgo_bulgarian.txt */"Автомат",
  CategorySticker: /* csgo_bulgarian.txt */"Стикер",
  CategoryTool: /* csgo_bulgarian.txt */"Инструмент",
  EditorCancel: /* csgo_bulgarian.txt */"Отказ",
  EditorNametag: /* csgo_bulgarian.txt */"Етикет за име",
  EditorPatches: /* csgo_bulgarian.txt */"Нашивки",
  EditorQuantity: /* csgo_bulgarian.txt */"Количество",
  EditorRandom: /* csgo_bulgarian.txt */"Произволна",
  EditorReset: /* csgo_bulgarian.txt */"Нулиране",
  EditorSave: /* csgo_bulgarian.txt */"Запазване",
  EditorSeed: /* csgo_bulgarian.txt */"Шарка",
  EditorStatTrak: /* csgo_bulgarian.txt */"StatTrak™",
  EditorStickers: /* csgo_bulgarian.txt */"Стикери",
  EditorWear: /* csgo_bulgarian.txt */"Износване",
  GenericCancel: /* csgo_bulgarian.txt */"Отказ",
  InspectClose: /* csgo_bulgarian.txt */"Затваряне",
  InventoryApplyPatch: /* csgo_bulgarian.txt */"Прилагане на нашивка",
  InventoryApplySticker: /* csgo_bulgarian.txt */"Прилагане на стикер",
  InventoryFilterAgents: /* csgo_bulgarian.txt */"Агенти",
  InventoryFilterAll: /* csgo_bulgarian.txt */"Всичко",
  InventoryFilterAllEquipment: /* csgo_bulgarian.txt */"Всичката екипировка",
  InventoryFilterAllGraphicArt: /* csgo_bulgarian.txt */"Всички графични худ. творчества",
  InventoryFilterAlphabetical: /* csgo_bulgarian.txt */"Азбучно",
  InventoryFilterCharms: /* csgo_bulgarian.txt */"Джунджурии",
  InventoryFilterCollection: /* csgo_bulgarian.txt */"Колекция",
  InventoryFilterContainers: /* csgo_bulgarian.txt */"Контейнери",
  InventoryFilterDisplay: /* csgo_bulgarian.txt */"Показни",
  InventoryFilterEquipment: /* csgo_bulgarian.txt */"Екипировка",
  InventoryFilterEquipped: /* csgo_bulgarian.txt */"Екипирани",
  InventoryFilterEverything: /* csgo_bulgarian.txt */"Всичко",
  InventoryFilterGloves: /* csgo_bulgarian.txt */"Ръкавици",
  InventoryFilterGraffiti: /* csgo_bulgarian.txt */"Графити",
  InventoryFilterGraffitiBoxes: /* csgo_bulgarian.txt */"Кутия с графити",
  InventoryFilterGraphicArt: /* csgo_bulgarian.txt */"Графични худ. творчества",
  InventoryFilterMedals: /* csgo_bulgarian.txt */"Медали",
  InventoryFilterMelee: /* csgo_bulgarian.txt */"Ръкопашни",
  InventoryFilterMidTier: /* csgo_bulgarian.txt */"Средна поредица",
  InventoryFilterMisc: /* csgo_bulgarian.txt */"Разни",
  InventoryFilterMusicKits: /* csgo_bulgarian.txt */"Музикални комплекти",
  InventoryFilterNewest: /* csgo_bulgarian.txt */"Най-нови",
  InventoryFilterPatches: /* csgo_bulgarian.txt */"Нашивки",
  InventoryFilterPistols: /* csgo_bulgarian.txt */"Пистолети",
  InventoryFilterQuality: /* csgo_bulgarian.txt */"Качество",
  InventoryFilterRifles: /* csgo_bulgarian.txt */"Винтовки",
  InventoryFilterSearch: /* csgo_bulgarian.txt */"Напишете търсеното тук",
  InventoryFilterSouvenirCases: /* csgo_bulgarian.txt */"Сувенирни сандъци",
  InventoryFilterStickerCapsules: /* csgo_bulgarian.txt */"Капсули със стикери",
  InventoryFilterStickers: /* csgo_bulgarian.txt */"Стикери",
  InventoryFilterTools: /* csgo_bulgarian.txt */"Инструменти",
  InventoryFilterType: /* csgo_bulgarian.txt */"Тип",
  InventoryFilterWeaponCases: /* csgo_bulgarian.txt */"Оръжейни сандъци",
  InventoryItemContainsOne: /* csgo_bulgarian.txt */"Съдържа един от следните артикули:",
  InventoryItemDelete: /* csgo_bulgarian.txt */"Изтриване",
  InventoryItemDeleteConfirm: /* csgo_bulgarian.txt */"Изтриване на артикула",
  InventoryItemDeleteConfirmDesc: /* csgo_bulgarian.txt */"Сигурни ли сте, че искате да изтриете този артикул?",
  InventoryItemEdit: /* csgo_bulgarian.txt */"Редактиране",
  InventoryItemEquip: /* csgo_bulgarian.txt */"Екипиране",
  InventoryItemExterior: /* csgo_bulgarian.txt */"Външен вид:",
  InventoryItemInspect: /* csgo_bulgarian.txt */"Оглед",
  InventoryItemInspectFinishCatalog: /* csgo_bulgarian.txt */"№ за окраската в каталога",
  InventoryItemInspectInGame: /* csgo_bulgarian.txt */"Оглед в играта…",
  InventoryItemInspectPatternTemplate: /* csgo_bulgarian.txt */"Шаблон на шарката",
  InventoryItemInspectWearRating: /* csgo_bulgarian.txt */"Оценка на износването",
  InventoryItemMVPStatTrakCount: /* csgo_bulgarian.txt */"Официални съревнователни НЦИ от StatTrak™:",
  InventoryItemNew: /* csgo_bulgarian.txt */"Ново!",
  InventoryItemRareItem: /* csgo_bulgarian.txt */"или изключително рядък специален артикул!",
  InventoryItemRarity: /* csgo_bulgarian.txt */"Рядкост:",
  InventoryItemRemovePatch: /* csgo_bulgarian.txt */"Премахване на нашивка",
  InventoryItemRename: /* csgo_bulgarian.txt */"Преименуване на",
  InventoryItemRenameStorageUnit: /* csgo_bulgarian.txt */"Промяна на етикета",
  InventoryItemScrapeSticker: /* csgo_bulgarian.txt */"Одраскване на стикер",
  InventoryItemStatTrak: /* csgo_bulgarian.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_bulgarian.txt */"Потвърдени убийства от StatTrak™:",
  InventoryItemStatTrakDesc: /* csgo_bulgarian.txt */"Този артикул включва технологията StatTrak™, която следи определени статистики, когато е екипиран от своя притежател.",
  InventoryItemStorageUnitDeposit: /* csgo_bulgarian.txt */"Депозиране на артикули",
  InventoryItemStorageUnitEmptyBody: /* csgo_bulgarian.txt */"Съхраняващият елемент Ви позволява да складирате до {1} от своите излишни артикули, които в противен случай биха надвишили лимита на инвентара. Понастоящем избраният съхраняващ елемент е празен. По всяко време можете да местите артикули от инвентара в него. Да набавяте такива обратно в инвентара или просто да го използвате, за да организирате своите колекции.",
  InventoryItemStorageUnitEmptyClose: /* csgo_bulgarian.txt */"Добре",
  InventoryItemStorageUnitEmptyTitle: /* csgo_bulgarian.txt */"Изпразване на съхраняващ елемент",
  InventoryItemStorageUnitInspect: /* csgo_bulgarian.txt */"Оглед",
  InventoryItemStorageUnitRetrieve: /* csgo_bulgarian.txt */"Набавяне на артикули",
  InventoryItemSwapStatTrak: /* csgo_bulgarian.txt */"Отваряне на инструмент за StatTrak™ размяна",
  InventoryItemTeam: /* csgo_bulgarian.txt */"Отбор:",
  InventoryItemTeamAny: /* csgo_bulgarian.txt */"Всякакви",
  InventoryItemTeamCT: /* csgo_bulgarian.txt */"Контра терорист",
  InventoryItemTeamT: /* csgo_bulgarian.txt */"Терорист",
  InventoryItemUnequip: /* csgo_bulgarian.txt */"Премахване на екипировката",
  InventoryItemUnlockContainer: /* csgo_bulgarian.txt */"Отключване на контейнера",
  InventoryItemUseStorageUnit: /* csgo_bulgarian.txt */"Стартиране на ползването на този елемент",
  InventorySelectAnItem: /* csgo_bulgarian.txt */"Изберете артикул, с който да използвате:",
  InventorySelectInspectContents: /* csgo_bulgarian.txt */"Оглед на съдържанието",
  InventorySelectItemToDeposit: /* csgo_bulgarian.txt */"Избиране на артикули, които да преместите",
  InventorySelectItemToRetrieve: /* csgo_bulgarian.txt */"Избиране на артикули за набавяне от",
  ItemRarityAncient: /* csgo_bulgarian.txt */"Необикновен тип",
  ItemRarityCommon: /* csgo_bulgarian.txt */"Базов клас",
  ItemRarityDefault: /* csgo_bulgarian.txt */"По подразбиране",
  ItemRarityImmortal: /* csgo_bulgarian.txt */"Контрабанда",
  ItemRarityLegendary: /* csgo_bulgarian.txt */"Екзотичен тип",
  ItemRarityMythical: /* csgo_bulgarian.txt */"Забележителен тип",
  ItemRarityNameAgent: /* csgo_bulgarian.txt */"Агент",
  ItemRarityNameCharm: /* csgo_bulgarian.txt */"Джунджурия",
  ItemRarityNameCollectible: /* csgo_bulgarian.txt */"Колекционерско",
  ItemRarityNameContainer: /* csgo_bulgarian.txt */"Контейнер",
  ItemRarityNameContract: /* csgo_bulgarian.txt */"Договор",
  ItemRarityNameEquipment: /* csgo_bulgarian.txt */"Екипировка",
  ItemRarityNameGloves: /* csgo_bulgarian.txt */"Ръкавици",
  ItemRarityNameGraffiti: /* csgo_bulgarian.txt */"Графити",
  ItemRarityNameKey: /* csgo_bulgarian.txt */"Ключ",
  ItemRarityNameKnife: /* csgo_bulgarian.txt */"Нож",
  ItemRarityNameMachinegun: /* csgo_bulgarian.txt */"Картечница",
  ItemRarityNameMusicKit: /* csgo_bulgarian.txt */"Музикален комплект",
  ItemRarityNamePatch: /* csgo_bulgarian.txt */"Нашивка",
  ItemRarityNamePistol: /* csgo_bulgarian.txt */"Пистолет",
  ItemRarityNameRifle: /* csgo_bulgarian.txt */"Винтовка",
  ItemRarityNameSMG: /* csgo_bulgarian.txt */"Автомат",
  ItemRarityNameShotgun: /* csgo_bulgarian.txt */"Пушка",
  ItemRarityNameSniperRifle: /* csgo_bulgarian.txt */"Снайперистка винтовка",
  ItemRarityNameSticker: /* csgo_bulgarian.txt */"Стикер",
  ItemRarityNameTool: /* csgo_bulgarian.txt */"Инструмент",
  ItemRarityRare: /* csgo_bulgarian.txt */"Висок клас",
  ItemRarityUncommon: /* csgo_bulgarian.txt */"Средна поредица",
  ItemSwapStatTrakAccept: /* csgo_bulgarian.txt */"ПРИЕМАНЕ",
  ItemSwapStatTrakClose: /* csgo_bulgarian.txt */"Затваряне",
  ItemSwapStatTrakDesc: /* csgo_bulgarian.txt */"Този артикул разменя StatTrak™ стойностите между две оръжия от еднакъв тип.",
  ItemSwapStatTrakUse: /* csgo_bulgarian.txt */"Инструмент за StatTrak™ размяна",
  ItemSwapStatTrakWarn: /* csgo_bulgarian.txt */"Този инструмент за StatTrak™ размяна може да бъде използван само веднъж",
  ItemWeaponRarityAncient: /* csgo_bulgarian.txt */"Секретно оръжие",
  ItemWeaponRarityCommon: /* csgo_bulgarian.txt */"Потребителски клас",
  ItemWeaponRarityDefault: /* csgo_bulgarian.txt */"Обикновено оръжие",
  ItemWeaponRarityImmortal: /* csgo_bulgarian.txt */"Контрабанда",
  ItemWeaponRarityLegendary: /* csgo_bulgarian.txt */"Класифицирано оръжие",
  ItemWeaponRarityMythical: /* csgo_bulgarian.txt */"Ограничено оръжие",
  ItemWeaponRarityRare: /* csgo_bulgarian.txt */"Стандартен военен клас",
  ItemWeaponRarityUncommon: /* csgo_bulgarian.txt */"Индустриален клас",
  ItemWearBS: /* csgo_bulgarian.txt */"Белязан от битки",
  ItemWearFN: /* csgo_bulgarian.txt */"Фабрично нов",
  ItemWearFT: /* csgo_bulgarian.txt */"Тестван в полеви условия",
  ItemWearMW: /* csgo_bulgarian.txt */"Минимално износен",
  ItemWearWW: /* csgo_bulgarian.txt */"Доста износен",
  RemovePatchRemove: /* csgo_bulgarian.txt */"Премахване на нашивка",
  RemovePatchRemoveDesc: /* csgo_bulgarian.txt */"Моля, потвърдете, че бихте искали да премахнете тази нашивка от своя агент. Премахнатата нашивка ще бъде унищожена.",
  RemovePatchUse: /* csgo_bulgarian.txt */"Премахване на нашивка",
  RemovePatchWarn: /* csgo_bulgarian.txt */"Премахване на нашивка от",
  RenameCancel: /* csgo_bulgarian.txt */"Отказ",
  RenameEnterName: /* csgo_bulgarian.txt */"Въведете ново име за:",
  RenameRename: /* csgo_bulgarian.txt */"Преименуване на",
  RenameStorageUnitClose: /* csgo_bulgarian.txt */"Затваряне",
  RenameStorageUnitEnterName: /* csgo_bulgarian.txt */"Въведете ново име за:",
  RenameStorageUnitFirstNameWarn: /* csgo_bulgarian.txt */"Въведете описателен етикет за своя личен съхраняващ елемент и стартирайте да го използвате за складиране на артикули.",
  RenameStorageUnitNewNameWarn: /* csgo_bulgarian.txt */"Въведете нов описателен етикет за този съхраняващ елемент.",
  RenameStorageUnitRename: /* csgo_bulgarian.txt */"Персонализиране",
  RenameStorageUnitUse: /* csgo_bulgarian.txt */"Персонализирайте своя съхраняващ елемент",
  RenameUse: /* csgo_bulgarian.txt */"Използване на етикет за име",
  RenameWarn: /* csgo_bulgarian.txt */"Етикетът за име може да бъде използван само веднъж",
  ScrapeStickerCancel: /* csgo_bulgarian.txt */"Отказ",
  ScrapeStickerClose: /* csgo_bulgarian.txt */"Затваряне",
  ScrapeStickerRemove: /* csgo_bulgarian.txt */"Премахване на стикер",
  ScrapeStickerRemoveDesc: /* csgo_bulgarian.txt */"По-нататъшното одраскване на този стикер ще го премахне от артикула и той ще бъде унищожен.",
  ScrapeStickerUse: /* csgo_bulgarian.txt */"Одраскване на стикер",
  ScrapeStickerWarn: /* csgo_bulgarian.txt */"Одраскване на стикер от",
  SettingsMasterVolume: /* csgo_bulgarian.txt */"Основна сила на звука",
  StickerPickerRemove: /* csgo_bulgarian.txt */"Премахване"
};
