/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const czech = {
  ...english,
  ApplyPatchUse: /* csgo_czech.txt */"Použít nášivku",
  ApplyPatchWarn: /* csgo_czech.txt */"Nášivka může být použita pouze jednou",
  ApplyStickerCancel: /* csgo_czech.txt */"Zrušit",
  ApplyStickerUse: /* csgo_czech.txt */"Použít samolepku",
  ApplyStickerUseOn: /* csgo_czech.txt */"Použít na:",
  ApplyStickerWarn: /* csgo_czech.txt */"Samolepka může být použita pouze jednou",
  CaseAdd: /* csgo_czech.txt */"Přidat",
  CaseClose: /* csgo_czech.txt */"Zavřít",
  CaseContainsOne: /* csgo_czech.txt */"Obsahuje jeden z následujících předmětů:",
  CaseNeed: /* csgo_czech.txt */"Pro tuto akci je vyžadován předmět",
  CaseOnceWarn: /* csgo_czech.txt */"Tuto bednu je možné otevřít pouze jednou",
  CaseRareItem: /* csgo_czech.txt */"★ Speciální předmět ★",
  CaseUnlock: /* csgo_czech.txt */"Odemknout",
  CaseUnlockContainer: /* csgo_czech.txt */"Odemknout bednu",
  CaseUse: /* csgo_czech.txt */"Použít",
  CategoryAgent: /* csgo_czech.txt */"Agent",
  CategoryCase: /* csgo_czech.txt */"Bedna",
  CategoryCollectible: /* csgo_czech.txt */"Vyznamenání",
  CategoryEquipment: /* csgo_czech.txt */"Výbava",
  CategoryGlove: /* csgo_czech.txt */"Rukavice",
  CategoryGraffiti: /* csgo_czech.txt */"Graffiti",
  CategoryHeavy: /* csgo_czech.txt */"Těžké",
  CategoryKey: /* csgo_czech.txt */"Klíč",
  CategoryKnife: /* csgo_czech.txt */"Nůž",
  CategoryMusicKit: /* csgo_czech.txt */"Hudební balíček",
  CategoryPatch: /* csgo_czech.txt */"Nášivka",
  CategoryPistol: /* csgo_czech.txt */"Pistole",
  CategoryRifle: /* csgo_czech.txt */"Puška",
  CategorySMG: /* csgo_czech.txt */"Samopal",
  CategorySticker: /* csgo_czech.txt */"Samolepka",
  CategoryTool: /* csgo_czech.txt */"Nástroj",
  EditorCancel: /* csgo_czech.txt */"Zrušit",
  EditorNametag: /* csgo_czech.txt */"Štítek",
  EditorPatches: /* csgo_czech.txt */"Nášivky",
  EditorQuantity: /* csgo_czech.txt */"Množství",
  EditorRandom: /* csgo_czech.txt */"Náhodná",
  EditorReset: /* csgo_czech.txt */"Resetovat",
  EditorSave: /* csgo_czech.txt */"Uložit",
  EditorSeed: /* csgo_czech.txt */"Vzor",
  EditorStatTrak: /* csgo_czech.txt */"StatTrak™",
  EditorStickers: /* csgo_czech.txt */"Samolepky",
  EditorWear: /* csgo_czech.txt */"Povrch",
  InspectClose: /* csgo_czech.txt */"Zavřít",
  InventoryApplyPatch: /* csgo_czech.txt */"Použít nášivku",
  InventoryApplySticker: /* csgo_czech.txt */"Použít samolepku",
  InventoryFilterAgents: /* csgo_czech.txt */"Agenti",
  InventoryFilterAll: /* csgo_czech.txt */"Vše",
  InventoryFilterAllEquipment: /* csgo_czech.txt */"Všechna výbava",
  InventoryFilterAllGraphicArt: /* csgo_czech.txt */"Všechny obrázky",
  InventoryFilterAlphabetical: /* csgo_czech.txt */"Dle abecedy",
  InventoryFilterCollection: /* csgo_czech.txt */"Dle kolekce",
  InventoryFilterContainers: /* csgo_czech.txt */"BEDNY",
  InventoryFilterDisplay: /* csgo_czech.txt */"VYZNAMENÁNÍ",
  InventoryFilterEquipment: /* csgo_czech.txt */"VÝBAVA",
  InventoryFilterEquipped: /* csgo_czech.txt */"Dle vybavení",
  InventoryFilterEverything: /* csgo_czech.txt */"VŠE",
  InventoryFilterGloves: /* csgo_czech.txt */"Rukavice",
  InventoryFilterGraffiti: /* csgo_czech.txt */"Graffiti",
  InventoryFilterGraffitiBoxes: /* csgo_czech.txt */"Krabičky s graffiti",
  InventoryFilterGraphicArt: /* csgo_czech.txt */"OBRÁZKY",
  InventoryFilterMedals: /* csgo_czech.txt */"Medaile",
  InventoryFilterMelee: /* csgo_czech.txt */"Na blízko",
  InventoryFilterMidTier: /* csgo_czech.txt */"Střední třída",
  InventoryFilterMisc: /* csgo_czech.txt */"Různé",
  InventoryFilterMusicKits: /* csgo_czech.txt */"Hudební balíčky",
  InventoryFilterNewest: /* csgo_czech.txt */"Dle data získání",
  InventoryFilterPatches: /* csgo_czech.txt */"Nášivky",
  InventoryFilterPistols: /* csgo_czech.txt */"Pistole",
  InventoryFilterQuality: /* csgo_czech.txt */"Dle vzácnosti",
  InventoryFilterRifles: /* csgo_czech.txt */"Pušky",
  InventoryFilterSearch: /* csgo_czech.txt */"Zadej hledaný výraz",
  InventoryFilterSouvenirCases: /* csgo_czech.txt */"Bedny se suvenýry",
  InventoryFilterStickerCapsules: /* csgo_czech.txt */"Kapsle se samolepkami",
  InventoryFilterStickers: /* csgo_czech.txt */"Samolepky",
  InventoryFilterTools: /* csgo_czech.txt */"Nástroje",
  InventoryFilterType: /* csgo_czech.txt */"Dle typu",
  InventoryFilterWeaponCases: /* csgo_czech.txt */"Bedny se zbraněmi",
  InventoryItemContainsOne: /* csgo_czech.txt */"Obsahuje jeden z následujících předmětů:",
  InventoryItemDelete: /* csgo_czech.txt */"Odstranit",
  InventoryItemEdit: /* csgo_czech.txt */"Upravit",
  InventoryItemEquip: /* csgo_czech.txt */"Vybavit",
  InventoryItemExterior: /* csgo_czech.txt */"Povrch:",
  InventoryItemInspect: /* csgo_czech.txt */"Prohlédnout",
  InventoryItemInspectFinishCatalog: /* csgo_czech.txt */"Katalogové číslo",
  InventoryItemInspectInGame: /* csgo_czech.txt */"Prohlédnout ve hře...",
  InventoryItemInspectPatternTemplate: /* csgo_czech.txt */"Číslo šablony vzoru",
  InventoryItemInspectWearRating: /* csgo_czech.txt */"Opotřebení",
  InventoryItemMVPStatTrakCount: /* csgo_czech.txt */"Nejlepší hráč v kompetitivních zápasech:",
  InventoryItemNew: /* csgo_czech.txt */"Nový!",
  InventoryItemRareItem: /* csgo_czech.txt */"nebo speciální, extrémně vzácný předmět!",
  InventoryItemRarity: /* csgo_czech.txt */"Vzácnost:",
  InventoryItemRemovePatch: /* csgo_czech.txt */"Odebrat nášivku",
  InventoryItemRename: /* csgo_czech.txt */"Změnit název",
  InventoryItemRenameStorageUnit: /* csgo_czech.txt */"Změnit štítek",
  InventoryItemScrapeSticker: /* csgo_czech.txt */"Strhnout samolepku",
  InventoryItemStatTrak: /* csgo_czech.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_czech.txt */"StatTrak™ zabití:",
  InventoryItemStatTrakDesc: /* csgo_czech.txt */"Tento předmět disponuje technologií StatTrak™, která jeho vlastníkovi umožňuje sledovat určitou statistiku.",
  InventoryItemStorageUnitDeposit: /* csgo_czech.txt */"Uložit předměty",
  InventoryItemStorageUnitEmptyBody: /* csgo_czech.txt */"Tento úložný kontejner je momentálně prázdný, nicméně nabízí prostor až pro {1} předmětů, které by se jinak nevešly do tvého inventáře. Předměty můžeš kdykoli přesunout do kontejneru nebo si je z kontejneru naopak vyzvednout. Případně můžeš kontejner použít také pro uložení svých sběratelských předmětů a vhodně mu změnit název.",
  InventoryItemStorageUnitEmptyClose: /* csgo_czech.txt */"OK",
  InventoryItemStorageUnitEmptyTitle: /* csgo_czech.txt */"Úložný kontejner je prázdný",
  InventoryItemStorageUnitInspect: /* csgo_czech.txt */"Prohlédnout",
  InventoryItemStorageUnitRetrieve: /* csgo_czech.txt */"Vyzvednout předměty",
  InventoryItemSwapStatTrak: /* csgo_czech.txt */"Otevřít prohazovač statistik StatTrak™",
  InventoryItemTeam: /* csgo_czech.txt */"Tým:",
  InventoryItemTeamAny: /* csgo_czech.txt */"Oba",
  InventoryItemTeamCT: /* csgo_czech.txt */"Counter-Teroristé",
  InventoryItemTeamT: /* csgo_czech.txt */"Teroristé",
  InventoryItemUnequip: /* csgo_czech.txt */"Sundat",
  InventoryItemUnlockContainer: /* csgo_czech.txt */"Odemknout bednu",
  InventoryItemUseStorageUnit: /* csgo_czech.txt */"Začít používat kontejner",
  InventorySelectAnItem: /* csgo_czech.txt */"Vyber předmět, který chceš použít s:",
  InventorySelectInspectContents: /* csgo_czech.txt */"Prohlížíš si obsah",
  InventorySelectItemToDeposit: /* csgo_czech.txt */"Vyber předměty, které chceš přesunout do",
  InventorySelectItemToRetrieve: /* csgo_czech.txt */"Vyber předměty, které chceš vyzvednout z",
  ItemRarityAncient: /* csgo_czech.txt */"Mimořádná",
  ItemRarityCommon: /* csgo_czech.txt */"Základní třída",
  ItemRarityDefault: /* csgo_czech.txt */"Základní",
  ItemRarityImmortal: /* csgo_czech.txt */"Pašovaná",
  ItemRarityLegendary: /* csgo_czech.txt */"Exotická",
  ItemRarityMythical: /* csgo_czech.txt */"Významná",
  ItemRarityNameAgent: /* csgo_czech.txt */"Agent",
  ItemRarityNameCollectible: /* csgo_czech.txt */"Vyznamenání",
  ItemRarityNameContainer: /* csgo_czech.txt */"Bedna",
  ItemRarityNameContract: /* csgo_czech.txt */"Kontrakt",
  ItemRarityNameEquipment: /* csgo_czech.txt */"Výbava",
  ItemRarityNameGloves: /* csgo_czech.txt */"Rukavice",
  ItemRarityNameGraffiti: /* csgo_czech.txt */"Graffiti",
  ItemRarityNameKey: /* csgo_czech.txt */"Klíč",
  ItemRarityNameKnife: /* csgo_czech.txt */"Nůž",
  ItemRarityNameMachinegun: /* csgo_czech.txt */"Kulomet",
  ItemRarityNameMusicKit: /* csgo_czech.txt */"Hudební balíček",
  ItemRarityNamePatch: /* csgo_czech.txt */"Nášivka",
  ItemRarityNamePistol: /* csgo_czech.txt */"Pistole",
  ItemRarityNameRifle: /* csgo_czech.txt */"Puška",
  ItemRarityNameSMG: /* csgo_czech.txt */"Samopal",
  ItemRarityNameShotgun: /* csgo_czech.txt */"Brokovnice",
  ItemRarityNameSniperRifle: /* csgo_czech.txt */"Odstřelovací puška",
  ItemRarityNameSticker: /* csgo_czech.txt */"Samolepka",
  ItemRarityNameTool: /* csgo_czech.txt */"Nástroj",
  ItemRarityRare: /* csgo_czech.txt */"Vyšší třída",
  ItemRarityUncommon: /* csgo_czech.txt */"Střední třída",
  ItemSwapStatTrakAccept: /* csgo_czech.txt */"PŘIJMOUT",
  ItemSwapStatTrakClose: /* csgo_czech.txt */"Zavřít",
  ItemSwapStatTrakDesc: /* csgo_czech.txt */"Tento nástroj prohodí statistiky mezi dvěma předměty stejného typu.",
  ItemSwapStatTrakUse: /* csgo_czech.txt */"Prohazovač statistik StatTrak™",
  ItemSwapStatTrakWarn: /* csgo_czech.txt */"Tento nástroj může být použit pouze jednou",
  ItemWeaponRarityAncient: /* csgo_czech.txt */"Skrytá",
  ItemWeaponRarityCommon: /* csgo_czech.txt */"Neotestovaná",
  ItemWeaponRarityDefault: /* csgo_czech.txt */"Základní",
  ItemWeaponRarityImmortal: /* csgo_czech.txt */"Pašovaná",
  ItemWeaponRarityLegendary: /* csgo_czech.txt */"Tajná",
  ItemWeaponRarityMythical: /* csgo_czech.txt */"Zakázaná",
  ItemWeaponRarityRare: /* csgo_czech.txt */"Armádní",
  ItemWeaponRarityUncommon: /* csgo_czech.txt */"Prověřená",
  ItemWearBS: /* csgo_czech.txt */"Poničený bojem",
  ItemWearFN: /* csgo_czech.txt */"Zbrusu nový",
  ItemWearFT: /* csgo_czech.txt */"Opotřebený",
  ItemWearMW: /* csgo_czech.txt */"Lehce opotřebený",
  ItemWearWW: /* csgo_czech.txt */"Silně opotřebený",
  RemovePatchRemove: /* csgo_czech.txt */"Odebrat nášivku",
  RemovePatchRemoveDesc: /* csgo_czech.txt */"Potvrď odebrání této nášivky z agenta. Pamatuj však, že nášivka bude zničena.",
  RemovePatchUse: /* csgo_czech.txt */"Odebrat nášivku",
  RemovePatchWarn: /* csgo_czech.txt */"Odebrat nášivku z:",
  RenameCancel: /* csgo_czech.txt */"Zrušit",
  RenameEnterName: /* csgo_czech.txt */"Zadej nový název pro:",
  RenameRename: /* csgo_czech.txt */"Změnit název",
  RenameStorageUnitClose: /* csgo_czech.txt */"Zavřít",
  RenameStorageUnitEnterName: /* csgo_czech.txt */"Zadej nový název pro:",
  RenameStorageUnitFirstNameWarn: /* csgo_czech.txt */"Zadej popisný štítek pro tento úložný kontejner a začni ho používat.",
  RenameStorageUnitNewNameWarn: /* csgo_czech.txt */"Zadej nový popisný štítek pro tento úložný kontejner.",
  RenameStorageUnitRename: /* csgo_czech.txt */"Přizpůsobit",
  RenameStorageUnitUse: /* csgo_czech.txt */"Přizpůsob si úložný kontejner",
  RenameUse: /* csgo_czech.txt */"Použít štítek",
  RenameWarn: /* csgo_czech.txt */"Štítek může být použit pouze jednou",
  ScrapeStickerCancel: /* csgo_czech.txt */"Zrušit",
  ScrapeStickerClose: /* csgo_czech.txt */"Zavřít",
  ScrapeStickerRemove: /* csgo_czech.txt */"Odebrat samolepku",
  ScrapeStickerRemoveDesc: /* csgo_czech.txt */"Pokud strhneš samolepku celou, navždy ji ze zbraně odebereš a samolepka bude zničena.",
  ScrapeStickerUse: /* csgo_czech.txt */"Strhnout samolepku",
  ScrapeStickerWarn: /* csgo_czech.txt */"Strhnout samolepku z:",
  StickerPickerRemove: /* csgo_czech.txt */"Odebrat"
};
