/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const dutch = {
  ...english,
  ApplyPatchUse: /* csgo_dutch.txt */"Embleem aanbrengen",
  ApplyPatchWarn: /* csgo_dutch.txt */"Een embleem kan maar één keer aangebracht worden",
  ApplyStickerCancel: /* csgo_dutch.txt */"Annuleren",
  ApplyStickerUse: /* csgo_dutch.txt */"Sticker aanbrengen",
  ApplyStickerUseOn: /* csgo_dutch.txt */"Gebruik op",
  ApplyStickerWarn: /* csgo_dutch.txt */"Een sticker kan maar één keer toegepast worden",
  CaseAdd: /* csgo_dutch.txt */"Toevoegen",
  CaseClose: /* csgo_dutch.txt */"Sluiten",
  CaseContainsOne: /* csgo_dutch.txt */"Bevat één van de volgende:",
  CaseNeed: /* csgo_dutch.txt */"Voor deze actie is een  vereist",
  CaseOnceWarn: /* csgo_dutch.txt */"Deze kist kan maar één keer geopend worden",
  CaseRareItem: /* csgo_dutch.txt */"★ Zeldzaam speciaal voorwerp ★",
  CaseUnlock: /* csgo_dutch.txt */"ontgrendelen",
  CaseUnlockContainer: /* csgo_dutch.txt */"Kist openen",
  CaseUse: /* csgo_dutch.txt */"gebruiken",
  CategoryAgent: /* csgo_dutch.txt */"Agent",
  CategoryCase: /* csgo_dutch.txt */"Container",
  CategoryCollectible: /* csgo_dutch.txt */"Verzamelvoorwerp",
  CategoryEquipment: /* csgo_dutch.txt */"Uitrusting",
  CategoryGlove: /* csgo_dutch.txt */"Handschoenen",
  CategoryGraffiti: /* csgo_dutch.txt */"Graffiti",
  CategoryHeavy: /* csgo_dutch.txt */"Zwaar",
  CategoryKey: /* csgo_dutch.txt */"Sleutel",
  CategoryKnife: /* csgo_dutch.txt */"Mes",
  CategoryMusicKit: /* csgo_dutch.txt */"Muziekset",
  CategoryPatch: /* csgo_dutch.txt */"Embleem",
  CategoryPistol: /* csgo_dutch.txt */"Pistool",
  CategoryRifle: /* csgo_dutch.txt */"Geweer",
  CategorySMG: /* csgo_dutch.txt */"SMG",
  CategorySticker: /* csgo_dutch.txt */"Sticker",
  CategoryTool: /* csgo_dutch.txt */"Gereedschap",
  EditorCancel: /* csgo_dutch.txt */"Annuleren",
  EditorNametag: /* csgo_dutch.txt */"Naamplaat",
  EditorPatches: /* csgo_dutch.txt */"Emblemen",
  EditorQuantity: /* csgo_dutch.txt */"Aantal",
  EditorRandom: /* csgo_dutch.txt */"Willekeurig",
  EditorReset: /* csgo_dutch.txt */"Terugzetten",
  EditorSave: /* csgo_dutch.txt */"Opslaan",
  EditorSeed: /* csgo_dutch.txt */"Patroon",
  EditorStatTrak: /* csgo_dutch.txt */"StatTrak™",
  EditorStickers: /* csgo_dutch.txt */"Stickers",
  EditorWear: /* csgo_dutch.txt */"Dragen",
  InspectClose: /* csgo_dutch.txt */"Sluiten",
  InventoryApplyPatch: /* csgo_dutch.txt */"Embleem aanbrengen",
  InventoryApplySticker: /* csgo_dutch.txt */"Sticker toepassen",
  InventoryFilterAgents: /* csgo_dutch.txt */"Agenten",
  InventoryFilterAll: /* csgo_dutch.txt */"Alles",
  InventoryFilterAllEquipment: /* csgo_dutch.txt */"Alle uitrusting",
  InventoryFilterAllGraphicArt: /* csgo_dutch.txt */"Alle illustraties",
  InventoryFilterAlphabetical: /* csgo_dutch.txt */"Alfabetisch",
  InventoryFilterCollection: /* csgo_dutch.txt */"Collectie",
  InventoryFilterContainers: /* csgo_dutch.txt */"CONTAINERS",
  InventoryFilterDisplay: /* csgo_dutch.txt */"DISPLAY",
  InventoryFilterEquipment: /* csgo_dutch.txt */"UITRUSTING",
  InventoryFilterEquipped: /* csgo_dutch.txt */"Uitgerust",
  InventoryFilterEverything: /* csgo_dutch.txt */"ALLES",
  InventoryFilterGloves: /* csgo_dutch.txt */"Handschoenen",
  InventoryFilterGraffiti: /* csgo_dutch.txt */"Graffiti",
  InventoryFilterGraffitiBoxes: /* csgo_dutch.txt */"Graffitidozen",
  InventoryFilterGraphicArt: /* csgo_dutch.txt */"GRAFISCH",
  InventoryFilterMedals: /* csgo_dutch.txt */"Medailles",
  InventoryFilterMelee: /* csgo_dutch.txt */"Slagwapen",
  InventoryFilterMidTier: /* csgo_dutch.txt */"Mid-Tier",
  InventoryFilterMisc: /* csgo_dutch.txt */"Diversen",
  InventoryFilterMusicKits: /* csgo_dutch.txt */"Muzieksets",
  InventoryFilterNewest: /* csgo_dutch.txt */"Nieuwste",
  InventoryFilterPatches: /* csgo_dutch.txt */"Emblemen",
  InventoryFilterPistols: /* csgo_dutch.txt */"Pistolen",
  InventoryFilterQuality: /* csgo_dutch.txt */"Kwaliteit",
  InventoryFilterRifles: /* csgo_dutch.txt */"Geweren",
  InventoryFilterSearch: /* csgo_dutch.txt */"Typ hier om te zoeken",
  InventoryFilterSouvenirCases: /* csgo_dutch.txt */"Souvenirkisten",
  InventoryFilterStickerCapsules: /* csgo_dutch.txt */"Stickercapsules",
  InventoryFilterStickers: /* csgo_dutch.txt */"Stickers",
  InventoryFilterTools: /* csgo_dutch.txt */"Tools",
  InventoryFilterType: /* csgo_dutch.txt */"Type",
  InventoryFilterWeaponCases: /* csgo_dutch.txt */"Wapenkisten",
  InventoryItemContainsOne: /* csgo_dutch.txt */"Bevat één van de volgende:",
  InventoryItemDelete: /* csgo_dutch.txt */"Verwijderen",
  InventoryItemEdit: /* csgo_dutch.txt */"Bewerken",
  InventoryItemEquip: /* csgo_dutch.txt */"Uitrusten",
  InventoryItemExterior: /* csgo_dutch.txt */"Staat:",
  InventoryItemInspect: /* csgo_dutch.txt */"Inspecteren",
  InventoryItemInspectFinishCatalog: /* csgo_dutch.txt */"Afwerkingscatalogus",
  InventoryItemInspectInGame: /* csgo_dutch.txt */"In-game bekijken...",
  InventoryItemInspectPatternTemplate: /* csgo_dutch.txt */"Patroonsjabloon",
  InventoryItemInspectWearRating: /* csgo_dutch.txt */"Slijtagescore",
  InventoryItemMVPStatTrakCount: /* csgo_dutch.txt */"StatTrak™ officiële competitieve MVPs:",
  InventoryItemNew: /* csgo_dutch.txt */"Nieuw!",
  InventoryItemRareItem: /* csgo_dutch.txt */"of een extreem zeldzaam speciaal voorwerp!",
  InventoryItemRarity: /* csgo_dutch.txt */"Zeldzaamheid:",
  InventoryItemRemovePatch: /* csgo_dutch.txt */"Embleem verwijderen",
  InventoryItemRename: /* csgo_dutch.txt */"andere naam geven",
  InventoryItemRenameStorageUnit: /* csgo_dutch.txt */"Label wijzigen",
  InventoryItemScrapeSticker: /* csgo_dutch.txt */"Sticker schrapen",
  InventoryItemStatTrak: /* csgo_dutch.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_dutch.txt */"StatTrak™-bevestigde doden:",
  InventoryItemStatTrakDesc: /* csgo_dutch.txt */"Dit voorwerp maakt gebruik van StatTrak™-technologie die bepaalde statistieken bijhoudt wanneer deze door de eigenaar in gebruik is.",
  InventoryItemStorageUnitDeposit: /* csgo_dutch.txt */"Voorwerpen opslaan",
  InventoryItemStorageUnitEmptyBody: /* csgo_dutch.txt */"This Storage Unit allows you to store up to {1} of your surplus items which would otherwise exceed inventory limit. The selected Storage Unit is currently empty. At any time you can move items from your inventory into this Storage Unit, retrieve items back into your inventory, or you can just use it to organize your collectibles.",
  InventoryItemStorageUnitEmptyClose: /* csgo_dutch.txt */"OK",
  InventoryItemStorageUnitEmptyTitle: /* csgo_dutch.txt */"Opslageenheid is leeg",
  InventoryItemStorageUnitInspect: /* csgo_dutch.txt */"Inspecteren",
  InventoryItemStorageUnitRetrieve: /* csgo_dutch.txt */"Voorwerpen ophalen",
  InventoryItemSwapStatTrak: /* csgo_dutch.txt */"StatTrak™-verwisselgereedschap openen",
  InventoryItemTeam: /* csgo_dutch.txt */"Team:",
  InventoryItemTeamAny: /* csgo_dutch.txt */"Beide",
  InventoryItemTeamCT: /* csgo_dutch.txt */"Counter-Terrorist",
  InventoryItemTeamT: /* csgo_dutch.txt */"Terrorist",
  InventoryItemUnequip: /* csgo_dutch.txt */"Uitdoen",
  InventoryItemUnlockContainer: /* csgo_dutch.txt */"Kist openen",
  InventoryItemUseStorageUnit: /* csgo_dutch.txt */"Deze eenheid gebruiken",
  InventorySelectAnItem: /* csgo_dutch.txt */"Selecteer een voorwerp om te gebruiken met:",
  InventorySelectInspectContents: /* csgo_dutch.txt */"Inhoud controleren van",
  InventorySelectItemToDeposit: /* csgo_dutch.txt */"Kies de voorwerpen die je wilt verplaatsen in",
  InventorySelectItemToRetrieve: /* csgo_dutch.txt */"Kies de voorwerpen die je wilt ophalen van",
  ItemRarityAncient: /* csgo_dutch.txt */"Buitengewoon",
  ItemRarityCommon: /* csgo_dutch.txt */"Standaard-rang",
  ItemRarityDefault: /* csgo_dutch.txt */"Standaard",
  ItemRarityImmortal: /* csgo_dutch.txt */"Smokkelwaar",
  ItemRarityLegendary: /* csgo_dutch.txt */"Exotisch",
  ItemRarityMythical: /* csgo_dutch.txt */"Opmerkelijk",
  ItemRarityNameAgent: /* csgo_dutch.txt */"Agent",
  ItemRarityNameCollectible: /* csgo_dutch.txt */"Verzamelvoorwerp",
  ItemRarityNameContainer: /* csgo_dutch.txt */"Container",
  ItemRarityNameContract: /* csgo_dutch.txt */"Contract",
  ItemRarityNameEquipment: /* csgo_dutch.txt */"Uitrusting",
  ItemRarityNameGloves: /* csgo_dutch.txt */"Handschoenen",
  ItemRarityNameGraffiti: /* csgo_dutch.txt */"Graffiti",
  ItemRarityNameKey: /* csgo_dutch.txt */"Sleutel",
  ItemRarityNameKnife: /* csgo_dutch.txt */"Mes",
  ItemRarityNameMachinegun: /* csgo_dutch.txt */"Machinegeweer",
  ItemRarityNameMusicKit: /* csgo_dutch.txt */"Muziekset",
  ItemRarityNamePatch: /* csgo_dutch.txt */"Embleem",
  ItemRarityNamePistol: /* csgo_dutch.txt */"Pistool",
  ItemRarityNameRifle: /* csgo_dutch.txt */"Geweer",
  ItemRarityNameSMG: /* csgo_dutch.txt */"SMG",
  ItemRarityNameShotgun: /* csgo_dutch.txt */"Shotgun",
  ItemRarityNameSniperRifle: /* csgo_dutch.txt */"Snipergeweer",
  ItemRarityNameSticker: /* csgo_dutch.txt */"Sticker",
  ItemRarityNameTool: /* csgo_dutch.txt */"Gereedschap",
  ItemRarityRare: /* csgo_dutch.txt */"Hoge rang",
  ItemRarityUncommon: /* csgo_dutch.txt */"Gemiddelde rang",
  ItemSwapStatTrakAccept: /* csgo_dutch.txt */"ACCEPTEREN",
  ItemSwapStatTrakClose: /* csgo_dutch.txt */"Sluiten",
  ItemSwapStatTrakDesc: /* csgo_dutch.txt */"Dit voorwerp verwisselt de StatTrak™-waarden tussen twee voorwerpen van hetzelfde type.",
  ItemSwapStatTrakUse: /* csgo_dutch.txt */"StatTrak™-verwisselgereedschap",
  ItemSwapStatTrakWarn: /* csgo_dutch.txt */"Dit StatTrak™-verwisselgereedschap kan slechts eenmaal worden gebruikt",
  ItemWeaponRarityAncient: /* csgo_dutch.txt */"Verborgen",
  ItemWeaponRarityCommon: /* csgo_dutch.txt */"Consumenten-rang",
  ItemWeaponRarityDefault: /* csgo_dutch.txt */"Standaard",
  ItemWeaponRarityImmortal: /* csgo_dutch.txt */"Smokkelwaar",
  ItemWeaponRarityLegendary: /* csgo_dutch.txt */"Geheim",
  ItemWeaponRarityMythical: /* csgo_dutch.txt */"Beperkt",
  ItemWeaponRarityRare: /* csgo_dutch.txt */"Mil-Spec-rang",
  ItemWeaponRarityUncommon: /* csgo_dutch.txt */"Industrie-rang",
  ItemWearBS: /* csgo_dutch.txt */"Door strijd gehavend",
  ItemWearFN: /* csgo_dutch.txt */"Gloednieuw",
  ItemWearFT: /* csgo_dutch.txt */"In de praktijk getest",
  ItemWearMW: /* csgo_dutch.txt */"Nauwelijks gebruikt",
  ItemWearWW: /* csgo_dutch.txt */"Behoorlijk gebruikt",
  RemovePatchRemove: /* csgo_dutch.txt */"Embleem verwijderen",
  RemovePatchRemoveDesc: /* csgo_dutch.txt */"Bevestig dat je dit embleem van je agent wilt verwijderen. Het verwijderde embleem zal worden vernietigd.",
  RemovePatchUse: /* csgo_dutch.txt */"Embleem verwijderen",
  RemovePatchWarn: /* csgo_dutch.txt */"Remove a patch from",
  RenameCancel: /* csgo_dutch.txt */"Annuleren",
  RenameEnterName: /* csgo_dutch.txt */"Voer een nieuwe naam in voor",
  RenameRename: /* csgo_dutch.txt */"andere naam geven",
  RenameStorageUnitClose: /* csgo_dutch.txt */"Sluiten",
  RenameStorageUnitEnterName: /* csgo_dutch.txt */"Voer een nieuwe naam in voor",
  RenameStorageUnitFirstNameWarn: /* csgo_dutch.txt */"Enter a descriptive label for your personal Storage Unit and start using it for storing items.",
  RenameStorageUnitNewNameWarn: /* csgo_dutch.txt */"Enter a new descriptive label for this Storage Unit.",
  RenameStorageUnitRename: /* csgo_dutch.txt */"Personaliseren",
  RenameStorageUnitUse: /* csgo_dutch.txt */"Personalize Your Storage Unit",
  RenameUse: /* csgo_dutch.txt */"Naamplaat kopen",
  RenameWarn: /* csgo_dutch.txt */"Een naamplaat kan maar eenmalig gebruikt worden",
  ScrapeStickerCancel: /* csgo_dutch.txt */"Annuleren",
  ScrapeStickerClose: /* csgo_dutch.txt */"Sluiten",
  ScrapeStickerRemove: /* csgo_dutch.txt */"Sticker verwijderen",
  ScrapeStickerRemoveDesc: /* csgo_dutch.txt */"Als je deze sticker verder schraapt zal het worden verwijderd van het voorwerp en worden vernietigd.",
  ScrapeStickerUse: /* csgo_dutch.txt */"Sticker schrapen",
  ScrapeStickerWarn: /* csgo_dutch.txt */"Schraap een sticker van",
  StickerPickerRemove: /* csgo_dutch.txt */"Verwijderen"
};
