/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// prettier-ignore
export const english = {

  APIPageHeader: "API for programmers",
  ApplyPatchUse: /* csgo_english.txt */"Apply Patch",
  ApplyPatchWarn: /* csgo_english.txt */"A patch can only be applied once",
  ApplyStickerCancel: /* csgo_english.txt */"Cancel",
  ApplyStickerUse: /* csgo_english.txt */"Apply Sticker",
  ApplyStickerUseOn: /* csgo_english.txt */"Use on",
  ApplyStickerWarn: /* csgo_english.txt */"A sticker can only be applied once",
  CaseAdd: /* csgo_english.txt */"Add",
  CaseAddKeyConfirm: "Confirm key craft",
  CaseClose: /* csgo_english.txt */"Close",
  CaseContainsOne: /* csgo_english.txt */"Contains one of the following:",
  CaseNeed: /* csgo_english.txt */"This action requires a",
  CaseOnceWarn: /* csgo_english.txt */"This Container can only be opened once",
  CaseRareItem: /* csgo_english.txt */"★ Rare Special Item ★",
  CaseSeed: "SEED",
  CaseUnlock: /* csgo_english.txt */"Unlock",
  CaseUnlockContainer: /* csgo_english.txt */"Unlock Container",
  CaseUse: /* csgo_english.txt */"Use",
  CaseWear: "WEAR",
  CategoryAgent: /* csgo_english.txt */"Agent",
  CategoryCase: /* csgo_english.txt */"Container",
  CategoryCollectible: /* csgo_english.txt */"Collectible",
  CategoryEquipment: /* csgo_english.txt */"Equipment",
  CategoryGlove: /* csgo_english.txt */"Gloves",
  CategoryGraffiti: /* csgo_english.txt */"Graffiti",
  CategoryHeavy: /* csgo_english.txt */"Heavy",
  CategoryKey: /* csgo_english.txt */"Key",
  CategoryKnife: /* csgo_english.txt */"Knife",
  CategoryMusicKit: /* csgo_english.txt */"Music Kit",
  CategoryPatch: /* csgo_english.txt */"Patch",
  CategoryPistol: /* csgo_english.txt */"Pistol",
  CategoryRifle: /* csgo_english.txt */"Rifle",
  CategorySMG: /* csgo_english.txt */"SMG",
  CategorySticker: /* csgo_english.txt */"Sticker",
  CategoryTool: /* csgo_english.txt */"Tool",
  CraftBy: "Crafted by",
  CraftConfirmHeader: "Confirm craft",
  CraftSearchPlaceholder: "Search for an item...",
  CraftSelectHeader: "Crafting an item...",
  CraftSharedHeader: "Shared craft",
  EditorCancel: /* csgo_english.txt */"Cancel",
  EditorCraft: "Craft",
  EditorNametag: /* csgo_english.txt */"Name Tag",
  EditorNametagPlaceholder: "Type a custom name...",
  EditorPatches: /* csgo_english.txt */"Patches",
  EditorQuantity: /* csgo_english.txt */"Quantity",
  EditorRandom: /* csgo_english.txt */"Random",
  EditorReset: /* csgo_english.txt */"Reset",
  EditorSave: /* csgo_english.txt */"Save",
  EditorSeed: /* csgo_english.txt */"Pattern",
  EditorStatTrak: /* csgo_english.txt */"StatTrak™",
  EditorStickerWear: "Sticker wear",
  EditorStickers: /* csgo_english.txt */"Stickers",
  EditorWear: /* csgo_english.txt */"Wear",
  GridItemNoItemsToDisplay: "No items to display",
  HeaderAPILabel: "API",
  HeaderCraftCannotCraft: "You cannot craft.",
  HeaderCraftInventoryFull: "Your inventory is full.",
  HeaderCraftLabel: "Craft Item",
  HeaderDonate: "Donate",
  HeaderInventoryLabel: "Inventory",
  HeaderSettingsLabel: "Settings",
  HeaderSignInLabel: "Sign-in to sync",
  HeaderSignOutLabel: "Sign out",
  HeaderSignedInAsLabel: "Signed in as",
  InspectClose: /* csgo_english.txt */"Close",
  InventoryApplyPatch: /* csgo_english.txt */"Apply Patch",
  InventoryApplySticker: /* csgo_english.txt */"Apply Sticker",
  InventoryFilterAgents: /* csgo_english.txt */"Agents",
  InventoryFilterAll: /* csgo_english.txt */"All",
  InventoryFilterAllEquipment: /* csgo_english.txt */"All Equipment",
  InventoryFilterAllGraphicArt: /* csgo_english.txt */"All Graphic Art",
  InventoryFilterAlphabetical: /* csgo_english.txt */"Alphabetical",
  InventoryFilterCollection: /* csgo_english.txt */"Collection",
  InventoryFilterContainers: /* csgo_english.txt */"CONTAINERS",
  InventoryFilterDisplay: /* csgo_english.txt */"DISPLAY",
  InventoryFilterEquipment: /* csgo_english.txt */"EQUIPMENT",
  InventoryFilterEquipped: /* csgo_english.txt */"Equipped",
  InventoryFilterEverything: /* csgo_english.txt */"EVERYTHING",
  InventoryFilterGloves: /* csgo_english.txt */"Gloves",
  InventoryFilterGraffiti: /* csgo_english.txt */"Graffiti",
  InventoryFilterGraffitiBoxes: /* csgo_english.txt */"Graffiti Boxes",
  InventoryFilterGraphicArt: /* csgo_english.txt */"GRAPHIC ART",
  InventoryFilterMedals: /* csgo_english.txt */"Medals",
  InventoryFilterMelee: /* csgo_english.txt */"Melee",
  InventoryFilterMidTier: /* csgo_english.txt */"Mid-Tier",
  InventoryFilterMisc: /* csgo_english.txt */"Misc",
  InventoryFilterMusicKits: /* csgo_english.txt */"Music Kits",
  InventoryFilterNewest: /* csgo_english.txt */"Newest",
  InventoryFilterPatches: /* csgo_english.txt */"Patches",
  InventoryFilterPistols: /* csgo_english.txt */"Pistols",
  InventoryFilterQuality: /* csgo_english.txt */"Quality",
  InventoryFilterRifles: /* csgo_english.txt */"Rifles",
  InventoryFilterSearch: /* csgo_english.txt */"Type search here",
  InventoryFilterSouvenirCases: /* csgo_english.txt */"Souvenir Cases",
  InventoryFilterStickerCapsules: /* csgo_english.txt */"Sticker Capsules",
  InventoryFilterStickers: /* csgo_english.txt */"Stickers",
  InventoryFilterTools: /* csgo_english.txt */"Tools",
  InventoryFilterType: /* csgo_english.txt */"Type",
  InventoryFilterWeaponCases: /* csgo_english.txt */"Weapon Cases",
  InventoryItemContainsOne: /* csgo_english.txt */"Contains one of the following:",
  InventoryItemDelete: /* csgo_english.txt */"Delete",
  InventoryItemEdit: /* csgo_english.txt */"Edit",
  InventoryItemEquip: /* csgo_english.txt */"Equip",
  InventoryItemEquipBothTeams: "Equip Both Teams",
  InventoryItemEquipCT: "Equip CT",
  InventoryItemEquipT: "Equip T",
  InventoryItemExterior: /* csgo_english.txt */"Exterior:",
  InventoryItemInspect: /* csgo_english.txt */"Inspect",
  InventoryItemInspectCopied: "Command copied!",
  InventoryItemInspectFinishCatalog: /* csgo_english.txt */"Finish Catalog",
  InventoryItemInspectInGame: /* csgo_english.txt */"Inspect in Game...",
  InventoryItemInspectPatternTemplate: /* csgo_english.txt */"Pattern Template",
  InventoryItemInspectWearRating: /* csgo_english.txt */"Wear Rating",
  InventoryItemMVPStatTrakCount: /* csgo_english.txt */"StatTrak™ Official Competitive MVPs:",
  InventoryItemNew: /* csgo_english.txt */"New!",
  InventoryItemRareItem: /* csgo_english.txt */"or an Exceedingly Rare Special Item!",
  InventoryItemRarity: /* csgo_english.txt */"Rarity:",
  InventoryItemRemovePatch: /* csgo_english.txt */"Remove Patch",
  InventoryItemRename: /* csgo_english.txt */"Rename",
  InventoryItemRenameStorageUnit: /* csgo_english.txt */"Change Label",
  InventoryItemScrapeSticker: /* csgo_english.txt */"Scrape Sticker",
  InventoryItemSeed: "Seed:",
  InventoryItemShare: "Share",
  InventoryItemShareCopied: "Link copied!",
  InventoryItemStatTrak: /* csgo_english.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_english.txt */"StatTrak™ Confirmed Kills:",
  InventoryItemStatTrakDesc: /* csgo_english.txt */"This item features StatTrak™ technology, which tracks certain statistics when equipped by its owner.",
  InventoryItemStorageUnitDeposit: /* csgo_english.txt */"Deposit Items",
  InventoryItemStorageUnitEmptyBody: /* csgo_english.txt */"This Storage Unit allows you to store up to {1} of your surplus items which would otherwise exceed inventory limit. The selected Storage Unit is currently empty. At any time you can move items from your inventory into this Storage Unit, retrieve items back into your inventory, or you can just use it to organize your collectibles.",
  InventoryItemStorageUnitEmptyClose: /* csgo_english.txt */"OK",
  InventoryItemStorageUnitEmptyTitle: /* csgo_english.txt */"Empty Storage Unit",
  InventoryItemStorageUnitInspect: /* csgo_english.txt */"Inspect",
  InventoryItemStorageUnitRetrieve: /* csgo_english.txt */"Retrieve Items",
  InventoryItemSwapStatTrak: /* csgo_english.txt */"Open StatTrak™ Swap Tool",
  InventoryItemTeam: /* csgo_english.txt */"Team:",
  InventoryItemTeamAny: /* csgo_english.txt */"Any",
  InventoryItemTeamCT: /* csgo_english.txt */"Counter-Terrorist",
  InventoryItemTeamT: /* csgo_english.txt */"Terrorist",
  InventoryItemUnequip: /* csgo_english.txt */"Unequip",
  InventoryItemUnequipCT: "Unequip CT",
  InventoryItemUnequipT: "Unequip T",
  InventoryItemUnlockContainer: /* csgo_english.txt */"Unlock Container",
  InventoryItemUseStorageUnit: /* csgo_english.txt */"Start Using This Unit",
  InventoryItemWear: "Wear:",
  InventoryNoItemsToDisplay: "No items to display",
  InventorySelectAnItem: /* csgo_english.txt */"Select an item to use with:",
  InventorySelectInspectContents: /* csgo_english.txt */"Inspecting contents of",
  InventorySelectItemToDeposit: /* csgo_english.txt */"Select items to move into",
  InventorySelectItemToRetrieve: /* csgo_english.txt */"Select items to retrieve from",
  ItemRarityAncient: /* csgo_english.txt */"Extraordinary",
  ItemRarityCommon: /* csgo_english.txt */"Base Grade",
  ItemRarityDefault: /* csgo_english.txt */"Default",
  ItemRarityFormat: "{1} {2}",
  ItemRarityImmortal: /* csgo_english.txt */"Contraband",
  ItemRarityLegendary: /* csgo_english.txt */"Exotic",
  ItemRarityMythical: /* csgo_english.txt */"Remarkable",
  ItemRarityNameAgent: /* csgo_english.txt */"Agent",
  ItemRarityNameCollectible: /* csgo_english.txt */"Collectible",
  ItemRarityNameContainer: /* csgo_english.txt */"Container",
  ItemRarityNameContract: /* csgo_english.txt */"Contract",
  ItemRarityNameEquipment: /* csgo_english.txt */"Equipment",
  ItemRarityNameGloves: /* csgo_english.txt */"Gloves",
  ItemRarityNameGraffiti: /* csgo_english.txt */"Graffiti",
  ItemRarityNameKey: /* csgo_english.txt */"Key",
  ItemRarityNameKnife: /* csgo_english.txt */"Knife",
  ItemRarityNameMachinegun: /* csgo_english.txt */"Machinegun",
  ItemRarityNameMusicKit: /* csgo_english.txt */"Music Kit",
  ItemRarityNamePatch: /* csgo_english.txt */"Patch",
  ItemRarityNamePistol: /* csgo_english.txt */"Pistol",
  ItemRarityNameRifle: /* csgo_english.txt */"Rifle",
  ItemRarityNameSMG: /* csgo_english.txt */"SMG",
  ItemRarityNameShotgun: /* csgo_english.txt */"Shotgun",
  ItemRarityNameSniperRifle: /* csgo_english.txt */"Sniper Rifle",
  ItemRarityNameSticker: /* csgo_english.txt */"Sticker",
  ItemRarityNameTool: /* csgo_english.txt */"Tool",
  ItemRarityRare: /* csgo_english.txt */"High Grade",
  ItemRarityUncommon: /* csgo_english.txt */"Medium Grade",
  ItemSwapStatTrakAccept: /* csgo_english.txt */"ACCEPT",
  ItemSwapStatTrakClose: /* csgo_english.txt */"Close",
  ItemSwapStatTrakDesc: /* csgo_english.txt */"This item swaps StatTrak™ values between two of the same item type.",
  ItemSwapStatTrakUse: /* csgo_english.txt */"StatTrak™ Swap Tool",
  ItemSwapStatTrakWarn: /* csgo_english.txt */"This StatTrak™ Swap Tool can only be used once",
  ItemWeaponRarityAncient: /* csgo_english.txt */"Covert",
  ItemWeaponRarityCommon: /* csgo_english.txt */"Consumer Grade",
  ItemWeaponRarityDefault: /* csgo_english.txt */"Stock",
  ItemWeaponRarityImmortal: /* csgo_english.txt */"Contraband",
  ItemWeaponRarityLegendary: /* csgo_english.txt */"Classified",
  ItemWeaponRarityMythical: /* csgo_english.txt */"Restricted",
  ItemWeaponRarityRare: /* csgo_english.txt */"Mil-Spec Grade",
  ItemWeaponRarityUncommon: /* csgo_english.txt */"Industrial Grade",
  ItemWearBS: /* csgo_english.txt */"Battle-Scarred",
  ItemWearFN: /* csgo_english.txt */"Factory New",
  ItemWearFT: /* csgo_english.txt */"Field-Tested",
  ItemWearMW: /* csgo_english.txt */"Minimal Wear",
  ItemWearWW: /* csgo_english.txt */"Well-Worn",
  JavaScriptRequired: "Please turn on JavaScript and refresh the page.",
  Language$brazilian: "Português do Brasil",
  Language$bulgarian: "Български",
  Language$czech: "Čeština",
  Language$danish: "Dansk",
  Language$dutch: "Nederlands",
  Language$english: "English",
  Language$finnish: "Suomi",
  Language$french: "Français",
  Language$german: "Deutsch",
  Language$greek: "Ελληνικά",
  Language$hungarian: "Magyar",
  Language$indonesian: "Bahasa Indonesia",
  Language$italian: "Italiano",
  Language$japanese: "日本語",
  Language$koreana: "한국어",
  Language$latam: "Español (Latinoamérica)",
  Language$norwegian: "Norsk",
  Language$polish: "Polski",
  Language$portuguese: "Português",
  Language$romanian: "Română",
  Language$russian: "Русский",
  Language$schinese: "简体中文",
  Language$spanish: "Español",
  Language$swedish: "Svenska",
  Language$tchinese: "繁體中文",
  Language$thai: "ไทย",
  Language$turkish: "Türkçe",
  Language$ukrainian: "Українська",
  Language$vietnamese: "Tiếng Việt",
  PatchPickerHeader: "Pick a patch...",
  PatchPickerSearchPlaceholder: "Search patch...",
  RemovePatchRemove: /* csgo_english.txt */"Remove Patch",
  RemovePatchRemoveDesc: /* csgo_english.txt */"Please confirm that you would like to remove this patch from your agent. The removed patch will be destroyed.",
  RemovePatchUse: /* csgo_english.txt */"Remove Patch",
  RemovePatchWarn: /* csgo_english.txt */"Remove a patch from",
  RenameCancel: /* csgo_english.txt */"Cancel",
  RenameEnterName: /* csgo_english.txt */"Enter a new name for:",
  RenameRename: /* csgo_english.txt */"Rename",
  RenameStorageUnitClose: /* csgo_english.txt */"Close",
  RenameStorageUnitEnterName: /* csgo_english.txt */"Enter a new name for:",
  RenameStorageUnitFirstNameWarn: /* csgo_english.txt */"Enter a descriptive label for your personal Storage Unit and start using it for storing items.",
  RenameStorageUnitNewNameWarn: /* csgo_english.txt */"Enter a new descriptive label for this Storage Unit.",
  RenameStorageUnitRename: /* csgo_english.txt */"Personalize",
  RenameStorageUnitUse: /* csgo_english.txt */"Personalize Your Storage Unit",
  RenameUse: /* csgo_english.txt */"Use Name Tag",
  RenameWarn: /* csgo_english.txt */"A Name Tag can only be used once",
  ScrapeStickerCancel: /* csgo_english.txt */"Cancel",
  ScrapeStickerClose: /* csgo_english.txt */"Close",
  ScrapeStickerRemove: /* csgo_english.txt */"Remove Sticker",
  ScrapeStickerRemoveDesc: /* csgo_english.txt */"Scraping this sticker further will remove it from the item and it will be destroyed.",
  ScrapeStickerUse: /* csgo_english.txt */"Scrape Sticker",
  ScrapeStickerWarn: /* csgo_english.txt */"Scrape a sticker from",
  SettingsBackground: "Background",
  SettingsBackgroundRandom: "Random",
  SettingsConfirmRemoveAllItems: "Are you sure you want to remove all items from your inventory?\nTHIS ACTION CANNOT BE UNDONE.",
  SettingsHeader: "Settings",
  SettingsHideFilters: "Hide filters",
  SettingsHideFreeItems: "Hide default items",
  SettingsLanguage: "Language",
  SettingsRemoveAllItems: "Reset my inventory",
  SettingsSave: "Save",
  SettingsStatsForNerds: "Stats for nerds",
  StickerPickerFilterPlaceholder: "Filter by category...",
  StickerPickerHeader: "Pick a sticker...",
  StickerPickerNA: "N/A",
  StickerPickerRemove: /* csgo_english.txt */"Remove",
  StickerPickerSearchPlaceholder: "Search sticker...",
  SyncErrorContinue: "Try again",
  SyncErrorDesc: "An error occurred while syncing your changes.",
  SyncErrorTitle: "Sync Error",
  SyncWarnText: "You are not authenticated, your changes will not by synchronized."
};
