/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const finnish = {
  ...english,
  ApplyPatchUse: /* csgo_finnish.txt */"Käytä kangasmerkki",
  ApplyPatchWarn: /* csgo_finnish.txt */"Kangasmerkki voidaan käyttää vain kerran",
  ApplyStickerCancel: /* csgo_finnish.txt */"Peruuta",
  ApplyStickerUse: /* csgo_finnish.txt */"Käytä tarra",
  ApplyStickerUseOn: /* csgo_finnish.txt */"Käytä:",
  ApplyStickerWarn: /* csgo_finnish.txt */"Tarraa voidaan käyttää vain kerran",
  CaseAdd: /* csgo_finnish.txt */"Lisää",
  CaseClose: /* csgo_finnish.txt */"Sulje",
  CaseContainsOne: /* csgo_finnish.txt */"Sisältää yhden seuraavista:",
  CaseNeed: /* csgo_finnish.txt */"Toimintoon vaaditaan esinettä:",
  CaseOnceWarn: /* csgo_finnish.txt */"Tämä säiliö voidaan avata vain kerran",
  CaseRareItem: /* csgo_finnish.txt */"★ Harvinainen erikoisesine ★",
  CaseUnlock: /* csgo_finnish.txt */"Avaa",
  CaseUnlockContainer: /* csgo_finnish.txt */"Avaa säiliö",
  CaseUse: /* csgo_finnish.txt */"Käytä esinettä",
  CategoryAgent: /* csgo_finnish.txt */"agentti",
  CategoryCase: /* csgo_finnish.txt */"säiliö",
  CategoryCollectible: /* csgo_finnish.txt */"keräilyesine",
  CategoryEquipment: /* csgo_finnish.txt */"varuste",
  CategoryGlove: /* csgo_finnish.txt */"hanskapari",
  CategoryGraffiti: /* csgo_finnish.txt */"graffiti",
  CategoryHeavy: /* csgo_finnish.txt */"Raskaat",
  CategoryKey: /* csgo_finnish.txt */"avain",
  CategoryKnife: /* csgo_finnish.txt */"veitsi",
  CategoryMusicKit: /* csgo_finnish.txt */"Musiikkipakkaus",
  CategoryPatch: /* csgo_finnish.txt */"Kangasmerkki",
  CategoryPistol: /* csgo_finnish.txt */"pistooli",
  CategoryRifle: /* csgo_finnish.txt */"kivääri",
  CategorySMG: /* csgo_finnish.txt */"konepistooli",
  CategorySticker: /* csgo_finnish.txt */"Tarra",
  CategoryTool: /* csgo_finnish.txt */"työkalu",
  EditorCancel: /* csgo_finnish.txt */"Peruuta",
  EditorNametag: /* csgo_finnish.txt */"Nimitunniste",
  EditorPatches: /* csgo_finnish.txt */"Kangasmerkit",
  EditorQuantity: /* csgo_finnish.txt */"Määrä",
  EditorRandom: /* csgo_finnish.txt */"Satunnainen",
  EditorReset: /* csgo_finnish.txt */"Nollaa",
  EditorSave: /* csgo_finnish.txt */"Tallenna",
  EditorSeed: /* csgo_finnish.txt */"Kuvio",
  EditorStatTrak: /* csgo_finnish.txt */"StatTrak™",
  EditorStickers: /* csgo_finnish.txt */"Tarrat",
  EditorWear: /* csgo_finnish.txt */"Kuluminen",
  InspectClose: /* csgo_finnish.txt */"Sulje",
  InventoryApplyPatch: /* csgo_finnish.txt */"Käytä kangasmerkki",
  InventoryApplySticker: /* csgo_finnish.txt */"Käytä tarra",
  InventoryFilterAgents: /* csgo_finnish.txt */"Agentit",
  InventoryFilterAll: /* csgo_finnish.txt */"Kaikki",
  InventoryFilterAllEquipment: /* csgo_finnish.txt */"Kaikki varusteet",
  InventoryFilterAllGraphicArt: /* csgo_finnish.txt */"Kaikki grafiikka",
  InventoryFilterAlphabetical: /* csgo_finnish.txt */"A-Ö",
  InventoryFilterCollection: /* csgo_finnish.txt */"Kokoelma",
  InventoryFilterContainers: /* csgo_finnish.txt */"SÄILIÖT",
  InventoryFilterDisplay: /* csgo_finnish.txt */"ESITTELY",
  InventoryFilterEquipment: /* csgo_finnish.txt */"VARUSTEET",
  InventoryFilterEquipped: /* csgo_finnish.txt */"Käytössä",
  InventoryFilterEverything: /* csgo_finnish.txt */"KAIKKI",
  InventoryFilterGloves: /* csgo_finnish.txt */"Hanskat",
  InventoryFilterGraffiti: /* csgo_finnish.txt */"Graffiti",
  InventoryFilterGraffitiBoxes: /* csgo_finnish.txt */"Graffitilaatikot",
  InventoryFilterGraphicArt: /* csgo_finnish.txt */"GRAFIIKKA",
  InventoryFilterMedals: /* csgo_finnish.txt */"Mitalit",
  InventoryFilterMelee: /* csgo_finnish.txt */"Lähitaisteluase",
  InventoryFilterMidTier: /* csgo_finnish.txt */"Keskitaso",
  InventoryFilterMisc: /* csgo_finnish.txt */"Muu",
  InventoryFilterMusicKits: /* csgo_finnish.txt */"Musiikkipakkaukset",
  InventoryFilterNewest: /* csgo_finnish.txt */"Uusin",
  InventoryFilterPatches: /* csgo_finnish.txt */"Kangasmerkit",
  InventoryFilterPistols: /* csgo_finnish.txt */"Pistoolit",
  InventoryFilterQuality: /* csgo_finnish.txt */"Harvinaisin",
  InventoryFilterRifles: /* csgo_finnish.txt */"Kiväärit",
  InventoryFilterSearch: /* csgo_finnish.txt */"Kirjoita haku tähän",
  InventoryFilterSouvenirCases: /* csgo_finnish.txt */"Tuliaissalkut",
  InventoryFilterStickerCapsules: /* csgo_finnish.txt */"Tarrakapselit",
  InventoryFilterStickers: /* csgo_finnish.txt */"Tarrat",
  InventoryFilterTools: /* csgo_finnish.txt */"Työkalut",
  InventoryFilterType: /* csgo_finnish.txt */"Tyyppi",
  InventoryFilterWeaponCases: /* csgo_finnish.txt */"Aselaatikot",
  InventoryItemContainsOne: /* csgo_finnish.txt */"Sisältää yhden seuraavista:",
  InventoryItemDelete: /* csgo_finnish.txt */"Poista",
  InventoryItemEdit: /* csgo_finnish.txt */"Muokkaa",
  InventoryItemEquip: /* csgo_finnish.txt */"Ota käyttöön",
  InventoryItemExterior: /* csgo_finnish.txt */"Pinta:",
  InventoryItemInspect: /* csgo_finnish.txt */"Tarkasta",
  InventoryItemInspectFinishCatalog: /* csgo_finnish.txt */"Viimeistelyvalikoima",
  InventoryItemInspectInGame: /* csgo_finnish.txt */"Tutki pelissä...",
  InventoryItemInspectPatternTemplate: /* csgo_finnish.txt */"Kuviopohja",
  InventoryItemInspectWearRating: /* csgo_finnish.txt */"Kuluma",
  InventoryItemMVPStatTrakCount: /* csgo_finnish.txt */"StatTrak™ Viralliset kilpailutilan Tähtipelaaja-merkinnät:",
  InventoryItemNew: /* csgo_finnish.txt */"Uusi!",
  InventoryItemRareItem: /* csgo_finnish.txt */"tai erittäin harvinaisen erikoisesineen!",
  InventoryItemRarity: /* csgo_finnish.txt */"Harvinaisuus:",
  InventoryItemRemovePatch: /* csgo_finnish.txt */"Poista kangasmerkki",
  InventoryItemRename: /* csgo_finnish.txt */"Nimeä uudelleen",
  InventoryItemRenameStorageUnit: /* csgo_finnish.txt */"Vaihda nimike",
  InventoryItemScrapeSticker: /* csgo_finnish.txt */"Raaputa tarra",
  InventoryItemStatTrak: /* csgo_finnish.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_finnish.txt */"StatTrak™ varmistetut tapot:",
  InventoryItemStatTrakDesc: /* csgo_finnish.txt */"Tämä esine sisältää StatTrak™-teknologiaa, joka pitää kirjaa tietyistä tilastoista omistajansa käyttämänä.",
  InventoryItemStorageUnitDeposit: /* csgo_finnish.txt */"Talleta esineet",
  InventoryItemStorageUnitEmptyBody: /* csgo_finnish.txt */"Voit säilöä tähän varastolaatikkoon jopa {1} ylimääräistä esinettä, jotka eivät mahtuisi varusteluetteloosi. Tällä hetkellä valitsemasi varastolaatikko on tyhjä. Voit siirtää esineitä laatiikkoon tai pois sieltä milloin vain. Voit käyttää sitä myös tavaroiden järjestelyyn.",
  InventoryItemStorageUnitEmptyClose: /* csgo_finnish.txt */"OK",
  InventoryItemStorageUnitEmptyTitle: /* csgo_finnish.txt */"Tyhjä varastolaatikko",
  InventoryItemStorageUnitInspect: /* csgo_finnish.txt */"Tarkasta",
  InventoryItemStorageUnitRetrieve: /* csgo_finnish.txt */"Hae esineet",
  InventoryItemSwapStatTrak: /* csgo_finnish.txt */"Avaa StatTrak™-vaihtotyökalu",
  InventoryItemTeam: /* csgo_finnish.txt */"Joukkue:",
  InventoryItemTeamAny: /* csgo_finnish.txt */"Kaikki",
  InventoryItemTeamCT: /* csgo_finnish.txt */"Erikoissotilas",
  InventoryItemTeamT: /* csgo_finnish.txt */"Terroristi",
  InventoryItemUnequip: /* csgo_finnish.txt */"Poista käytöstä",
  InventoryItemUnlockContainer: /* csgo_finnish.txt */"Avaa säiliö",
  InventoryItemUseStorageUnit: /* csgo_finnish.txt */"Aloita varastolaatikon käyttö",
  InventorySelectAnItem: /* csgo_finnish.txt */"Valitse yhteiskäyttöön esine:",
  InventorySelectInspectContents: /* csgo_finnish.txt */"Tarkastetaan sisältö kohteelle:",
  InventorySelectItemToDeposit: /* csgo_finnish.txt */"Valitse siirrettävät esineet",
  InventorySelectItemToRetrieve: /* csgo_finnish.txt */"Valitse siirrettävät esineet",
  ItemRarityAncient: /* csgo_finnish.txt */"Merkillinen",
  ItemRarityCommon: /* csgo_finnish.txt */"Perustason",
  ItemRarityDefault: /* csgo_finnish.txt */"Tavallinen",
  ItemRarityImmortal: /* csgo_finnish.txt */"Salakuljetettu",
  ItemRarityLegendary: /* csgo_finnish.txt */"Eksoottinen",
  ItemRarityMythical: /* csgo_finnish.txt */"Huomattava",
  ItemRarityNameAgent: /* csgo_finnish.txt */"agentti",
  ItemRarityNameCollectible: /* csgo_finnish.txt */"keräilyesine",
  ItemRarityNameContainer: /* csgo_finnish.txt */"säiliö",
  ItemRarityNameContract: /* csgo_finnish.txt */"Sopimus",
  ItemRarityNameEquipment: /* csgo_finnish.txt */"varuste",
  ItemRarityNameGloves: /* csgo_finnish.txt */"hanskapari",
  ItemRarityNameGraffiti: /* csgo_finnish.txt */"graffiti",
  ItemRarityNameKey: /* csgo_finnish.txt */"avain",
  ItemRarityNameKnife: /* csgo_finnish.txt */"veitsi",
  ItemRarityNameMachinegun: /* csgo_finnish.txt */"konekivääri",
  ItemRarityNameMusicKit: /* csgo_finnish.txt */"Musiikkipakkaus",
  ItemRarityNamePatch: /* csgo_finnish.txt */"Kangasmerkki",
  ItemRarityNamePistol: /* csgo_finnish.txt */"pistooli",
  ItemRarityNameRifle: /* csgo_finnish.txt */"kivääri",
  ItemRarityNameSMG: /* csgo_finnish.txt */"konepistooli",
  ItemRarityNameShotgun: /* csgo_finnish.txt */"haulikko",
  ItemRarityNameSniperRifle: /* csgo_finnish.txt */"tarkkuuskivääri",
  ItemRarityNameSticker: /* csgo_finnish.txt */"Tarra",
  ItemRarityNameTool: /* csgo_finnish.txt */"työkalu",
  ItemRarityRare: /* csgo_finnish.txt */"Korkean tason",
  ItemRarityUncommon: /* csgo_finnish.txt */"Keskitason",
  ItemSwapStatTrakAccept: /* csgo_finnish.txt */"HYVÄKSY",
  ItemSwapStatTrakClose: /* csgo_finnish.txt */"Sulje",
  ItemSwapStatTrakDesc: /* csgo_finnish.txt */"Tämä esine vaihtaa kahden samanlaisen aseen StatTrak™-arvot keskenään.",
  ItemSwapStatTrakUse: /* csgo_finnish.txt */"StatTrak™-vaihtotyökalu",
  ItemSwapStatTrakWarn: /* csgo_finnish.txt */"Tätä StatTrak™-vaihtotyökalua voi käyttää vain kerran",
  ItemWeaponRarityAncient: /* csgo_finnish.txt */"Salainen",
  ItemWeaponRarityCommon: /* csgo_finnish.txt */"Kuluttajatason",
  ItemWeaponRarityDefault: /* csgo_finnish.txt */"Tavallinen",
  ItemWeaponRarityImmortal: /* csgo_finnish.txt */"Salakuljetettu",
  ItemWeaponRarityLegendary: /* csgo_finnish.txt */"Luottamuksellinen",
  ItemWeaponRarityMythical: /* csgo_finnish.txt */"Rajoitettu",
  ItemWeaponRarityRare: /* csgo_finnish.txt */"Armeijatason",
  ItemWeaponRarityUncommon: /* csgo_finnish.txt */"Teollistason",
  ItemWearBS: /* csgo_finnish.txt */"Reissussa rähjääntynyt",
  ItemWearFN: /* csgo_finnish.txt */"Suoraan tehtaalta",
  ItemWearFT: /* csgo_finnish.txt */"Käytössä kokeiltu",
  ItemWearMW: /* csgo_finnish.txt */"Vähän käytetty",
  ItemWearWW: /* csgo_finnish.txt */"Aikansa elänyt",
  RemovePatchRemove: /* csgo_finnish.txt */"Poista kangasmerkki",
  RemovePatchRemoveDesc: /* csgo_finnish.txt */"Vahvista, että haluat poistaa kangasmerkin agentiltasi. Poistettu merkki tuhotaan.",
  RemovePatchUse: /* csgo_finnish.txt */"Poista kangasmerkki",
  RemovePatchWarn: /* csgo_finnish.txt */"Poista kangasmerkki kohteesta",
  RenameCancel: /* csgo_finnish.txt */"Peruuta",
  RenameEnterName: /* csgo_finnish.txt */"Syötä esineelle  uusi nimi",
  RenameRename: /* csgo_finnish.txt */"Nimeä uudelleen",
  RenameStorageUnitClose: /* csgo_finnish.txt */"Sulje",
  RenameStorageUnitEnterName: /* csgo_finnish.txt */"Syötä esineelle  uusi nimi",
  RenameStorageUnitFirstNameWarn: /* csgo_finnish.txt */"Lisää kuvaus omaan varastolaatikkoosi ja ala käyttää sitä esineiden tallentamiseen.",
  RenameStorageUnitNewNameWarn: /* csgo_finnish.txt */"Kirjoita uusi nimike tälle varastolaatikolle",
  RenameStorageUnitRename: /* csgo_finnish.txt */"Personoi",
  RenameStorageUnitUse: /* csgo_finnish.txt */"Personalisoi varastolaatikkoasi",
  RenameUse: /* csgo_finnish.txt */"Käytä nimitunniste",
  RenameWarn: /* csgo_finnish.txt */"Nimitunnistetta voi käyttää vain kerran",
  ScrapeStickerCancel: /* csgo_finnish.txt */"Peruuta",
  ScrapeStickerClose: /* csgo_finnish.txt */"Sulje",
  ScrapeStickerRemove: /* csgo_finnish.txt */"Poista tarra",
  ScrapeStickerRemoveDesc: /* csgo_finnish.txt */"Seuraava raaputus poistaa tarran aseesta ja tuhoaa sen.",
  ScrapeStickerUse: /* csgo_finnish.txt */"Raaputa tarra",
  ScrapeStickerWarn: /* csgo_finnish.txt */"Raaputa tarraa aseessa",
  StickerPickerRemove: /* csgo_finnish.txt */"Poista"
};
