/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const french = {
  ...english,
  ApplyPatchUse: /* csgo_french.txt */"Appliquer l'écusson",
  ApplyPatchWarn: /* csgo_french.txt */"Un écusson ne peut être utilisé qu'une seule fois",
  ApplyStickerCancel: /* csgo_french.txt */"Annuler",
  ApplyStickerUse: /* csgo_french.txt */"Appliquer le sticker",
  ApplyStickerUseOn: /* csgo_french.txt */"Appliquer sur",
  ApplyStickerWarn: /* csgo_french.txt */"Un sticker ne peut être utilisé qu'une seule fois",
  CaseAdd: /* csgo_french.txt */"Ajouter",
  CaseClose: /* csgo_french.txt */"Fermer",
  CaseContainsOne: /* csgo_french.txt */"Contient l'un des objets suivants :",
  CaseNeed: /* csgo_french.txt */"Vous devez posséder un(e)",
  CaseOnceWarn: /* csgo_french.txt */"Ce conteneur ne peut être ouvert qu'une seule fois",
  CaseRareItem: /* csgo_french.txt */"★ Item spécial rare ★",
  CaseUnlock: /* csgo_french.txt */"Déverrouiller",
  CaseUnlockContainer: /* csgo_french.txt */"Ouvrir le conteneur",
  CaseUse: /* csgo_french.txt */"Utiliser",
  CategoryAgent: /* csgo_french.txt */"Agent",
  CategoryCase: /* csgo_french.txt */"Conteneur",
  CategoryCollectible: /* csgo_french.txt */"Collector",
  CategoryEquipment: /* csgo_french.txt */"Équipement",
  CategoryGlove: /* csgo_french.txt */"Gants",
  CategoryGraffiti: /* csgo_french.txt */"Graffiti",
  CategoryHeavy: /* csgo_french.txt */"Lourdes",
  CategoryKey: /* csgo_french.txt */"Clé",
  CategoryKeychain: /* csgo_french.txt */"Porte-bonheur",
  CategoryKnife: /* csgo_french.txt */"Couteau",
  CategoryMusicKit: /* csgo_french.txt */"Kit de musiques",
  CategoryPatch: /* csgo_french.txt */"Écusson",
  CategoryPistol: /* csgo_french.txt */"Pistolet",
  CategoryRifle: /* csgo_french.txt */"Fusil",
  CategorySMG: /* csgo_french.txt */"PM",
  CategorySticker: /* csgo_french.txt */"Sticker",
  CategoryTool: /* csgo_french.txt */"Outil",
  EditorCancel: /* csgo_french.txt */"Annuler",
  EditorNametag: /* csgo_french.txt */"Étiquette",
  EditorPatches: /* csgo_french.txt */"Écussons",
  EditorQuantity: /* csgo_french.txt */"Quantité",
  EditorRandom: /* csgo_french.txt */"Aléatoire",
  EditorReset: /* csgo_french.txt */"Réinitialiser",
  EditorSave: /* csgo_french.txt */"Enregistrer",
  EditorSeed: /* csgo_french.txt */"Motif",
  EditorStatTrak: /* csgo_french.txt */"StatTrak™",
  EditorStickers: /* csgo_french.txt */"Stickers",
  EditorWear: /* csgo_french.txt */"Usure",
  GenericCancel: /* csgo_french.txt */"Annuler",
  InspectClose: /* csgo_french.txt */"Fermer",
  InventoryApplyPatch: /* csgo_french.txt */"Appliquer l'écusson",
  InventoryApplySticker: /* csgo_french.txt */"Appliquer le sticker",
  InventoryFilterAgents: /* csgo_french.txt */"Éléments",
  InventoryFilterAll: /* csgo_french.txt */"Tous",
  InventoryFilterAllEquipment: /* csgo_french.txt */"Tout l'équipement",
  InventoryFilterAllGraphicArt: /* csgo_french.txt */"Tous les items d'art graphique",
  InventoryFilterAlphabetical: /* csgo_french.txt */"Ordre alphabétique",
  InventoryFilterCharms: /* csgo_french.txt */"Porte-bonheurs",
  InventoryFilterCollection: /* csgo_french.txt */"Collection",
  InventoryFilterContainers: /* csgo_french.txt */"CONTENEURS",
  InventoryFilterDisplay: /* csgo_french.txt */"PROFIL",
  InventoryFilterEquipment: /* csgo_french.txt */"ÉQUIPEMENT",
  InventoryFilterEquipped: /* csgo_french.txt */"Équipé",
  InventoryFilterEverything: /* csgo_french.txt */"TOUT",
  InventoryFilterGloves: /* csgo_french.txt */"Gants",
  InventoryFilterGraffiti: /* csgo_french.txt */"Graffitis",
  InventoryFilterGraffitiBoxes: /* csgo_french.txt */"Boîtes de graffitis",
  InventoryFilterGraphicArt: /* csgo_french.txt */"ART GRAPHIQUE",
  InventoryFilterMedals: /* csgo_french.txt */"Médailles",
  InventoryFilterMelee: /* csgo_french.txt */"Corps à corps",
  InventoryFilterMidTier: /* csgo_french.txt */"Intermédiaires",
  InventoryFilterMisc: /* csgo_french.txt */"Divers",
  InventoryFilterMusicKits: /* csgo_french.txt */"Kits de musiques",
  InventoryFilterNewest: /* csgo_french.txt */"Plus récent",
  InventoryFilterPatches: /* csgo_french.txt */"Écussons",
  InventoryFilterPistols: /* csgo_french.txt */"Pistolets",
  InventoryFilterQuality: /* csgo_french.txt */"Qualité",
  InventoryFilterRifles: /* csgo_french.txt */"Fusils",
  InventoryFilterSearch: /* csgo_french.txt */"Rechercher",
  InventoryFilterSouvenirCases: /* csgo_french.txt */"Caisses souvenir",
  InventoryFilterStickerCapsules: /* csgo_french.txt */"Capsules à stickers",
  InventoryFilterStickers: /* csgo_french.txt */"Stickers",
  InventoryFilterTools: /* csgo_french.txt */"Outils",
  InventoryFilterType: /* csgo_french.txt */"Type",
  InventoryFilterWeaponCases: /* csgo_french.txt */"Caisses d'arme",
  InventoryItemContainsOne: /* csgo_french.txt */"Contient l'un des objets suivants :",
  InventoryItemDelete: /* csgo_french.txt */"Supprimer",
  InventoryItemDeleteConfirm: /* csgo_french.txt */"Supprimer cet item",
  InventoryItemDeleteConfirmDesc: /* csgo_french.txt */"Voulez-vous vraiment supprimer cet item ?",
  InventoryItemEdit: /* csgo_french.txt */"Modifier",
  InventoryItemEquip: /* csgo_french.txt */"Équiper",
  InventoryItemExterior: /* csgo_french.txt */"Apparence :",
  InventoryItemInspect: /* csgo_french.txt */"Examiner",
  InventoryItemInspectFinishCatalog: /* csgo_french.txt */"ID de la finition ",
  InventoryItemInspectInGame: /* csgo_french.txt */"Examiner en jeu…",
  InventoryItemInspectPatternTemplate: /* csgo_french.txt */"Modèle des motifs ",
  InventoryItemInspectWearRating: /* csgo_french.txt */"Taux d'usure ",
  InventoryItemMVPStatTrakCount: /* csgo_french.txt */"StatTrak™ des MJs en compétitif:",
  InventoryItemNew: /* csgo_french.txt */"Nouveau !",
  InventoryItemRareItem: /* csgo_french.txt */"ou un item spécial extrêmement rare !",
  InventoryItemRarity: /* csgo_french.txt */"Rareté :",
  InventoryItemRemovePatch: /* csgo_french.txt */"Retirer l'écusson",
  InventoryItemRename: /* csgo_french.txt */"Renommer",
  InventoryItemRenameStorageUnit: /* csgo_french.txt */"Changer l'étiquette",
  InventoryItemScrapeSticker: /* csgo_french.txt */"Gratter le sticker",
  InventoryItemStatTrak: /* csgo_french.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_french.txt */"Victimes confirmées StatTrak™:",
  InventoryItemStatTrakDesc: /* csgo_french.txt */"Cet item utilise la technologie StatTrak™ : certaines statistiques seront enregistrées lorsqu'il sera équipé.",
  InventoryItemStorageUnitDeposit: /* csgo_french.txt */"Déposer des items",
  InventoryItemStorageUnitEmptyBody: /* csgo_french.txt */"L'unité de stockage vous permet de stocker jusqu'à {1} items en surplus par rapport à la capacité de votre inventaire. L'unité de stockage sélectionnée est actuellement vide. À tout moment, vous pouvez déplacer des items de votre inventaire vers l'unité de stockage et inversement, ou vous pouvez simplement l'utiliser pour organiser vos collections d'items.",
  InventoryItemStorageUnitEmptyClose: /* csgo_french.txt */"OK",
  InventoryItemStorageUnitEmptyTitle: /* csgo_french.txt */"Unité de stockage vide",
  InventoryItemStorageUnitInspect: /* csgo_french.txt */"Examiner",
  InventoryItemStorageUnitRetrieve: /* csgo_french.txt */"Récupérer des items",
  InventoryItemSwapStatTrak: /* csgo_french.txt */"Utiliser l'outil de permutation StatTrak™",
  InventoryItemTeam: /* csgo_french.txt */"Équipe :",
  InventoryItemTeamAny: /* csgo_french.txt */"Les deux",
  InventoryItemTeamCT: /* csgo_french.txt */"Antiterroristes",
  InventoryItemTeamT: /* csgo_french.txt */"Terroristes",
  InventoryItemUnequip: /* csgo_french.txt */"Déséquiper",
  InventoryItemUnlockContainer: /* csgo_french.txt */"Ouvrir le conteneur",
  InventoryItemUseStorageUnit: /* csgo_french.txt */"Commencer à utiliser cette unité",
  InventorySelectAnItem: /* csgo_french.txt */"Sélectionnez un item avec lequel l'utiliser :",
  InventorySelectInspectContents: /* csgo_french.txt */"Examen du contenu de",
  InventorySelectItemToDeposit: /* csgo_french.txt */"Sélectionnez les objets à déplacer",
  InventorySelectItemToRetrieve: /* csgo_french.txt */"Sélectionner les objets à récupérer",
  ItemRarityAncient: /* csgo_french.txt */"Extraordinaire",
  ItemRarityCommon: /* csgo_french.txt */"Qualité de base",
  ItemRarityDefault: /* csgo_french.txt */"Défaut",
  ItemRarityImmortal: /* csgo_french.txt */"Contrebande",
  ItemRarityLegendary: /* csgo_french.txt */"Exotique",
  ItemRarityMythical: /* csgo_french.txt */"Remarquable",
  ItemRarityNameAgent: /* csgo_french.txt */"Agent",
  ItemRarityNameCharm: /* csgo_french.txt */"Porte-bonheur",
  ItemRarityNameCollectible: /* csgo_french.txt */"Collector",
  ItemRarityNameContainer: /* csgo_french.txt */"Conteneur",
  ItemRarityNameContract: /* csgo_french.txt */"Contrat",
  ItemRarityNameEquipment: /* csgo_french.txt */"Équipement",
  ItemRarityNameGloves: /* csgo_french.txt */"Gants",
  ItemRarityNameGraffiti: /* csgo_french.txt */"Graffiti",
  ItemRarityNameKey: /* csgo_french.txt */"Clé",
  ItemRarityNameKnife: /* csgo_french.txt */"Couteau",
  ItemRarityNameMachinegun: /* csgo_french.txt */"Mitrailleuse",
  ItemRarityNameMusicKit: /* csgo_french.txt */"Kit de musiques",
  ItemRarityNamePatch: /* csgo_french.txt */"Écusson",
  ItemRarityNamePistol: /* csgo_french.txt */"Pistolet",
  ItemRarityNameRifle: /* csgo_french.txt */"Fusil",
  ItemRarityNameSMG: /* csgo_french.txt */"PM",
  ItemRarityNameShotgun: /* csgo_french.txt */"Fusil à pompe",
  ItemRarityNameSniperRifle: /* csgo_french.txt */"Fusil de précision",
  ItemRarityNameSticker: /* csgo_french.txt */"Sticker",
  ItemRarityNameTool: /* csgo_french.txt */"Outil",
  ItemRarityRare: /* csgo_french.txt */"Qualité supérieure",
  ItemRarityUncommon: /* csgo_french.txt */"Qualité moyenne",
  ItemSwapStatTrakAccept: /* csgo_french.txt */"ACCEPTER",
  ItemSwapStatTrakClose: /* csgo_french.txt */"Fermer",
  ItemSwapStatTrakDesc: /* csgo_french.txt */"Cet item permet de permuter les valeurs StatTrak™ entre deux types d'items identiques.",
  ItemSwapStatTrakUse: /* csgo_french.txt */"Outil de permutation StatTrak™",
  ItemSwapStatTrakWarn: /* csgo_french.txt */"Cet outil de permutation StatTrak™ ne peut être utilisé qu'une seule fois",
  ItemWeaponRarityAncient: /* csgo_french.txt */"Secrète",
  ItemWeaponRarityCommon: /* csgo_french.txt */"Artisanale",
  ItemWeaponRarityDefault: /* csgo_french.txt */"Ordinaire",
  ItemWeaponRarityImmortal: /* csgo_french.txt */"Contrebande",
  ItemWeaponRarityLegendary: /* csgo_french.txt */"Classifiée",
  ItemWeaponRarityMythical: /* csgo_french.txt */"Limitée",
  ItemWeaponRarityRare: /* csgo_french.txt */"Militaire",
  ItemWeaponRarityUncommon: /* csgo_french.txt */"Industrielle",
  ItemWearBS: /* csgo_french.txt */"Marquée par les combats",
  ItemWearFN: /* csgo_french.txt */"Neuve",
  ItemWearFT: /* csgo_french.txt */"Testée sur le terrain",
  ItemWearMW: /* csgo_french.txt */"Très peu usée",
  ItemWearWW: /* csgo_french.txt */"Usée",
  RemovePatchRemove: /* csgo_french.txt */"Retirer l'écusson",
  RemovePatchRemoveDesc: /* csgo_french.txt */"Veuillez confirmer que vous voulez retirer cet écusson de votre agent. L'écusson retiré sera détruit.",
  RemovePatchUse: /* csgo_french.txt */"Retirer l'écusson",
  RemovePatchWarn: /* csgo_french.txt */"Retirer un écusson appliqué à",
  RenameCancel: /* csgo_french.txt */"Annuler",
  RenameEnterName: /* csgo_french.txt */"Saisissez un nouveau nom pour :",
  RenameRename: /* csgo_french.txt */"Renommer",
  RenameStorageUnitClose: /* csgo_french.txt */"Fermer",
  RenameStorageUnitEnterName: /* csgo_french.txt */"Saisissez un nouveau nom pour :",
  RenameStorageUnitFirstNameWarn: /* csgo_french.txt */"Saisissez une description pour votre unité de stockage personnelle et commencez à y stocker vos objets.",
  RenameStorageUnitNewNameWarn: /* csgo_french.txt */"Saisissez une nouvelle description pour cette unité de stockage.",
  RenameStorageUnitRename: /* csgo_french.txt */"Personnaliser",
  RenameStorageUnitUse: /* csgo_french.txt */"Personnalisez votre unité de stockage",
  RenameUse: /* csgo_french.txt */"Utiliser l'étiquette",
  RenameWarn: /* csgo_french.txt */"Une étiquette ne peut être utilisée qu'une seule fois",
  ScrapeStickerCancel: /* csgo_french.txt */"Annuler",
  ScrapeStickerClose: /* csgo_french.txt */"Fermer",
  ScrapeStickerRemove: /* csgo_french.txt */"Retirer le sticker",
  ScrapeStickerRemoveDesc: /* csgo_french.txt */"Gratter davantage ce sticker le supprimera de cet objet.",
  ScrapeStickerUse: /* csgo_french.txt */"Gratter le sticker",
  ScrapeStickerWarn: /* csgo_french.txt */"Gratter un sticker appliqué à",
  SettingsMasterVolume: /* csgo_french.txt */"Volume principal",
  StickerPickerRemove: /* csgo_french.txt */"Supprimer"
};
