/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const german = {
  ...english,
  ApplyPatchUse: /* csgo_german.txt */"Aufnäher anbringen",
  ApplyPatchWarn: /* csgo_german.txt */"Ein Aufnäher kann nur einmal verwendet werden",
  ApplyStickerCancel: /* csgo_german.txt */"Abbrechen",
  ApplyStickerUse: /* csgo_german.txt */"Aufkleber anbringen",
  ApplyStickerUseOn: /* csgo_german.txt */"An  anbringen",
  ApplyStickerWarn: /* csgo_german.txt */"Ein Aufkleber kann nur einmal verwendet werden",
  CaseAdd: /* csgo_german.txt */"Hinzufügen",
  CaseClose: /* csgo_german.txt */"Schließen",
  CaseContainsOne: /* csgo_german.txt */"Enthält einen der folgende Gegenstände:",
  CaseNeed: /* csgo_german.txt */"Sie benötigen:",
  CaseOnceWarn: /* csgo_german.txt */"Dieser Behälter kann nur einmal geöffnet werden",
  CaseRareItem: /* csgo_german.txt */"★ Seltener Spezialgegenstand ★",
  CaseUnlock: /* csgo_german.txt */"öffnen",
  CaseUnlockContainer: /* csgo_german.txt */"Behälter öffnen",
  CaseUse: /* csgo_german.txt */"benutzen",
  CategoryAgent: /* csgo_german.txt */"Agent",
  CategoryCase: /* csgo_german.txt */"Behälter",
  CategoryCollectible: /* csgo_german.txt */"Sammlerstück",
  CategoryEquipment: /* csgo_german.txt */"Ausrüstung",
  CategoryGlove: /* csgo_german.txt */"Handschuhe",
  CategoryGraffiti: /* csgo_german.txt */"Graffiti",
  CategoryHeavy: /* csgo_german.txt */"Schwer",
  CategoryKey: /* csgo_german.txt */"Schlüssel",
  CategoryKeychain: /* csgo_german.txt */"Anhänger",
  CategoryKnife: /* csgo_german.txt */"Messer",
  CategoryMusicKit: /* csgo_german.txt */"Musikkit",
  CategoryPatch: /* csgo_german.txt */"Aufnäher",
  CategoryPistol: /* csgo_german.txt */"Pistole",
  CategoryRifle: /* csgo_german.txt */"Gewehr",
  CategorySMG: /* csgo_german.txt */"MP",
  CategorySticker: /* csgo_german.txt */"Aufkleber",
  CategoryTool: /* csgo_german.txt */"Werkzeug",
  EditorCancel: /* csgo_german.txt */"Abbrechen",
  EditorConfirmPick: /* csgo_german.txt */"Tipp bestätigen",
  EditorNametag: /* csgo_german.txt */"Namensschild",
  EditorPatches: /* csgo_german.txt */"Aufnäher",
  EditorPick: /* csgo_german.txt */"Auswahl",
  EditorQuantity: /* csgo_german.txt */"Anzahl",
  EditorRandom: /* csgo_german.txt */"Zufällig",
  EditorReset: /* csgo_german.txt */"Zurücksetzen",
  EditorSave: /* csgo_german.txt */"Speichern",
  EditorSeed: /* csgo_german.txt */"Muster",
  EditorStatTrak: /* csgo_german.txt */"StatTrak™",
  EditorStickers: /* csgo_german.txt */"Aufkleber",
  EditorWear: /* csgo_german.txt */"Abnutzung",
  GenericCancel: /* csgo_german.txt */"Abbrechen",
  GenericNo: /* csgo_german.txt */"Nein",
  GenericYes: /* csgo_german.txt */"Ja",
  InspectClose: /* csgo_german.txt */"Schließen",
  InventoryApplyPatch: /* csgo_german.txt */"Aufnäher anbringen",
  InventoryApplySticker: /* csgo_german.txt */"Aufkleber anbringen",
  InventoryFilterAgents: /* csgo_german.txt */"Agenten",
  InventoryFilterAll: /* csgo_german.txt */"Alle",
  InventoryFilterAllEquipment: /* csgo_german.txt */"Komplette Ausrüstung",
  InventoryFilterAllGraphicArt: /* csgo_german.txt */"Alle Kunstgegenstände",
  InventoryFilterAlphabetical: /* csgo_german.txt */"Alphabetisch",
  InventoryFilterCharms: /* csgo_german.txt */"Anhänger",
  InventoryFilterCollection: /* csgo_german.txt */"Kollektion",
  InventoryFilterContainers: /* csgo_german.txt */"BEHÄLTER",
  InventoryFilterDisplay: /* csgo_german.txt */"ANZEIGE",
  InventoryFilterEquipment: /* csgo_german.txt */"AUSRÜSTUNG",
  InventoryFilterEquipped: /* csgo_german.txt */"Ausgerüstet",
  InventoryFilterEverything: /* csgo_german.txt */"ALLES",
  InventoryFilterGloves: /* csgo_german.txt */"Handschuhe",
  InventoryFilterGraffiti: /* csgo_german.txt */"Graffiti",
  InventoryFilterGraffitiBoxes: /* csgo_german.txt */"Graffitiboxen",
  InventoryFilterGraphicArt: /* csgo_german.txt */"GRAFIK",
  InventoryFilterMedals: /* csgo_german.txt */"Medaillen",
  InventoryFilterMelee: /* csgo_german.txt */"Nahkampf",
  InventoryFilterMidTier: /* csgo_german.txt */"MPs & Schrot",
  InventoryFilterMisc: /* csgo_german.txt */"Verschiedenes",
  InventoryFilterMusicKits: /* csgo_german.txt */"Musikkits",
  InventoryFilterNewest: /* csgo_german.txt */"Neueste",
  InventoryFilterPatches: /* csgo_german.txt */"Aufnäher",
  InventoryFilterPistols: /* csgo_german.txt */"Pistolen",
  InventoryFilterQuality: /* csgo_german.txt */"Qualität",
  InventoryFilterRifles: /* csgo_german.txt */"Gewehre",
  InventoryFilterSearch: /* csgo_german.txt */"Suchbegriff eingeben",
  InventoryFilterSouvenirCases: /* csgo_german.txt */"Souvenirkisten",
  InventoryFilterStickerCapsules: /* csgo_german.txt */"Aufkleberkapseln",
  InventoryFilterStickers: /* csgo_german.txt */"Aufkleber",
  InventoryFilterTools: /* csgo_german.txt */"Werkzeuge",
  InventoryFilterType: /* csgo_german.txt */"Typ",
  InventoryFilterWeaponCases: /* csgo_german.txt */"Waffenkisten",
  InventoryItemContainsOne: /* csgo_german.txt */"Enthält einen der folgende Gegenstände:",
  InventoryItemDelete: /* csgo_german.txt */"Löschen",
  InventoryItemDeleteConfirm: /* csgo_german.txt */"Gegenstand löschen",
  InventoryItemDeleteConfirmDesc: /* csgo_german.txt */"Möchten Sie diesen Gegenstand wirklich löschen?",
  InventoryItemEdit: /* csgo_german.txt */"Bearbeiten",
  InventoryItemEquip: /* csgo_german.txt */"Ausrüsten",
  InventoryItemExterior: /* csgo_german.txt */"Zustand:",
  InventoryItemInspect: /* csgo_german.txt */"Untersuchen",
  InventoryItemInspectFinishCatalog: /* csgo_german.txt */"Lackkatalog",
  InventoryItemInspectInGame: /* csgo_german.txt */"Im Spiel untersuchen …",
  InventoryItemInspectPatternTemplate: /* csgo_german.txt */"Mustervorlage",
  InventoryItemInspectWearRating: /* csgo_german.txt */"Abnutzungsgrad",
  InventoryItemMVPStatTrakCount: /* csgo_german.txt */"StatTrak™ Auszeichnungen als „Beste Spieler“ im offiziellen Wettkampf:",
  InventoryItemNew: /* csgo_german.txt */"Neu!",
  InventoryItemRareItem: /* csgo_german.txt */"oder einen außerordentlich seltenen Bonus-Gegenstand!",
  InventoryItemRarity: /* csgo_german.txt */"Seltenheit:",
  InventoryItemRemovePatch: /* csgo_german.txt */"Aufnäher entfernen",
  InventoryItemRename: /* csgo_german.txt */"umbenennen",
  InventoryItemRenameClearTooltip: /* csgo_german.txt */"Von vorne anfangen.",
  InventoryItemRenameInvalidTooltip: /* csgo_german.txt */"Bitte geben Sie einen gültigen Namen ein.",
  InventoryItemRenamePlaceholder: /* csgo_german.txt */"Neuer Name",
  InventoryItemRenameStorageUnit: /* csgo_german.txt */"Beschreibung ändern",
  InventoryItemScrapeSticker: /* csgo_german.txt */"Aufkleber abkratzen",
  InventoryItemStatTrak: /* csgo_german.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_german.txt */"StatTrak™-bestätigte Abschüsse:",
  InventoryItemStatTrakDesc: /* csgo_german.txt */"Dieser Gegenstand verfügt über StatTrak™-Technologie, der bestimmte Statistiken festhält, wenn er von ihrem Besitzer ausgerüstet wird.",
  InventoryItemStorageUnitDeposit: /* csgo_german.txt */"Gegenstände lagern",
  InventoryItemStorageUnitEmptyBody: /* csgo_german.txt */"Mit dieser Speichereinheit können Sie bis zu {1} Ihrer überschüssigen Gegenstände lagern, die sonst das Inventarlimit überschreiten würden. Die ausgewählte Speichereinheit ist derzeit leer. Sie können jederzeit Gegenstände aus Ihrem Inventar in diese Speichereinheit verschieben, sie wieder zurück in Ihren Inventar holen oder einfach Ihre Sammlungen organisieren.",
  InventoryItemStorageUnitEmptyClose: /* csgo_german.txt */"OK",
  InventoryItemStorageUnitEmptyTitle: /* csgo_german.txt */"Speichereinheit leer",
  InventoryItemStorageUnitInspect: /* csgo_german.txt */"Untersuchen",
  InventoryItemStorageUnitRetrieve: /* csgo_german.txt */"Gegenstände abrufen",
  InventoryItemSwapStatTrak: /* csgo_german.txt */"StatTrak™-Austauschwerkzeug öffnen",
  InventoryItemTeam: /* csgo_german.txt */"Team:",
  InventoryItemTeamAny: /* csgo_german.txt */"Beliebig",
  InventoryItemTeamCT: /* csgo_german.txt */"Antiterroreinheit",
  InventoryItemTeamT: /* csgo_german.txt */"Terroristen",
  InventoryItemUnequip: /* csgo_german.txt */"Ablegen",
  InventoryItemUnlockContainer: /* csgo_german.txt */"Behälter öffnen",
  InventoryItemUseStorageUnit: /* csgo_german.txt */"Diese Einheit verwenden",
  InventorySelectAnItem: /* csgo_german.txt */"Gegenstand auswählen zur Verwendung mit:",
  InventorySelectInspectContents: /* csgo_german.txt */"Inhalte von:",
  InventorySelectItemToDeposit: /* csgo_german.txt */"Gegenstände zum Verschieben auswählen:",
  InventorySelectItemToRetrieve: /* csgo_german.txt */"Gegenstände zum Abrufen auswählen:",
  ItemRarityAncient: /* csgo_german.txt */"Außerordentlich",
  ItemRarityCommon: /* csgo_german.txt */"Standardqualität",
  ItemRarityDefault: /* csgo_german.txt */"Standard",
  ItemRarityImmortal: /* csgo_german.txt */"Schmuggelware",
  ItemRarityLegendary: /* csgo_german.txt */"Exotisch",
  ItemRarityMythical: /* csgo_german.txt */"Bemerkenswert",
  ItemRarityNameAgent: /* csgo_german.txt */"Agent",
  ItemRarityNameCharm: /* csgo_german.txt */"Anhänger",
  ItemRarityNameCollectible: /* csgo_german.txt */"Sammlerstück",
  ItemRarityNameContainer: /* csgo_german.txt */"Behälter",
  ItemRarityNameContract: /* csgo_german.txt */"Vertrag",
  ItemRarityNameEquipment: /* csgo_german.txt */"Ausrüstung",
  ItemRarityNameGloves: /* csgo_german.txt */"Handschuhe",
  ItemRarityNameGraffiti: /* csgo_german.txt */"Graffiti",
  ItemRarityNameKey: /* csgo_german.txt */"Schlüssel",
  ItemRarityNameKnife: /* csgo_german.txt */"Messer",
  ItemRarityNameMachinegun: /* csgo_german.txt */"Maschinengewehr",
  ItemRarityNameMusicKit: /* csgo_german.txt */"Musikkit",
  ItemRarityNamePatch: /* csgo_german.txt */"Aufnäher",
  ItemRarityNamePistol: /* csgo_german.txt */"Pistole",
  ItemRarityNameRifle: /* csgo_german.txt */"Gewehr",
  ItemRarityNameSMG: /* csgo_german.txt */"MP",
  ItemRarityNameShotgun: /* csgo_german.txt */"Schrotflinte",
  ItemRarityNameSniperRifle: /* csgo_german.txt */"Scharfschützengewehr",
  ItemRarityNameSticker: /* csgo_german.txt */"Aufkleber",
  ItemRarityNameTool: /* csgo_german.txt */"Werkzeug",
  ItemRarityRare: /* csgo_german.txt */"Hohe Qualität",
  ItemRarityUncommon: /* csgo_german.txt */"Mittlere Qualität",
  ItemSwapStatTrakAccept: /* csgo_german.txt */"ÜBERNEHMEN",
  ItemSwapStatTrakClose: /* csgo_german.txt */"Schließen",
  ItemSwapStatTrakDesc: /* csgo_german.txt */"Dieser Gegenstand tauscht die StatTrak™-Werte zweier Gegenstände gleichen Typs aus.",
  ItemSwapStatTrakUse: /* csgo_german.txt */"StatTrak™-Austauschwerkzeug",
  ItemSwapStatTrakWarn: /* csgo_german.txt */"Dieses StatTrak™-Austauschwerkzeug kann nur einmal benutzt werden.",
  ItemWeaponRarityAncient: /* csgo_german.txt */"Verdeckt",
  ItemWeaponRarityCommon: /* csgo_german.txt */"Verbraucherklasse",
  ItemWeaponRarityDefault: /* csgo_german.txt */"Standard",
  ItemWeaponRarityImmortal: /* csgo_german.txt */"Schmuggelware",
  ItemWeaponRarityLegendary: /* csgo_german.txt */"Vertraulich",
  ItemWeaponRarityMythical: /* csgo_german.txt */"Limitiert",
  ItemWeaponRarityRare: /* csgo_german.txt */"Militärstandard",
  ItemWeaponRarityUncommon: /* csgo_german.txt */"Industriequalität",
  ItemWearBS: /* csgo_german.txt */"Kampfspuren",
  ItemWearFN: /* csgo_german.txt */"Fabrikneu",
  ItemWearFT: /* csgo_german.txt */"Einsatzerprobt",
  ItemWearMW: /* csgo_german.txt */"Minimale Gebrauchsspuren",
  ItemWearWW: /* csgo_german.txt */"Abgenutzt",
  RemovePatchRemove: /* csgo_german.txt */"Aufnäher entfernen",
  RemovePatchRemoveDesc: /* csgo_german.txt */"Bitte bestätigen Sie, dass Sie diesen Aufnäher wirklich von Ihrem Agenten entfernen möchten. Der entfernte Aufnäher wird dabei zerstört.",
  RemovePatchUse: /* csgo_german.txt */"Aufnäher entfernen",
  RemovePatchWarn: /* csgo_german.txt */"Aufnäher von  entfernen",
  RenameCancel: /* csgo_german.txt */"Abbrechen",
  RenameEnterName: /* csgo_german.txt */"Neuen Namen eingeben für:",
  RenameRename: /* csgo_german.txt */"umbenennen",
  RenameStorageUnitClose: /* csgo_german.txt */"Schließen",
  RenameStorageUnitEnterName: /* csgo_german.txt */"Neuen Namen eingeben für:",
  RenameStorageUnitFirstNameWarn: /* csgo_german.txt */"Geben Sie eine neue aussagekräftige Beschreibung für Ihre persönliche Speichereinheit ein und lagern Sie dort Ihre Gegenstände.",
  RenameStorageUnitNewNameWarn: /* csgo_german.txt */"Geben Sie eine neue aussagekräftige Beschreibung für diese Speichereinheit an.",
  RenameStorageUnitRename: /* csgo_german.txt */"Personalisieren",
  RenameStorageUnitUse: /* csgo_german.txt */"Speichereinheit personalisieren",
  RenameUse: /* csgo_german.txt */"Namensschild benutzen",
  RenameWarn: /* csgo_german.txt */"Ein Namensschild kann nur einmal benutzt werden",
  ScrapeStickerCancel: /* csgo_german.txt */"Abbrechen",
  ScrapeStickerClose: /* csgo_german.txt */"Schließen",
  ScrapeStickerRemove: /* csgo_german.txt */"Aufkleber entfernen",
  ScrapeStickerRemoveDesc: /* csgo_german.txt */"Das weitere Abkratzen dieses Aufklebers zerstört ihn und entfernt ihn von dem Gegenstand.",
  ScrapeStickerUse: /* csgo_german.txt */"Aufkleber abkratzen",
  ScrapeStickerWarn: /* csgo_german.txt */"Aufkleber von  abkratzen",
  SettingsMasterVolume: /* csgo_german.txt */"Gesamtlautstärke",
  StickerPickerRemove: /* csgo_german.txt */"Entfernen"
};
