/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const greek = {
  ...english,
  ApplyPatchUse: /* csgo_greek.txt */"Εφαρμογή διακριτικού",
  ApplyPatchWarn: /* csgo_greek.txt */"Ένα διακριτικό μπορεί να εφαρμοστεί μόνο μία φορά",
  ApplyStickerCancel: /* csgo_greek.txt */"Άκυρο",
  ApplyStickerUse: /* csgo_greek.txt */"Εφαρμογή αυτοκόλλητου",
  ApplyStickerUseOn: /* csgo_greek.txt */"Χρήση σε",
  ApplyStickerWarn: /* csgo_greek.txt */"Ένα αυτοκόλλητο μπορεί να εφαρμοστεί μόνο μία φορά",
  CaseAdd: /* csgo_greek.txt */"Προσθήκη",
  CaseClose: /* csgo_greek.txt */"ΚΛΕΙΣΙΜΟ",
  CaseContainsOne: /* csgo_greek.txt */"Περιέχει ένα από τα παρακάτω αντικείμενα:",
  CaseNeed: /* csgo_greek.txt */"Αυτή η ενέργεια απαιτεί",
  CaseOnceWarn: /* csgo_greek.txt */"Το κιβώτιο αυτό μπορεί να ανοιχθεί μόνο μία φορά",
  CaseRareItem: /* csgo_greek.txt */"★ Εξαιρετικά σπάνιο αντικείμενο ★",
  CaseUnlock: /* csgo_greek.txt */"Ξεκλείδωμα",
  CaseUnlockContainer: /* csgo_greek.txt */"Ξεκλείδωμα κιβωτίου",
  CaseUse: /* csgo_greek.txt */"Χρήση",
  CategoryAgent: /* csgo_greek.txt */"Πράκτορας",
  CategoryCase: /* csgo_greek.txt */"Κιβώτιο",
  CategoryCollectible: /* csgo_greek.txt */"Συλλεκτικό",
  CategoryEquipment: /* csgo_greek.txt */"Εξοπλισμός",
  CategoryGlove: /* csgo_greek.txt */"Γάντια",
  CategoryGraffiti: /* csgo_greek.txt */"Γκράφιτι",
  CategoryHeavy: /* csgo_greek.txt */"Οπλοπολυβόλα",
  CategoryKey: /* csgo_greek.txt */"Κλειδί",
  CategoryKnife: /* csgo_greek.txt */"Μαχαίρι",
  CategoryMusicKit: /* csgo_greek.txt */"Μουσικό κουτί",
  CategoryPatch: /* csgo_greek.txt */"Διακριτικό",
  CategoryPistol: /* csgo_greek.txt */"Πιστόλι",
  CategoryRifle: /* csgo_greek.txt */"Τυφέκιο",
  CategorySMG: /* csgo_greek.txt */"Υποπολυβόλο",
  CategorySticker: /* csgo_greek.txt */"Αυτοκόλλητο",
  CategoryTool: /* csgo_greek.txt */"Εργαλείο",
  EditorCancel: /* csgo_greek.txt */"Άκυρο",
  EditorNametag: /* csgo_greek.txt */"Ετικέτα ονόματος",
  EditorPatches: /* csgo_greek.txt */"ΔΙΑΚΡΙΤΙΚΑ",
  EditorQuantity: /* csgo_greek.txt */"Ποσότητα",
  EditorRandom: /* csgo_greek.txt */"Τυχαίος",
  EditorReset: /* csgo_greek.txt */"Επαναφορά",
  EditorSave: /* csgo_greek.txt */"Αποθήκευση",
  EditorSeed: /* csgo_greek.txt */"Μοτίβο",
  EditorStatTrak: /* csgo_greek.txt */"StatTrak™",
  EditorStickers: /* csgo_greek.txt */"Αυτοκόλλητα",
  EditorWear: /* csgo_greek.txt */"Φθορά",
  InspectClose: /* csgo_greek.txt */"ΚΛΕΙΣΙΜΟ",
  InventoryApplyPatch: /* csgo_greek.txt */"Εφαρμογή διακριτικού",
  InventoryApplySticker: /* csgo_greek.txt */"Εφαρμογή αυτοκόλλητου",
  InventoryFilterAgents: /* csgo_greek.txt */"ΠΡΑΚΤΟΡΕΣ",
  InventoryFilterAll: /* csgo_greek.txt */"ΟΛΑ",
  InventoryFilterAllEquipment: /* csgo_greek.txt */"ΟΛΟΣ Ο ΕΞΟΠΛΙΣΜΟΣ",
  InventoryFilterAllGraphicArt: /* csgo_greek.txt */"ΟΛΕΣ ΟΙ ΓΡΑΦΙΚΕΣ ΤΕΧΝΕΣ",
  InventoryFilterAlphabetical: /* csgo_greek.txt */"Αλφαβητικά",
  InventoryFilterCollection: /* csgo_greek.txt */"Συλλογή",
  InventoryFilterContainers: /* csgo_greek.txt */"ΚΟΝΤΕΪΝΕΡ",
  InventoryFilterDisplay: /* csgo_greek.txt */"ΠΡΟΒΟΛΗ",
  InventoryFilterEquipment: /* csgo_greek.txt */"ΕΞΟΠΛΙΣΜΟΣ",
  InventoryFilterEquipped: /* csgo_greek.txt */"Εξοπλισμένο",
  InventoryFilterEverything: /* csgo_greek.txt */"ΟΛΑ",
  InventoryFilterGloves: /* csgo_greek.txt */"Γάντια",
  InventoryFilterGraffiti: /* csgo_greek.txt */"ΓΚΡΑΦΙΤΙ",
  InventoryFilterGraffitiBoxes: /* csgo_greek.txt */"Κουτιά γκράφιτι",
  InventoryFilterGraphicArt: /* csgo_greek.txt */"ΓΡΑΦΙΚΗ ΤΕΧΝΗ",
  InventoryFilterMedals: /* csgo_greek.txt */"ΜΕΤΑΛΛΙΑ",
  InventoryFilterMelee: /* csgo_greek.txt */"ΑΓΧΕΜΑΧΟ ΟΠΛΟ",
  InventoryFilterMidTier: /* csgo_greek.txt */"ΜΕΣΑΙΑ ΒΑΘΜΙΔΑ",
  InventoryFilterMisc: /* csgo_greek.txt */"Λοιπά",
  InventoryFilterMusicKits: /* csgo_greek.txt */"ΜΟΥΣΙΚΑ ΚΟΥΤΙΑ",
  InventoryFilterNewest: /* csgo_greek.txt */"Νεότερα",
  InventoryFilterPatches: /* csgo_greek.txt */"ΔΙΑΚΡΙΤΙΚΑ",
  InventoryFilterPistols: /* csgo_greek.txt */"ΠΙΣΤΟΛΙΑ",
  InventoryFilterQuality: /* csgo_greek.txt */"Ποιότητα",
  InventoryFilterRifles: /* csgo_greek.txt */"ΤΟΥΦΕΚΙΑ",
  InventoryFilterSearch: /* csgo_greek.txt */"Αναζήτηση τύπου εδώ",
  InventoryFilterSouvenirCases: /* csgo_greek.txt */"Σεντούκια ενθυμίων",
  InventoryFilterStickerCapsules: /* csgo_greek.txt */"Κάψουλες αυτοκόλλητων",
  InventoryFilterStickers: /* csgo_greek.txt */"ΑΥΤΟΚΟΛΛΗΤΑ",
  InventoryFilterTools: /* csgo_greek.txt */"ΕΡΓΑΛΕΙΑ",
  InventoryFilterType: /* csgo_greek.txt */"Τύπος",
  InventoryFilterWeaponCases: /* csgo_greek.txt */"Θήκες όπλων",
  InventoryItemContainsOne: /* csgo_greek.txt */"Περιέχει ένα από τα παρακάτω αντικείμενα:",
  InventoryItemDelete: /* csgo_greek.txt */"Διαγραφή",
  InventoryItemEdit: /* csgo_greek.txt */"Επεξεργασία",
  InventoryItemEquip: /* csgo_greek.txt */"Εξόπλιση",
  InventoryItemExterior: /* csgo_greek.txt */"Εξωτερικό:",
  InventoryItemInspect: /* csgo_greek.txt */"Επιθεώρηση",
  InventoryItemInspectFinishCatalog: /* csgo_greek.txt */"Αριθμός καταλόγου",
  InventoryItemInspectInGame: /* csgo_greek.txt */"Επιθεώρηση εντός παιχνιδιού...",
  InventoryItemInspectPatternTemplate: /* csgo_greek.txt */"Τύπος μοτίβου",
  InventoryItemInspectWearRating: /* csgo_greek.txt */"Βαθμός φθοράς",
  InventoryItemMVPStatTrakCount: /* csgo_greek.txt */"Επίσημοι ανταγωνιστικοί StatTrak™ MVP:",
  InventoryItemNew: /* csgo_greek.txt */"Νέο!",
  InventoryItemRareItem: /* csgo_greek.txt */"ή ένα υπερβολικά σπάνιο αντικείμενο!",
  InventoryItemRarity: /* csgo_greek.txt */"Σπανιότητα:",
  InventoryItemRemovePatch: /* csgo_greek.txt */"Αφαίρεση διακριτικού",
  InventoryItemRename: /* csgo_greek.txt */"Μετονομασία",
  InventoryItemRenameStorageUnit: /* csgo_greek.txt */"Αλλαγή ετικέτας",
  InventoryItemScrapeSticker: /* csgo_greek.txt */"Ξύσιμο αυτοκόλλητου",
  InventoryItemStatTrak: /* csgo_greek.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_greek.txt */"Επικυρωμένοι φόνοι StatTrak™:",
  InventoryItemStatTrakDesc: /* csgo_greek.txt */"Αυτό το αντικείμενο χρησιμοποιεί τεχνολογία StatTrak™, που ανιχνεύει ορισμένα στατιστικά όταν το χειρίζεται ο κάτοχός του.",
  InventoryItemStorageUnitDeposit: /* csgo_greek.txt */"Εναπόθεση αντικειμένων",
  InventoryItemStorageUnitEmptyBody: /* csgo_greek.txt */"Αυτό το κιβώτιο αποθήκευσης σας επιτρέπει να φυλάξετε έως {1} από τα επιπλέον αντικείμενα σας που θα ξεπερνούσαν αλλιώς το όριο της λίστας αντικειμένων σας. Το επιλεγμένο κιβώτιό σας είναι αυτή τη στιγμή άδειο. Οποιαδήποτε στιγμή μπορείτε να μετακινήσετε αντικείμενα από τη λίστα αντικειμένων σας στο κιβώτιο, να επιστρέψετε αντικείμενα πίσω στη λίστα αντικειμένων σας ή απλά να το χρησιμοποιήσετε για να οργανώσετε τα συλλεκτικά σας.",
  InventoryItemStorageUnitEmptyClose: /* csgo_greek.txt */"Εντάξει",
  InventoryItemStorageUnitEmptyTitle: /* csgo_greek.txt */"Άδειασμα κιβωτίου αποθήκευσης",
  InventoryItemStorageUnitInspect: /* csgo_greek.txt */"Επιθεώρηση",
  InventoryItemStorageUnitRetrieve: /* csgo_greek.txt */"Ανάκτηση αντικειμένων",
  InventoryItemSwapStatTrak: /* csgo_greek.txt */"Άνοιγμα εργαλείου εναλλαγής StatTrak™",
  InventoryItemTeam: /* csgo_greek.txt */"Ομάδα:",
  InventoryItemTeamAny: /* csgo_greek.txt */"Οποιαδήποτε",
  InventoryItemTeamCT: /* csgo_greek.txt */"Αντιτρομοκρατική",
  InventoryItemTeamT: /* csgo_greek.txt */"Τρομοκράτες",
  InventoryItemUnequip: /* csgo_greek.txt */"Παρόπλιση",
  InventoryItemUnlockContainer: /* csgo_greek.txt */"Ξεκλείδωμα κιβωτίου",
  InventoryItemUseStorageUnit: /* csgo_greek.txt */"Έναρξη χρήσης κιβωτίου",
  InventorySelectAnItem: /* csgo_greek.txt */"ΕΠΙΛΟΓΗ ΑΝΤΙΚΕΙΜΕΝΟΥ ΓΙΑ ΧΡΗΣΗ ΜΕ:",
  InventorySelectInspectContents: /* csgo_greek.txt */"Επιθεωρείτε τα περιεχόμενα από",
  InventorySelectItemToDeposit: /* csgo_greek.txt */"Επιλέξτε αντικείμενα για να μετακινήσετε σε",
  InventorySelectItemToRetrieve: /* csgo_greek.txt */"Επιλέξτε αντικείμενα για να λάβετε",
  ItemRarityAncient: /* csgo_greek.txt */"Extraordinary",
  ItemRarityCommon: /* csgo_greek.txt */"Base Grade",
  ItemRarityDefault: /* csgo_greek.txt */"Προεπιλογή",
  ItemRarityImmortal: /* csgo_greek.txt */"Contraband",
  ItemRarityLegendary: /* csgo_greek.txt */"Exotic",
  ItemRarityMythical: /* csgo_greek.txt */"Remarkable",
  ItemRarityNameAgent: /* csgo_greek.txt */"Πράκτορας",
  ItemRarityNameCollectible: /* csgo_greek.txt */"Συλλεκτικό",
  ItemRarityNameContainer: /* csgo_greek.txt */"Κιβώτιο",
  ItemRarityNameContract: /* csgo_greek.txt */"Συμβόλαιο",
  ItemRarityNameEquipment: /* csgo_greek.txt */"Εξοπλισμός",
  ItemRarityNameGloves: /* csgo_greek.txt */"Γάντια",
  ItemRarityNameGraffiti: /* csgo_greek.txt */"Γκράφιτι",
  ItemRarityNameKey: /* csgo_greek.txt */"Κλειδί",
  ItemRarityNameKnife: /* csgo_greek.txt */"Μαχαίρι",
  ItemRarityNameMachinegun: /* csgo_greek.txt */"Πολυβόλο",
  ItemRarityNameMusicKit: /* csgo_greek.txt */"Μουσικό κουτί",
  ItemRarityNamePatch: /* csgo_greek.txt */"Διακριτικό",
  ItemRarityNamePistol: /* csgo_greek.txt */"Πιστόλι",
  ItemRarityNameRifle: /* csgo_greek.txt */"Τυφέκιο",
  ItemRarityNameSMG: /* csgo_greek.txt */"Υποπολυβόλο",
  ItemRarityNameShotgun: /* csgo_greek.txt */"Καραμπίνα",
  ItemRarityNameSniperRifle: /* csgo_greek.txt */"Τουφέκι ακροβολιστή",
  ItemRarityNameSticker: /* csgo_greek.txt */"Αυτοκόλλητο",
  ItemRarityNameTool: /* csgo_greek.txt */"Εργαλείο",
  ItemRarityRare: /* csgo_greek.txt */"High Grade",
  ItemRarityUncommon: /* csgo_greek.txt */"Medium Grade",
  ItemSwapStatTrakAccept: /* csgo_greek.txt */"ΑΠΟΔΟΧΗ",
  ItemSwapStatTrakClose: /* csgo_greek.txt */"ΚΛΕΙΣΙΜΟ",
  ItemSwapStatTrakDesc: /* csgo_greek.txt */"Αυτό το αντικείμενο εναλλάσσει τις τιμές StatTrak™ μεταξύ δύο αντικειμένων ίδιου τύπου.",
  ItemSwapStatTrakUse: /* csgo_greek.txt */"Εργαλείο εναλλαγής StatTrak™",
  ItemSwapStatTrakWarn: /* csgo_greek.txt */"Αυτό το εργαλείο εναλλαγής StatTrak™ μπορεί να χρησιμοποιηθεί μόνο μία φορά",
  ItemWeaponRarityAncient: /* csgo_greek.txt */"Covert",
  ItemWeaponRarityCommon: /* csgo_greek.txt */"Consumer Grade",
  ItemWeaponRarityDefault: /* csgo_greek.txt */"Αρχικό",
  ItemWeaponRarityImmortal: /* csgo_greek.txt */"Contraband",
  ItemWeaponRarityLegendary: /* csgo_greek.txt */"Classified",
  ItemWeaponRarityMythical: /* csgo_greek.txt */"Restricted",
  ItemWeaponRarityRare: /* csgo_greek.txt */"Mil-Spec Grade",
  ItemWeaponRarityUncommon: /* csgo_greek.txt */"Industrial Grade",
  ItemWearBS: /* csgo_greek.txt */"Ξεσκισμένο από μάχη",
  ItemWearFN: /* csgo_greek.txt */"Εργοστασιακό",
  ItemWearFT: /* csgo_greek.txt */"Δοκιμασμένο στη μάχη",
  ItemWearMW: /* csgo_greek.txt */"Με ελάχιστες φθορές",
  ItemWearWW: /* csgo_greek.txt */"Πολυκαιρισμένο",
  RemovePatchRemove: /* csgo_greek.txt */"Αφαίρεση διακριτικού",
  RemovePatchRemoveDesc: /* csgo_greek.txt */"Επιβεβαιώστε ότι θέλετε να αφαιρέσετε αυτό το διακριτικό από τον πράκτορά σας. Το αφαιρούμενο διακριτικό θα καταστραφεί.",
  RemovePatchUse: /* csgo_greek.txt */"Αφαίρεση διακριτικού",
  RemovePatchWarn: /* csgo_greek.txt */"Αφαίρεση διακριτικού από",
  RenameCancel: /* csgo_greek.txt */"Άκυρο",
  RenameEnterName: /* csgo_greek.txt */"Εισάγετε ένα νέο όνομα για:",
  RenameRename: /* csgo_greek.txt */"Μετονομασία",
  RenameStorageUnitClose: /* csgo_greek.txt */"ΚΛΕΙΣΙΜΟ",
  RenameStorageUnitEnterName: /* csgo_greek.txt */"Εισάγετε ένα νέο όνομα για:",
  RenameStorageUnitFirstNameWarn: /* csgo_greek.txt */"Εισάγετε μια περιγραφική ετικέτα για το προσωπικό κιβώτιο αποθήκευσής σας και αρχίστε να το χρησιμοποιείτε για αποθήκευση αντικειμένων.",
  RenameStorageUnitNewNameWarn: /* csgo_greek.txt */"Εισάγετε μια νέα περιγραφική ετικέτα για αυτό το κιβώτιο αποθήκευσης.",
  RenameStorageUnitRename: /* csgo_greek.txt */"Εξατομίκευση",
  RenameStorageUnitUse: /* csgo_greek.txt */"Εξατομίκευση του κιβωτίου αποθήκευσης σας",
  RenameUse: /* csgo_greek.txt */"Χρήση ετικέτας ονόματος",
  RenameWarn: /* csgo_greek.txt */"Μια ετικέτα ονόματος μπορεί να χρησιμοποιηθεί μόνο μία φορά",
  ScrapeStickerCancel: /* csgo_greek.txt */"Άκυρο",
  ScrapeStickerClose: /* csgo_greek.txt */"ΚΛΕΙΣΙΜΟ",
  ScrapeStickerRemove: /* csgo_greek.txt */"Αφαίρεση αυτοκόλλητου",
  ScrapeStickerRemoveDesc: /* csgo_greek.txt */"Ξύνοντας περισσότερο αυτό το αυτοκόλλητο θα αφαιρεθεί από το αντικείμενο και θα καταστραφεί.",
  ScrapeStickerUse: /* csgo_greek.txt */"Ξύσιμο αυτοκόλλητου",
  ScrapeStickerWarn: /* csgo_greek.txt */"Ξύσιμο αυτοκόλλητου από",
  StickerPickerRemove: /* csgo_greek.txt */"Αφαίρεση"
};
