/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const hungarian = {
  ...english,
  ApplyPatchUse: /* csgo_hungarian.txt */"Felvarró elhelyezése",
  ApplyPatchWarn: /* csgo_hungarian.txt */"Egy felvarró csak egyszer használható",
  ApplyStickerCancel: /* csgo_hungarian.txt */"Mégse",
  ApplyStickerUse: /* csgo_hungarian.txt */"Matrica felragasztása",
  ApplyStickerUseOn: /* csgo_hungarian.txt */"Használat ezen:",
  ApplyStickerWarn: /* csgo_hungarian.txt */"Egy matrica csak egyszer használható",
  CaseAdd: /* csgo_hungarian.txt */"Hozzáadás",
  CaseClose: /* csgo_hungarian.txt */"Bezár",
  CaseContainsOne: /* csgo_hungarian.txt */"A következők egyikét tartalmazza:",
  CaseNeed: /* csgo_hungarian.txt */"E művelethez  szükséges",
  CaseOnceWarn: /* csgo_hungarian.txt */"Ez a tároló csak egyszer nyitható ki.",
  CaseRareItem: /* csgo_hungarian.txt */"★ Ritka különleges tárgy ★",
  CaseUnlock: /* csgo_hungarian.txt */"feloldása",
  CaseUnlockContainer: /* csgo_hungarian.txt */"Tároló kinyitása",
  CaseUse: /* csgo_hungarian.txt */"használata",
  CategoryAgent: /* csgo_hungarian.txt */"Ügynök",
  CategoryCase: /* csgo_hungarian.txt */"Tároló",
  CategoryCollectible: /* csgo_hungarian.txt */"Gyűjthető",
  CategoryEquipment: /* csgo_hungarian.txt */"Felszerelés",
  CategoryGlove: /* csgo_hungarian.txt */"Kesztyű",
  CategoryGraffiti: /* csgo_hungarian.txt */"Falfirka",
  CategoryHeavy: /* csgo_hungarian.txt */"Nehézfegyverek",
  CategoryKey: /* csgo_hungarian.txt */"Kulcs",
  CategoryKeychain: /* csgo_hungarian.txt */"Talizmán",
  CategoryKnife: /* csgo_hungarian.txt */"Kés",
  CategoryMusicKit: /* csgo_hungarian.txt */"Zenekészlet",
  CategoryPatch: /* csgo_hungarian.txt */"Felvarró",
  CategoryPistol: /* csgo_hungarian.txt */"Pisztoly",
  CategoryRifle: /* csgo_hungarian.txt */"Puska",
  CategorySMG: /* csgo_hungarian.txt */"Géppisztoly",
  CategorySticker: /* csgo_hungarian.txt */"Matrica",
  CategoryTool: /* csgo_hungarian.txt */"Eszköz",
  EditorCancel: /* csgo_hungarian.txt */"Mégse",
  EditorNametag: /* csgo_hungarian.txt */"Névcédula",
  EditorPatches: /* csgo_hungarian.txt */"Felvarrók",
  EditorQuantity: /* csgo_hungarian.txt */"Mennyiség",
  EditorRandom: /* csgo_hungarian.txt */"Véletlenszerű",
  EditorReset: /* csgo_hungarian.txt */"Visszaállítás",
  EditorSave: /* csgo_hungarian.txt */"Mentés",
  EditorSeed: /* csgo_hungarian.txt */"Minta",
  EditorStatTrak: /* csgo_hungarian.txt */"StatTrak™",
  EditorStickers: /* csgo_hungarian.txt */"Matricák",
  EditorWear: /* csgo_hungarian.txt */"Kopottság",
  GenericCancel: /* csgo_hungarian.txt */"Mégse",
  InspectClose: /* csgo_hungarian.txt */"Bezár",
  InventoryApplyPatch: /* csgo_hungarian.txt */"Felvarró elhelyezése",
  InventoryApplySticker: /* csgo_hungarian.txt */"Matrica felragasztása",
  InventoryFilterAgents: /* csgo_hungarian.txt */"Ügynökök",
  InventoryFilterAll: /* csgo_hungarian.txt */"Összes",
  InventoryFilterAllEquipment: /* csgo_hungarian.txt */"Minden felszerelés",
  InventoryFilterAllGraphicArt: /* csgo_hungarian.txt */"Minden grafikai alkotás",
  InventoryFilterAlphabetical: /* csgo_hungarian.txt */"Betűrend",
  InventoryFilterCharms: /* csgo_hungarian.txt */"Talizmánok",
  InventoryFilterCollection: /* csgo_hungarian.txt */"Gyűjtemény",
  InventoryFilterContainers: /* csgo_hungarian.txt */"TÁROLÓK",
  InventoryFilterDisplay: /* csgo_hungarian.txt */"DÍSZÍTŐK",
  InventoryFilterEquipment: /* csgo_hungarian.txt */"FELSZERELÉS",
  InventoryFilterEquipped: /* csgo_hungarian.txt */"Felszerelve",
  InventoryFilterEverything: /* csgo_hungarian.txt */"MINDEN",
  InventoryFilterGloves: /* csgo_hungarian.txt */"Kesztyű",
  InventoryFilterGraffiti: /* csgo_hungarian.txt */"Falfirka",
  InventoryFilterGraffitiBoxes: /* csgo_hungarian.txt */"Falfirka ládák",
  InventoryFilterGraphicArt: /* csgo_hungarian.txt */"GRAFIKA",
  InventoryFilterMedals: /* csgo_hungarian.txt */"Kitüntetések",
  InventoryFilterMelee: /* csgo_hungarian.txt */"Közelharci",
  InventoryFilterMidTier: /* csgo_hungarian.txt */"Középszint",
  InventoryFilterMisc: /* csgo_hungarian.txt */"Egyéb",
  InventoryFilterMusicKits: /* csgo_hungarian.txt */"Zenekészletek",
  InventoryFilterNewest: /* csgo_hungarian.txt */"Legújabb",
  InventoryFilterPatches: /* csgo_hungarian.txt */"Felvarrók",
  InventoryFilterPistols: /* csgo_hungarian.txt */"Pisztolyok",
  InventoryFilterQuality: /* csgo_hungarian.txt */"Minőség",
  InventoryFilterRifles: /* csgo_hungarian.txt */"Puskák",
  InventoryFilterSearch: /* csgo_hungarian.txt */"Ide írd a keresendő kifejezést",
  InventoryFilterSouvenirCases: /* csgo_hungarian.txt */"Emléktárgyládák",
  InventoryFilterStickerCapsules: /* csgo_hungarian.txt */"Matricakapszulák",
  InventoryFilterStickers: /* csgo_hungarian.txt */"Matricák",
  InventoryFilterTools: /* csgo_hungarian.txt */"Eszközök",
  InventoryFilterType: /* csgo_hungarian.txt */"Típus",
  InventoryFilterWeaponCases: /* csgo_hungarian.txt */"Fegyverládák",
  InventoryItemContainsOne: /* csgo_hungarian.txt */"A következők egyikét tartalmazza:",
  InventoryItemDelete: /* csgo_hungarian.txt */"Törlés",
  InventoryItemDeleteConfirm: /* csgo_hungarian.txt */"Tárgy törlése",
  InventoryItemDeleteConfirmDesc: /* csgo_hungarian.txt */"Biztosan törölni szeretnéd ezt az elemet?",
  InventoryItemEdit: /* csgo_hungarian.txt */"Szerkesztés",
  InventoryItemEquip: /* csgo_hungarian.txt */"Felszerel",
  InventoryItemExterior: /* csgo_hungarian.txt */"Külső:",
  InventoryItemInspect: /* csgo_hungarian.txt */"Megvizsgálás",
  InventoryItemInspectFinishCatalog: /* csgo_hungarian.txt */"Festéskatalógus",
  InventoryItemInspectInGame: /* csgo_hungarian.txt */"Megvizsgálás játékban...",
  InventoryItemInspectPatternTemplate: /* csgo_hungarian.txt */"Mintasablon",
  InventoryItemInspectWearRating: /* csgo_hungarian.txt */"Kopottsági érték",
  InventoryItemMVPStatTrakCount: /* csgo_hungarian.txt */"StatTrak™ hivatalos versengő MVP-k:",
  InventoryItemNew: /* csgo_hungarian.txt */"Új!",
  InventoryItemRareItem: /* csgo_hungarian.txt */"vagy egy rendkívül ritka különleges tárgy!",
  InventoryItemRarity: /* csgo_hungarian.txt */"Ritkaság:",
  InventoryItemRemovePatch: /* csgo_hungarian.txt */"Felvarró eltávolítása",
  InventoryItemRename: /* csgo_hungarian.txt */"átnevezése",
  InventoryItemRenameStorageUnit: /* csgo_hungarian.txt */"Címkeváltoztatás",
  InventoryItemScrapeSticker: /* csgo_hungarian.txt */"Matrica kaparása",
  InventoryItemStatTrak: /* csgo_hungarian.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_hungarian.txt */"StatTrak™ megerősített ölések:",
  InventoryItemStatTrakDesc: /* csgo_hungarian.txt */"Ez a tárgy StatTrak™ technológiát használ, ami rögzít bizonyos statisztikákat, mikor a tulajdonos felszerelte.",
  InventoryItemStorageUnitDeposit: /* csgo_hungarian.txt */"Tárgyak berakása",
  InventoryItemStorageUnitEmptyBody: /* csgo_hungarian.txt */"Ez a Raktárhelyiség lehetővé teszi legfeljebb {1} elfekvő tárgyad tárolását, amelyek egyébként meghaladnák a raktárkorlátot. A kiválasztott raktárhelyiség jelenleg üres. Bármikor mozgathatsz tárgyakat a raktáradból a raktárhelyiségbe, visszatehetsz belőle a raktáradba, vagy használhatod egyszerűen csak gyűjteményed rendszerezéséhez.",
  InventoryItemStorageUnitEmptyClose: /* csgo_hungarian.txt */"OK",
  InventoryItemStorageUnitEmptyTitle: /* csgo_hungarian.txt */"Üres raktárhelyiség",
  InventoryItemStorageUnitInspect: /* csgo_hungarian.txt */"Megvizsgálás",
  InventoryItemStorageUnitRetrieve: /* csgo_hungarian.txt */"Tárgyak kivétele",
  InventoryItemSwapStatTrak: /* csgo_hungarian.txt */"StatTrak™ Cserélő Szerszám megnyitása",
  InventoryItemTeam: /* csgo_hungarian.txt */"Csapat:",
  InventoryItemTeamAny: /* csgo_hungarian.txt */"Bármely",
  InventoryItemTeamCT: /* csgo_hungarian.txt */"Terrorelhárítók",
  InventoryItemTeamT: /* csgo_hungarian.txt */"Terroristák",
  InventoryItemUnequip: /* csgo_hungarian.txt */"Letesz",
  InventoryItemUnlockContainer: /* csgo_hungarian.txt */"Tároló kinyitása",
  InventoryItemUseStorageUnit: /* csgo_hungarian.txt */"Egység használatának megkezdése",
  InventorySelectAnItem: /* csgo_hungarian.txt */"Válassz tárgyat, amivel használod:",
  InventorySelectInspectContents: /* csgo_hungarian.txt */"Tartalom megvizsgálása",
  InventorySelectItemToDeposit: /* csgo_hungarian.txt */"Válassz behelyezendő tárgyakat",
  InventorySelectItemToRetrieve: /* csgo_hungarian.txt */"Válassz kiveendő tárgyakat",
  ItemRarityAncient: /* csgo_hungarian.txt */"Rendkívüli",
  ItemRarityCommon: /* csgo_hungarian.txt */"Alap fokozatú",
  ItemRarityDefault: /* csgo_hungarian.txt */"Alapértelmezett",
  ItemRarityImmortal: /* csgo_hungarian.txt */"Csempészett",
  ItemRarityLegendary: /* csgo_hungarian.txt */"Egzotikus",
  ItemRarityMythical: /* csgo_hungarian.txt */"Figyelemre méltó",
  ItemRarityNameAgent: /* csgo_hungarian.txt */"Ügynök",
  ItemRarityNameCharm: /* csgo_hungarian.txt */"Talizmán",
  ItemRarityNameCollectible: /* csgo_hungarian.txt */"Gyűjthető",
  ItemRarityNameContainer: /* csgo_hungarian.txt */"Tároló",
  ItemRarityNameContract: /* csgo_hungarian.txt */"Szerződés",
  ItemRarityNameEquipment: /* csgo_hungarian.txt */"Felszerelés",
  ItemRarityNameGloves: /* csgo_hungarian.txt */"Kesztyű",
  ItemRarityNameGraffiti: /* csgo_hungarian.txt */"Falfirka",
  ItemRarityNameKey: /* csgo_hungarian.txt */"Kulcs",
  ItemRarityNameKnife: /* csgo_hungarian.txt */"Kés",
  ItemRarityNameMachinegun: /* csgo_hungarian.txt */"Géppuska",
  ItemRarityNameMusicKit: /* csgo_hungarian.txt */"Zenekészlet",
  ItemRarityNamePatch: /* csgo_hungarian.txt */"Felvarró",
  ItemRarityNamePistol: /* csgo_hungarian.txt */"Pisztoly",
  ItemRarityNameRifle: /* csgo_hungarian.txt */"Puska",
  ItemRarityNameSMG: /* csgo_hungarian.txt */"Géppisztoly",
  ItemRarityNameShotgun: /* csgo_hungarian.txt */"Sörétes puska",
  ItemRarityNameSniperRifle: /* csgo_hungarian.txt */"Mesterlövész puska",
  ItemRarityNameSticker: /* csgo_hungarian.txt */"Matrica",
  ItemRarityNameTool: /* csgo_hungarian.txt */"Eszköz",
  ItemRarityRare: /* csgo_hungarian.txt */"Magas fokozatú",
  ItemRarityUncommon: /* csgo_hungarian.txt */"Közép fokozatú",
  ItemSwapStatTrakAccept: /* csgo_hungarian.txt */"ELFOGAD",
  ItemSwapStatTrakClose: /* csgo_hungarian.txt */"Bezár",
  ItemSwapStatTrakDesc: /* csgo_hungarian.txt */"Ez a tárgy StatTrak™ értékeket cserél két ugyanolyan típusú tárgy között.",
  ItemSwapStatTrakUse: /* csgo_hungarian.txt */"StatTrak™ Cserélő Szerszám",
  ItemSwapStatTrakWarn: /* csgo_hungarian.txt */"Ez a StatTrak™ Cserélő Szerszám csak egyszer használható.",
  ItemWeaponRarityAncient: /* csgo_hungarian.txt */"Fedett",
  ItemWeaponRarityCommon: /* csgo_hungarian.txt */"Fogyasztói fokozatú",
  ItemWeaponRarityDefault: /* csgo_hungarian.txt */"Kincstári",
  ItemWeaponRarityImmortal: /* csgo_hungarian.txt */"Csempészett",
  ItemWeaponRarityLegendary: /* csgo_hungarian.txt */"Bizalmas",
  ItemWeaponRarityMythical: /* csgo_hungarian.txt */"Korlátozott",
  ItemWeaponRarityRare: /* csgo_hungarian.txt */"Katonai fokozatú",
  ItemWeaponRarityUncommon: /* csgo_hungarian.txt */"Ipari fokozatú",
  ItemWearBS: /* csgo_hungarian.txt */"Háború tépázta",
  ItemWearFN: /* csgo_hungarian.txt */"Gyári új",
  ItemWearFT: /* csgo_hungarian.txt */"Harctéren tesztelt",
  ItemWearMW: /* csgo_hungarian.txt */"Kevéssé használt",
  ItemWearWW: /* csgo_hungarian.txt */"Viseltes",
  RemovePatchRemove: /* csgo_hungarian.txt */"Felvarró eltávolítása",
  RemovePatchRemoveDesc: /* csgo_hungarian.txt */"Kérjük, erősítsd meg, hogy el szeretnéd távolítani ezt a felvarrót az ügynöködről. Az eltávolított felvarró megsemmisül.",
  RemovePatchUse: /* csgo_hungarian.txt */"Felvarró eltávolítása",
  RemovePatchWarn: /* csgo_hungarian.txt */"Felvarró eltávolítása a(z)  tárgyról",
  RenameCancel: /* csgo_hungarian.txt */"Mégse",
  RenameEnterName: /* csgo_hungarian.txt */"Írj be új nevet ennek:",
  RenameRename: /* csgo_hungarian.txt */"átnevezése",
  RenameStorageUnitClose: /* csgo_hungarian.txt */"Bezár",
  RenameStorageUnitEnterName: /* csgo_hungarian.txt */"Írj be új nevet ennek:",
  RenameStorageUnitFirstNameWarn: /* csgo_hungarian.txt */"Írj be egy jellemző címkét raktárhelyiségednek, majd vedd használatba tárgyak tárolására.",
  RenameStorageUnitNewNameWarn: /* csgo_hungarian.txt */"Írj be egy jellemző címkét ennek a raktárhelyiségnek.",
  RenameStorageUnitRename: /* csgo_hungarian.txt */"Személyre szabás",
  RenameStorageUnitUse: /* csgo_hungarian.txt */"Raktárhelyiséged személyre szabása",
  RenameUse: /* csgo_hungarian.txt */"Névcédula használata",
  RenameWarn: /* csgo_hungarian.txt */"A névcédula csak egyszer használható fel.",
  ScrapeStickerCancel: /* csgo_hungarian.txt */"Mégse",
  ScrapeStickerClose: /* csgo_hungarian.txt */"Bezár",
  ScrapeStickerRemove: /* csgo_hungarian.txt */"Matrica eltávolítása",
  ScrapeStickerRemoveDesc: /* csgo_hungarian.txt */"Tovább kaparva ezt a matricát az eltávolításra kerül a tárgyról, és megsemmisül.",
  ScrapeStickerUse: /* csgo_hungarian.txt */"Matrica kaparása",
  ScrapeStickerWarn: /* csgo_hungarian.txt */"Matrica lekaparása a(z)  tárgyról",
  SettingsMasterVolume: /* csgo_hungarian.txt */"Fő hangerő",
  StickerPickerRemove: /* csgo_hungarian.txt */"Eltávolít"
};
