/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const indonesian = {
  ...english,
  ApplyPatchUse: /* csgo_indonesian.txt */"Tempel Patch",
  ApplyPatchWarn: /* csgo_indonesian.txt */"Patch hanya bisa ditempel satu kali",
  ApplyStickerCancel: /* csgo_indonesian.txt */"Batal",
  ApplyStickerUse: /* csgo_indonesian.txt */"Tempel Stiker",
  ApplyStickerUseOn: /* csgo_indonesian.txt */"Gunakan pada",
  ApplyStickerWarn: /* csgo_indonesian.txt */"Stiker hanya bisa ditempel satu kali",
  CaseAdd: /* csgo_indonesian.txt */"Tambah",
  CaseClose: /* csgo_indonesian.txt */"Tutup",
  CaseContainsOne: /* csgo_indonesian.txt */"Berisi salah satu dari item berikut:",
  CaseNeed: /* csgo_indonesian.txt */"Hal ini membutuhkan sebuah",
  CaseOnceWarn: /* csgo_indonesian.txt */"Kontainer ini hanya bisa dibuka satu kali",
  CaseRareItem: /* csgo_indonesian.txt */"★ Item Langka Spesial ★",
  CaseUnlock: /* csgo_indonesian.txt */"Buka",
  CaseUnlockContainer: /* csgo_indonesian.txt */"Buka Kontainer",
  CaseUse: /* csgo_indonesian.txt */"Gunakan",
  CategoryAgent: /* csgo_indonesian.txt */"Agen",
  CategoryCase: /* csgo_indonesian.txt */"Kontainer",
  CategoryCollectible: /* csgo_indonesian.txt */"Item Koleksi",
  CategoryEquipment: /* csgo_indonesian.txt */"Peralatan",
  CategoryGlove: /* csgo_indonesian.txt */"Sarung Tangan",
  CategoryGraffiti: /* csgo_indonesian.txt */"Grafiti",
  CategoryHeavy: /* csgo_indonesian.txt */"Senjata Berat",
  CategoryKey: /* csgo_indonesian.txt */"Kunci",
  CategoryKnife: /* csgo_indonesian.txt */"Pisau",
  CategoryMusicKit: /* csgo_indonesian.txt */"Kit Musik",
  CategoryPatch: /* csgo_indonesian.txt */"Patch",
  CategoryPistol: /* csgo_indonesian.txt */"Pistol",
  CategoryRifle: /* csgo_indonesian.txt */"Rifle",
  CategorySMG: /* csgo_indonesian.txt */"SMG",
  CategorySticker: /* csgo_indonesian.txt */"Stiker",
  CategoryTool: /* csgo_indonesian.txt */"Alat",
  EditorCancel: /* csgo_indonesian.txt */"Batal",
  EditorNametag: /* csgo_indonesian.txt */"Tag Nama",
  EditorPatches: /* csgo_indonesian.txt */"Patch",
  EditorQuantity: /* csgo_indonesian.txt */"Jumlah",
  EditorRandom: /* csgo_indonesian.txt */"Acak",
  EditorReset: /* csgo_indonesian.txt */"Reset",
  EditorSave: /* csgo_indonesian.txt */"Simpan",
  EditorSeed: /* csgo_indonesian.txt */"Pola",
  EditorStatTrak: /* csgo_indonesian.txt */"StatTrak™",
  EditorStickers: /* csgo_indonesian.txt */"Stiker",
  EditorWear: /* csgo_indonesian.txt */"Kondisi",
  InspectClose: /* csgo_indonesian.txt */"Tutup",
  InventoryApplyPatch: /* csgo_indonesian.txt */"Tempel Patch",
  InventoryApplySticker: /* csgo_indonesian.txt */"Tempel Stiker",
  InventoryFilterAgents: /* csgo_indonesian.txt */"Agen",
  InventoryFilterAll: /* csgo_indonesian.txt */"Semua",
  InventoryFilterAllEquipment: /* csgo_indonesian.txt */"Semua Peralatan",
  InventoryFilterAllGraphicArt: /* csgo_indonesian.txt */"Semua Seni Grafis",
  InventoryFilterAlphabetical: /* csgo_indonesian.txt */"Alfabetis",
  InventoryFilterCollection: /* csgo_indonesian.txt */"Koleksi",
  InventoryFilterContainers: /* csgo_indonesian.txt */"KONTAINER",
  InventoryFilterDisplay: /* csgo_indonesian.txt */"TAMPILAN",
  InventoryFilterEquipment: /* csgo_indonesian.txt */"PERALATAN",
  InventoryFilterEquipped: /* csgo_indonesian.txt */"Terpasang",
  InventoryFilterEverything: /* csgo_indonesian.txt */"SEMUA",
  InventoryFilterGloves: /* csgo_indonesian.txt */"Sarung Tangan",
  InventoryFilterGraffiti: /* csgo_indonesian.txt */"Grafiti",
  InventoryFilterGraffitiBoxes: /* csgo_indonesian.txt */"Kotak Grafiti",
  InventoryFilterGraphicArt: /* csgo_indonesian.txt */"SENI GRAFIS",
  InventoryFilterMedals: /* csgo_indonesian.txt */"Medali",
  InventoryFilterMelee: /* csgo_indonesian.txt */"Melee",
  InventoryFilterMidTier: /* csgo_indonesian.txt */"Tingkat Menengah",
  InventoryFilterMisc: /* csgo_indonesian.txt */"Lainnya",
  InventoryFilterMusicKits: /* csgo_indonesian.txt */"Kit Musik",
  InventoryFilterNewest: /* csgo_indonesian.txt */"Terbaru",
  InventoryFilterPatches: /* csgo_indonesian.txt */"Patch",
  InventoryFilterPistols: /* csgo_indonesian.txt */"Pistol",
  InventoryFilterQuality: /* csgo_indonesian.txt */"Kualitas",
  InventoryFilterRifles: /* csgo_indonesian.txt */"Rifle",
  InventoryFilterSearch: /* csgo_indonesian.txt */"Ketik pencarian di sini",
  InventoryFilterSouvenirCases: /* csgo_indonesian.txt */"Peti Suvenir",
  InventoryFilterStickerCapsules: /* csgo_indonesian.txt */"Kapsul Stiker",
  InventoryFilterStickers: /* csgo_indonesian.txt */"Stiker",
  InventoryFilterTools: /* csgo_indonesian.txt */"Alat",
  InventoryFilterType: /* csgo_indonesian.txt */"Jenis",
  InventoryFilterWeaponCases: /* csgo_indonesian.txt */"Peti Senjata",
  InventoryItemContainsOne: /* csgo_indonesian.txt */"Berisi salah satu dari item berikut:",
  InventoryItemDelete: /* csgo_indonesian.txt */"Hapus",
  InventoryItemEdit: /* csgo_indonesian.txt */"Edit",
  InventoryItemEquip: /* csgo_indonesian.txt */"Pasang",
  InventoryItemExterior: /* csgo_indonesian.txt */"Eksterior:",
  InventoryItemInspect: /* csgo_indonesian.txt */"Periksa",
  InventoryItemInspectFinishCatalog: /* csgo_indonesian.txt */"Katalog Skin",
  InventoryItemInspectInGame: /* csgo_indonesian.txt */"Periksa di Dalam Game...",
  InventoryItemInspectPatternTemplate: /* csgo_indonesian.txt */"Templat Pola",
  InventoryItemInspectWearRating: /* csgo_indonesian.txt */"Tingkat Keusangan",
  InventoryItemMVPStatTrakCount: /* csgo_indonesian.txt */"MVP Kompetitif Resmi StatTrak™:",
  InventoryItemNew: /* csgo_indonesian.txt */"Baru!",
  InventoryItemRareItem: /* csgo_indonesian.txt */"atau Item Spesial yang Sangat Langka!",
  InventoryItemRarity: /* csgo_indonesian.txt */"Kelangkaan:",
  InventoryItemRemovePatch: /* csgo_indonesian.txt */"Lepas Patch",
  InventoryItemRename: /* csgo_indonesian.txt */"Ganti nama",
  InventoryItemRenameStorageUnit: /* csgo_indonesian.txt */"Ganti Label",
  InventoryItemScrapeSticker: /* csgo_indonesian.txt */"Kikis Stiker",
  InventoryItemStatTrak: /* csgo_indonesian.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_indonesian.txt */"Kill Terkonfirmasi StatTrak™:",
  InventoryItemStatTrakDesc: /* csgo_indonesian.txt */"Item ini memiliki fitur teknologi StatTrak™ yang bisa melacak statistik tertentu ketika digunakan.",
  InventoryItemStorageUnitDeposit: /* csgo_indonesian.txt */"Setor Item",
  InventoryItemStorageUnitEmptyBody: /* csgo_indonesian.txt */"Unit Penyimpanan memungkinkanmu untuk menyimpan hingga {1} item yang tidak muat lagi disimpan di dalam Inventaris. Saat ini, Unit Penyimpanan yang dipilih kosong. Kamu bisa memindahkan item dari inventaris ke Unit Penyimpanan dan sebaliknya kapan saja, atau kamu bisa menggunakannya untuk sekadar mengatur item koleksimu.",
  InventoryItemStorageUnitEmptyClose: /* csgo_indonesian.txt */"OK",
  InventoryItemStorageUnitEmptyTitle: /* csgo_indonesian.txt */"Unit Penyimpanan Kosong",
  InventoryItemStorageUnitInspect: /* csgo_indonesian.txt */"Periksa",
  InventoryItemStorageUnitRetrieve: /* csgo_indonesian.txt */"Ambil Item",
  InventoryItemSwapStatTrak: /* csgo_indonesian.txt */"Buka Alat Tukar StatTrak™",
  InventoryItemTeam: /* csgo_indonesian.txt */"Tim:",
  InventoryItemTeamAny: /* csgo_indonesian.txt */"Umum",
  InventoryItemTeamCT: /* csgo_indonesian.txt */"Anti-Teroris",
  InventoryItemTeamT: /* csgo_indonesian.txt */"Teroris",
  InventoryItemUnequip: /* csgo_indonesian.txt */"Lepas",
  InventoryItemUnlockContainer: /* csgo_indonesian.txt */"Buka Kontainer",
  InventoryItemUseStorageUnit: /* csgo_indonesian.txt */"Mulai Gunakan Unit Ini",
  InventorySelectAnItem: /* csgo_indonesian.txt */"Pilih item yang akan digunakan bersamaan:",
  InventorySelectInspectContents: /* csgo_indonesian.txt */"Memeriksa isi dari",
  InventorySelectItemToDeposit: /* csgo_indonesian.txt */"Pilih item untuk dipindahkan",
  InventorySelectItemToRetrieve: /* csgo_indonesian.txt */"Pilih item untuk diambil",
  ItemRarityAncient: /* csgo_indonesian.txt */"Fantastis",
  ItemRarityCommon: /* csgo_indonesian.txt */"Kualitas Biasa",
  ItemRarityDefault: /* csgo_indonesian.txt */"Default",
  ItemRarityImmortal: /* csgo_indonesian.txt */"Ilegal",
  ItemRarityLegendary: /* csgo_indonesian.txt */"Eksotis",
  ItemRarityMythical: /* csgo_indonesian.txt */"Istimewa",
  ItemRarityNameAgent: /* csgo_indonesian.txt */"Agen",
  ItemRarityNameCollectible: /* csgo_indonesian.txt */"Item Koleksi",
  ItemRarityNameContainer: /* csgo_indonesian.txt */"Kontainer",
  ItemRarityNameContract: /* csgo_indonesian.txt */"Kontrak",
  ItemRarityNameEquipment: /* csgo_indonesian.txt */"Peralatan",
  ItemRarityNameGloves: /* csgo_indonesian.txt */"Sarung Tangan",
  ItemRarityNameGraffiti: /* csgo_indonesian.txt */"Grafiti",
  ItemRarityNameKey: /* csgo_indonesian.txt */"Kunci",
  ItemRarityNameKnife: /* csgo_indonesian.txt */"Pisau",
  ItemRarityNameMachinegun: /* csgo_indonesian.txt */"Machinegun",
  ItemRarityNameMusicKit: /* csgo_indonesian.txt */"Kit Musik",
  ItemRarityNamePatch: /* csgo_indonesian.txt */"Patch",
  ItemRarityNamePistol: /* csgo_indonesian.txt */"Pistol",
  ItemRarityNameRifle: /* csgo_indonesian.txt */"Rifle",
  ItemRarityNameSMG: /* csgo_indonesian.txt */"SMG",
  ItemRarityNameShotgun: /* csgo_indonesian.txt */"Shotgun",
  ItemRarityNameSniperRifle: /* csgo_indonesian.txt */"Sniper Rifle",
  ItemRarityNameSticker: /* csgo_indonesian.txt */"Stiker",
  ItemRarityNameTool: /* csgo_indonesian.txt */"Alat",
  ItemRarityRare: /* csgo_indonesian.txt */"Kualitas Tinggi",
  ItemRarityUncommon: /* csgo_indonesian.txt */"Kualitas Menengah",
  ItemSwapStatTrakAccept: /* csgo_indonesian.txt */"TERIMA",
  ItemSwapStatTrakClose: /* csgo_indonesian.txt */"Tutup",
  ItemSwapStatTrakDesc: /* csgo_indonesian.txt */"Item ini menukar nilai StatTrak™ antara dua jenis item yang sama.",
  ItemSwapStatTrakUse: /* csgo_indonesian.txt */"Alat Tukar StatTrak™",
  ItemSwapStatTrakWarn: /* csgo_indonesian.txt */"Alat Tukar StatTrak™ ini hanya dapat digunakan sekali",
  ItemWeaponRarityAncient: /* csgo_indonesian.txt */"Tersembunyi",
  ItemWeaponRarityCommon: /* csgo_indonesian.txt */"Kelas Konsumen",
  ItemWeaponRarityDefault: /* csgo_indonesian.txt */"Stok",
  ItemWeaponRarityImmortal: /* csgo_indonesian.txt */"Ilegal",
  ItemWeaponRarityLegendary: /* csgo_indonesian.txt */"Rahasia",
  ItemWeaponRarityMythical: /* csgo_indonesian.txt */"Terbatas",
  ItemWeaponRarityRare: /* csgo_indonesian.txt */"Kelas Militer",
  ItemWeaponRarityUncommon: /* csgo_indonesian.txt */"Kelas Industri",
  ItemWearBS: /* csgo_indonesian.txt */"Usang",
  ItemWearFN: /* csgo_indonesian.txt */"Baru",
  ItemWearFT: /* csgo_indonesian.txt */"Setengah Pakai",
  ItemWearMW: /* csgo_indonesian.txt */"Seperti Baru",
  ItemWearWW: /* csgo_indonesian.txt */"Sering Digunakan",
  RemovePatchRemove: /* csgo_indonesian.txt */"Lepas Patch",
  RemovePatchRemoveDesc: /* csgo_indonesian.txt */"Harap konfirmasikan bahwa kamu ingin melepas patch ini dari agent. Patch yang dilepas akan dihancurkan.",
  RemovePatchUse: /* csgo_indonesian.txt */"Lepas Patch",
  RemovePatchWarn: /* csgo_indonesian.txt */"Lepas patch dari",
  RenameCancel: /* csgo_indonesian.txt */"Batal",
  RenameEnterName: /* csgo_indonesian.txt */"Masukkan nama baru untuk:",
  RenameRename: /* csgo_indonesian.txt */"Ganti nama",
  RenameStorageUnitClose: /* csgo_indonesian.txt */"Tutup",
  RenameStorageUnitEnterName: /* csgo_indonesian.txt */"Masukkan nama baru untuk:",
  RenameStorageUnitFirstNameWarn: /* csgo_indonesian.txt */"Masukkan label deskripsi untuk untuk Unit Penyimpanan pribadimu dan mulai simpan item-item milikmu.",
  RenameStorageUnitNewNameWarn: /* csgo_indonesian.txt */"Masukkan label deskripsi baru untuk Unit Penyimpanan ini.",
  RenameStorageUnitRename: /* csgo_indonesian.txt */"Personalisasi",
  RenameStorageUnitUse: /* csgo_indonesian.txt */"Atur Unit Penyimpananmu",
  RenameUse: /* csgo_indonesian.txt */"Gunakan Tag Nama",
  RenameWarn: /* csgo_indonesian.txt */"Tag Nama hanya bisa digunakan satu kali",
  ScrapeStickerCancel: /* csgo_indonesian.txt */"Batal",
  ScrapeStickerClose: /* csgo_indonesian.txt */"Tutup",
  ScrapeStickerRemove: /* csgo_indonesian.txt */"Lepas Stiker",
  ScrapeStickerRemoveDesc: /* csgo_indonesian.txt */"Mengikis stiker lebih dari ini akan membuat stiker terlepas dari item, dan stiker akan dihancurkan.",
  ScrapeStickerUse: /* csgo_indonesian.txt */"Kikis Stiker",
  ScrapeStickerWarn: /* csgo_indonesian.txt */"Kikis stiker dari",
  StickerPickerRemove: /* csgo_indonesian.txt */"Hapus"
};
