/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const italian = {
  ...english,
  ApplyPatchUse: /* csgo_italian.txt */"Applica toppa",
  ApplyPatchWarn: /* csgo_italian.txt */"La toppa può essere applicata una sola volta",
  ApplyStickerCancel: /* csgo_italian.txt */"Annulla",
  ApplyStickerUse: /* csgo_italian.txt */"Applica adesivo",
  ApplyStickerUseOn: /* csgo_italian.txt */"Usa su",
  ApplyStickerWarn: /* csgo_italian.txt */"L'adesivo può essere applicato una sola volta",
  CaseAdd: /* csgo_italian.txt */"Aggiungi",
  CaseClose: /* csgo_italian.txt */"Chiudi",
  CaseContainsOne: /* csgo_italian.txt */"Contiene uno dei seguenti oggetti:",
  CaseNeed: /* csgo_italian.txt */"Questa azione richiede:",
  CaseOnceWarn: /* csgo_italian.txt */"Questa cassa può essere aperta una volta sola",
  CaseRareItem: /* csgo_italian.txt */"★ Oggetto speciale raro ★",
  CaseUnlock: /* csgo_italian.txt */"Sblocca",
  CaseUnlockContainer: /* csgo_italian.txt */"Sblocca la cassa",
  CaseUse: /* csgo_italian.txt */"Usa",
  CategoryAgent: /* csgo_italian.txt */"Agente",
  CategoryCase: /* csgo_italian.txt */"Cassa",
  CategoryCollectible: /* csgo_italian.txt */"Oggetto collezionabile",
  CategoryEquipment: /* csgo_italian.txt */"Equipaggiamento",
  CategoryGlove: /* csgo_italian.txt */"Guanti",
  CategoryGraffiti: /* csgo_italian.txt */"Graffiti",
  CategoryHeavy: /* csgo_italian.txt */"Armi pesanti",
  CategoryKey: /* csgo_italian.txt */"Chiave",
  CategoryKeychain: /* csgo_italian.txt */"Ciondolo",
  CategoryKnife: /* csgo_italian.txt */"Coltello",
  CategoryMusicKit: /* csgo_italian.txt */"Tema musicale",
  CategoryPatch: /* csgo_italian.txt */"Toppa",
  CategoryPistol: /* csgo_italian.txt */"Pistola",
  CategoryRifle: /* csgo_italian.txt */"Fucile",
  CategorySMG: /* csgo_italian.txt */"Mitra",
  CategorySticker: /* csgo_italian.txt */"Adesivo",
  CategoryTool: /* csgo_italian.txt */"Strumento",
  EditorCancel: /* csgo_italian.txt */"Annulla",
  EditorConfirmPick: /* csgo_italian.txt */"Conferma il pronostico",
  EditorNametag: /* csgo_italian.txt */"Targhetta nome",
  EditorPatches: /* csgo_italian.txt */"Toppe",
  EditorPick: /* csgo_italian.txt */"Scegli",
  EditorQuantity: /* csgo_italian.txt */"Quantità",
  EditorRandom: /* csgo_italian.txt */"Casuale",
  EditorReset: /* csgo_italian.txt */"Ripristina",
  EditorSave: /* csgo_italian.txt */"Salva",
  EditorSeed: /* csgo_italian.txt */"Motivo",
  EditorStatTrak: /* csgo_italian.txt */"StatTrak™",
  EditorStickers: /* csgo_italian.txt */"Adesivi",
  EditorWear: /* csgo_italian.txt */"Condizioni",
  GenericCancel: /* csgo_italian.txt */"Annulla",
  GenericNo: /* csgo_italian.txt */"No",
  GenericYes: /* csgo_italian.txt */"Sì",
  InspectClose: /* csgo_italian.txt */"Chiudi",
  InventoryApplyPatch: /* csgo_italian.txt */"Applica toppa",
  InventoryApplySticker: /* csgo_italian.txt */"Applica adesivo",
  InventoryFilterAgents: /* csgo_italian.txt */"Agenti",
  InventoryFilterAll: /* csgo_italian.txt */"Tutti",
  InventoryFilterAllEquipment: /* csgo_italian.txt */"Tutti gli equipaggiamenti",
  InventoryFilterAllGraphicArt: /* csgo_italian.txt */"Tutti gli oggetti di arte grafica",
  InventoryFilterAlphabetical: /* csgo_italian.txt */"Ordine alfabetico",
  InventoryFilterCharms: /* csgo_italian.txt */"Ciondoli",
  InventoryFilterCollection: /* csgo_italian.txt */"Collezione",
  InventoryFilterContainers: /* csgo_italian.txt */"CASSE",
  InventoryFilterDisplay: /* csgo_italian.txt */"ESPOSIZIONE",
  InventoryFilterEquipment: /* csgo_italian.txt */"EQUIPAGGIAMENTO",
  InventoryFilterEquipped: /* csgo_italian.txt */"Equipaggiati",
  InventoryFilterEverything: /* csgo_italian.txt */"TUTTO",
  InventoryFilterGloves: /* csgo_italian.txt */"Guanti",
  InventoryFilterGraffiti: /* csgo_italian.txt */"Graffiti",
  InventoryFilterGraffitiBoxes: /* csgo_italian.txt */"Casse di graffiti",
  InventoryFilterGraphicArt: /* csgo_italian.txt */"ARTE GRAFICA",
  InventoryFilterMedals: /* csgo_italian.txt */"Medaglie",
  InventoryFilterMelee: /* csgo_italian.txt */"Da mischia",
  InventoryFilterMidTier: /* csgo_italian.txt */"Gamma media",
  InventoryFilterMisc: /* csgo_italian.txt */"Varie",
  InventoryFilterMusicKits: /* csgo_italian.txt */"Temi musicali",
  InventoryFilterNewest: /* csgo_italian.txt */"Più recenti",
  InventoryFilterPatches: /* csgo_italian.txt */"Toppe",
  InventoryFilterPistols: /* csgo_italian.txt */"Pistole",
  InventoryFilterQuality: /* csgo_italian.txt */"Qualità",
  InventoryFilterRifles: /* csgo_italian.txt */"Fucili",
  InventoryFilterSearch: /* csgo_italian.txt */"Cerca...",
  InventoryFilterSouvenirCases: /* csgo_italian.txt */"Casse di souvenir",
  InventoryFilterStickerCapsules: /* csgo_italian.txt */"Capsule di adesivi",
  InventoryFilterStickers: /* csgo_italian.txt */"Adesivi",
  InventoryFilterTools: /* csgo_italian.txt */"Strumenti",
  InventoryFilterType: /* csgo_italian.txt */"Tipo",
  InventoryFilterWeaponCases: /* csgo_italian.txt */"Casse di armi",
  InventoryItemContainsOne: /* csgo_italian.txt */"Contiene uno dei seguenti oggetti:",
  InventoryItemDelete: /* csgo_italian.txt */"Elimina",
  InventoryItemDeleteConfirm: /* csgo_italian.txt */"Elimina oggetto",
  InventoryItemDeleteConfirmDesc: /* csgo_italian.txt */"Vuoi davvero eliminare questo oggetto?",
  InventoryItemEdit: /* csgo_italian.txt */"Modifica",
  InventoryItemEquip: /* csgo_italian.txt */"Equipaggia",
  InventoryItemExterior: /* csgo_italian.txt */"Condizioni:",
  InventoryItemInspect: /* csgo_italian.txt */"Esamina",
  InventoryItemInspectFinishCatalog: /* csgo_italian.txt */"ID della skin",
  InventoryItemInspectInGame: /* csgo_italian.txt */"Esamina in gioco...",
  InventoryItemInspectPatternTemplate: /* csgo_italian.txt */"Modello del motivo",
  InventoryItemInspectWearRating: /* csgo_italian.txt */"Tasso di usura",
  InventoryItemMVPStatTrakCount: /* csgo_italian.txt */"MVP nelle partite Competitive StatTrak™:",
  InventoryItemNew: /* csgo_italian.txt */"Novità!",
  InventoryItemRareItem: /* csgo_italian.txt */"o un oggetto speciale eccezionalmente raro!",
  InventoryItemRarity: /* csgo_italian.txt */"Rarità:",
  InventoryItemRemovePatch: /* csgo_italian.txt */"Rimuovi toppa",
  InventoryItemRename: /* csgo_italian.txt */"Rinomina",
  InventoryItemRenameClearTooltip: /* csgo_italian.txt */"Ricomincia.",
  InventoryItemRenameInvalidTooltip: /* csgo_italian.txt */"Inserisci un nome valido.",
  InventoryItemRenamePlaceholder: /* csgo_italian.txt */"Nuovo nome",
  InventoryItemRenameStorageUnit: /* csgo_italian.txt */"Cambia etichetta",
  InventoryItemScrapeSticker: /* csgo_italian.txt */"Raschia adesivo",
  InventoryItemStatTrak: /* csgo_italian.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_italian.txt */"Uccisioni confermate da StatTrak™:",
  InventoryItemStatTrakDesc: /* csgo_italian.txt */"Questo oggetto include la tecnologia StatTrak™, che tiene traccia di alcune statistiche mentre viene impugnato dal proprietario.",
  InventoryItemStorageUnitDeposit: /* csgo_italian.txt */"Deposita oggetti",
  InventoryItemStorageUnitEmptyBody: /* csgo_italian.txt */"Questo magazzino ti permette di depositare fino a {1} dei tuoi oggetti in eccesso che altrimenti supererebbero il limite dell'inventario. Il magazzino selezionato è vuoto. In qualunque momento puoi spostare gli oggetti dal tuo inventario a questo magazzino, riportarli nell'inventario oppure usarlo solo per organizzare la tua collezione di oggetti.",
  InventoryItemStorageUnitEmptyClose: /* csgo_italian.txt */"OK",
  InventoryItemStorageUnitEmptyTitle: /* csgo_italian.txt */"Magazzino vuoto",
  InventoryItemStorageUnitInspect: /* csgo_italian.txt */"Esamina",
  InventoryItemStorageUnitRetrieve: /* csgo_italian.txt */"Recupera oggetti",
  InventoryItemSwapStatTrak: /* csgo_italian.txt */"Apri lo Scambiatore StatTrak™",
  InventoryItemTeam: /* csgo_italian.txt */"Squadra:",
  InventoryItemTeamAny: /* csgo_italian.txt */"Tutte",
  InventoryItemTeamCT: /* csgo_italian.txt */"Anti-Terrorista",
  InventoryItemTeamT: /* csgo_italian.txt */"Terrorista",
  InventoryItemUnequip: /* csgo_italian.txt */"Rimuovi",
  InventoryItemUnlockContainer: /* csgo_italian.txt */"Sblocca la cassa",
  InventoryItemUseStorageUnit: /* csgo_italian.txt */"Inizia ad usare questa unità",
  InventorySelectAnItem: /* csgo_italian.txt */"Seleziona un oggetto da usare con:",
  InventorySelectInspectContents: /* csgo_italian.txt */"Ispezione dei contenuti di",
  InventorySelectItemToDeposit: /* csgo_italian.txt */"Seleziona gli oggetti da spostare",
  InventorySelectItemToRetrieve: /* csgo_italian.txt */"Seleziona gli oggetti da recuperare dal",
  ItemRarityAncient: /* csgo_italian.txt */"Straordinario",
  ItemRarityCommon: /* csgo_italian.txt */"Qualità base",
  ItemRarityDefault: /* csgo_italian.txt */"Predefinito",
  ItemRarityImmortal: /* csgo_italian.txt */"Di contrabbando",
  ItemRarityLegendary: /* csgo_italian.txt */"Esotico",
  ItemRarityMythical: /* csgo_italian.txt */"Rimarchevole",
  ItemRarityNameAgent: /* csgo_italian.txt */"Agente",
  ItemRarityNameCharm: /* csgo_italian.txt */"Ciondolo",
  ItemRarityNameCollectible: /* csgo_italian.txt */"Oggetto collezionabile",
  ItemRarityNameContainer: /* csgo_italian.txt */"Cassa",
  ItemRarityNameContract: /* csgo_italian.txt */"Contratto",
  ItemRarityNameEquipment: /* csgo_italian.txt */"Equipaggiamento",
  ItemRarityNameGloves: /* csgo_italian.txt */"Guanti",
  ItemRarityNameGraffiti: /* csgo_italian.txt */"Graffiti",
  ItemRarityNameKey: /* csgo_italian.txt */"Chiave",
  ItemRarityNameKnife: /* csgo_italian.txt */"Coltello",
  ItemRarityNameMachinegun: /* csgo_italian.txt */"Mitragliatrice",
  ItemRarityNameMusicKit: /* csgo_italian.txt */"Tema musicale",
  ItemRarityNamePatch: /* csgo_italian.txt */"Toppa",
  ItemRarityNamePistol: /* csgo_italian.txt */"Pistola",
  ItemRarityNameRifle: /* csgo_italian.txt */"Fucile",
  ItemRarityNameSMG: /* csgo_italian.txt */"Mitra",
  ItemRarityNameShotgun: /* csgo_italian.txt */"Fucile a pompa",
  ItemRarityNameSniperRifle: /* csgo_italian.txt */"Fucile di precisione",
  ItemRarityNameSticker: /* csgo_italian.txt */"Adesivo",
  ItemRarityNameTool: /* csgo_italian.txt */"Strumento",
  ItemRarityRare: /* csgo_italian.txt */"Qualità elevata",
  ItemRarityUncommon: /* csgo_italian.txt */"Qualità media",
  ItemSwapStatTrakAccept: /* csgo_italian.txt */"ACCETTA",
  ItemSwapStatTrakClose: /* csgo_italian.txt */"Chiudi",
  ItemSwapStatTrakDesc: /* csgo_italian.txt */"Questo oggetto scambia i valori dei contatori StatTrak™ di due oggetti dello stesso tipo.",
  ItemSwapStatTrakUse: /* csgo_italian.txt */"Scambiatore StatTrak™",
  ItemSwapStatTrakWarn: /* csgo_italian.txt */"Questo Scambiatore StatTrak™ può essere usato una volta sola",
  ItemWeaponRarityAncient: /* csgo_italian.txt */"Segreto",
  ItemWeaponRarityCommon: /* csgo_italian.txt */"Amatoriale",
  ItemWeaponRarityDefault: /* csgo_italian.txt */"Predefinito",
  ItemWeaponRarityImmortal: /* csgo_italian.txt */"Di contrabbando",
  ItemWeaponRarityLegendary: /* csgo_italian.txt */"Confidenziale",
  ItemWeaponRarityMythical: /* csgo_italian.txt */"Riservato",
  ItemWeaponRarityRare: /* csgo_italian.txt */"Militare",
  ItemWeaponRarityUncommon: /* csgo_italian.txt */"Industriale",
  ItemWearBS: /* csgo_italian.txt */"Segnato dalle battaglie",
  ItemWearFN: /* csgo_italian.txt */"Nuovo di fabbrica",
  ItemWearFT: /* csgo_italian.txt */"Testato sul campo",
  ItemWearMW: /* csgo_italian.txt */"Usura minima",
  ItemWearWW: /* csgo_italian.txt */"Consumato",
  RemovePatchRemove: /* csgo_italian.txt */"Rimuovi toppa",
  RemovePatchRemoveDesc: /* csgo_italian.txt */"Conferma di voler rimuovere la toppa dal tuo agente. La toppa rimossa verrà distrutta.",
  RemovePatchUse: /* csgo_italian.txt */"Rimuovi toppa",
  RemovePatchWarn: /* csgo_italian.txt */"Rimuovi una toppa da",
  RenameCancel: /* csgo_italian.txt */"Annulla",
  RenameEnterName: /* csgo_italian.txt */"Inserisci un nuovo nome per:",
  RenameRename: /* csgo_italian.txt */"Rinomina",
  RenameStorageUnitClose: /* csgo_italian.txt */"Chiudi",
  RenameStorageUnitEnterName: /* csgo_italian.txt */"Inserisci un nuovo nome per:",
  RenameStorageUnitFirstNameWarn: /* csgo_italian.txt */"Inserisci una descrizione per il tuo magazzino e inizia a usarlo per depositare i tuoi oggetti.",
  RenameStorageUnitNewNameWarn: /* csgo_italian.txt */"Inserisci una descrizione per questo magazzino.",
  RenameStorageUnitRename: /* csgo_italian.txt */"Personalizza",
  RenameStorageUnitUse: /* csgo_italian.txt */"Personalizza il tuo magazzino",
  RenameUse: /* csgo_italian.txt */"Usa la Targhetta nome",
  RenameWarn: /* csgo_italian.txt */"Le Targhette Nome possono essere usate solo una volta",
  ScrapeStickerCancel: /* csgo_italian.txt */"Annulla",
  ScrapeStickerClose: /* csgo_italian.txt */"Chiudi",
  ScrapeStickerRemove: /* csgo_italian.txt */"Rimuovi adesivo",
  ScrapeStickerRemoveDesc: /* csgo_italian.txt */"Raschiare ulteriormente questo adesivo lo rimuoverà dall'oggetto e verrà distrutto.",
  ScrapeStickerUse: /* csgo_italian.txt */"Raschia adesivo",
  ScrapeStickerWarn: /* csgo_italian.txt */"Raschia un adesivo da",
  SettingsMasterVolume: /* csgo_italian.txt */"Volume principale",
  StickerPickerRemove: /* csgo_italian.txt */"Rimuovi"
};
