/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const koreana = {
  ...english,
  ApplyPatchUse: /* csgo_koreana.txt */"패치 부착",
  ApplyPatchWarn: /* csgo_koreana.txt */"패치는 한 번만 사용할 수 있습니다.",
  ApplyStickerCancel: /* csgo_koreana.txt */"취소",
  ApplyStickerUse: /* csgo_koreana.txt */"스티커 부착",
  ApplyStickerUseOn: /* csgo_koreana.txt */"에 사용",
  ApplyStickerWarn: /* csgo_koreana.txt */"스티커는 한 번만 붙일 수 있습니다",
  CaseAdd: /* csgo_koreana.txt */"추가",
  CaseClose: /* csgo_koreana.txt */"닫기",
  CaseContainsOne: /* csgo_koreana.txt */"다음 중 하나가 들어 있습니다.",
  CaseNeed: /* csgo_koreana.txt */"이 작업을 수행하려면 가 필요합니다.",
  CaseOnceWarn: /* csgo_koreana.txt */"이 아이템은 한 번만 열 수 있습니다",
  CaseRareItem: /* csgo_koreana.txt */"★ 특별하고 희귀한 아이템 ★",
  CaseUnlock: /* csgo_koreana.txt */"",
  CaseUnlockContainer: /* csgo_koreana.txt */"상자 열기",
  CaseUse: /* csgo_koreana.txt */"사용하기",
  CategoryAgent: /* csgo_koreana.txt */"요원",
  CategoryCase: /* csgo_koreana.txt */"상자",
  CategoryCollectible: /* csgo_koreana.txt */"수집품",
  CategoryEquipment: /* csgo_koreana.txt */"장비",
  CategoryGlove: /* csgo_koreana.txt */"장갑",
  CategoryGraffiti: /* csgo_koreana.txt */"그래피티",
  CategoryHeavy: /* csgo_koreana.txt */"중화기",
  CategoryKey: /* csgo_koreana.txt */"키",
  CategoryKnife: /* csgo_koreana.txt */"칼",
  CategoryMusicKit: /* csgo_koreana.txt */"음악 키트",
  CategoryPatch: /* csgo_koreana.txt */"패치",
  CategoryPistol: /* csgo_koreana.txt */"권총",
  CategoryRifle: /* csgo_koreana.txt */"소총",
  CategorySMG: /* csgo_koreana.txt */"기관단총",
  CategorySticker: /* csgo_koreana.txt */"스티커",
  CategoryTool: /* csgo_koreana.txt */"도구",
  EditorCancel: /* csgo_koreana.txt */"취소",
  EditorNametag: /* csgo_koreana.txt */"이름표",
  EditorPatches: /* csgo_koreana.txt */"패치",
  EditorQuantity: /* csgo_koreana.txt */"수량",
  EditorRandom: /* csgo_koreana.txt */"무작위",
  EditorReset: /* csgo_koreana.txt */"초기화",
  EditorSave: /* csgo_koreana.txt */"저장",
  EditorSeed: /* csgo_koreana.txt */"패턴",
  EditorStatTrak: /* csgo_koreana.txt */"StatTrak™",
  EditorStickers: /* csgo_koreana.txt */"스티커",
  EditorWear: /* csgo_koreana.txt */"형태",
  InspectClose: /* csgo_koreana.txt */"닫기",
  InventoryApplyPatch: /* csgo_koreana.txt */"패치 부착",
  InventoryApplySticker: /* csgo_koreana.txt */"스티커 붙이기",
  InventoryFilterAgents: /* csgo_koreana.txt */"요원",
  InventoryFilterAll: /* csgo_koreana.txt */"전체",
  InventoryFilterAllEquipment: /* csgo_koreana.txt */"모든 장비",
  InventoryFilterAllGraphicArt: /* csgo_koreana.txt */"모든 그래픽 아트",
  InventoryFilterAlphabetical: /* csgo_koreana.txt */"가나다순",
  InventoryFilterCollection: /* csgo_koreana.txt */"수집품",
  InventoryFilterContainers: /* csgo_koreana.txt */"상자",
  InventoryFilterDisplay: /* csgo_koreana.txt */"장식",
  InventoryFilterEquipment: /* csgo_koreana.txt */"장비",
  InventoryFilterEquipped: /* csgo_koreana.txt */"장착한 아이템",
  InventoryFilterEverything: /* csgo_koreana.txt */"전체",
  InventoryFilterGloves: /* csgo_koreana.txt */"장갑",
  InventoryFilterGraffiti: /* csgo_koreana.txt */"그래피티",
  InventoryFilterGraffitiBoxes: /* csgo_koreana.txt */"그래피티 상자",
  InventoryFilterGraphicArt: /* csgo_koreana.txt */"그래픽 아트",
  InventoryFilterMedals: /* csgo_koreana.txt */"훈장",
  InventoryFilterMelee: /* csgo_koreana.txt */"근접무기",
  InventoryFilterMidTier: /* csgo_koreana.txt */"중위 티어",
  InventoryFilterMisc: /* csgo_koreana.txt */"기타",
  InventoryFilterMusicKits: /* csgo_koreana.txt */"음악 키트",
  InventoryFilterNewest: /* csgo_koreana.txt */"최신",
  InventoryFilterPatches: /* csgo_koreana.txt */"패치",
  InventoryFilterPistols: /* csgo_koreana.txt */"권총",
  InventoryFilterQuality: /* csgo_koreana.txt */"품질",
  InventoryFilterRifles: /* csgo_koreana.txt */"소총",
  InventoryFilterSearch: /* csgo_koreana.txt */"검색어를 입력하세요",
  InventoryFilterSouvenirCases: /* csgo_koreana.txt */"기념품 상자",
  InventoryFilterStickerCapsules: /* csgo_koreana.txt */"스티커 캡슐",
  InventoryFilterStickers: /* csgo_koreana.txt */"스티커",
  InventoryFilterTools: /* csgo_koreana.txt */"도구",
  InventoryFilterType: /* csgo_koreana.txt */"유형",
  InventoryFilterWeaponCases: /* csgo_koreana.txt */"무기 상자",
  InventoryItemContainsOne: /* csgo_koreana.txt */"다음 중 하나가 들어 있습니다.",
  InventoryItemDelete: /* csgo_koreana.txt */"삭제",
  InventoryItemEdit: /* csgo_koreana.txt */"편집",
  InventoryItemEquip: /* csgo_koreana.txt */"장착",
  InventoryItemExterior: /* csgo_koreana.txt */"외관:",
  InventoryItemInspect: /* csgo_koreana.txt */"관찰",
  InventoryItemInspectFinishCatalog: /* csgo_koreana.txt */"도색 카탈로그 번호",
  InventoryItemInspectInGame: /* csgo_koreana.txt */"게임 내에서 관찰...",
  InventoryItemInspectPatternTemplate: /* csgo_koreana.txt */"무늬 템플릿 번호",
  InventoryItemInspectWearRating: /* csgo_koreana.txt */"닳은 정도",
  InventoryItemMVPStatTrakCount: /* csgo_koreana.txt */"StatTrak™ 공식 경쟁 매치 MVP 횟수:",
  InventoryItemNew: /* csgo_koreana.txt */"신규!",
  InventoryItemRareItem: /* csgo_koreana.txt */"또는 극도로 희귀한 아이템!",
  InventoryItemRarity: /* csgo_koreana.txt */"희귀도:",
  InventoryItemRemovePatch: /* csgo_koreana.txt */"패치 제거하기",
  InventoryItemRename: /* csgo_koreana.txt */"이름 바꾸기",
  InventoryItemRenameStorageUnit: /* csgo_koreana.txt */"이름 변경",
  InventoryItemScrapeSticker: /* csgo_koreana.txt */"스티커 긁어내기",
  InventoryItemStatTrak: /* csgo_koreana.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_koreana.txt */"StatTrak™ 인증 처치 수:",
  InventoryItemStatTrakDesc: /* csgo_koreana.txt */"이 무기는 특정 활동의 통계를 기록하는 StatTrak™ 기술을 사용합니다.",
  InventoryItemStorageUnitDeposit: /* csgo_koreana.txt */"아이템 보관하기",
  InventoryItemStorageUnitEmptyBody: /* csgo_koreana.txt */"저장 컨테이너에는 아이템을 추가로 최대 {1}개까지 보관할 수 있습니다. 지금 선택한 저장 컨테이너는 비어있습니다. 언제든지 아이템을 보관함에서 저장 컨테이너로 이동할 수 있으며 저장 컨테이너에 보관한 아이템을 보관함으로 다시 가져올 수도 있습니다. 또한 수집품을 정리하는 데 사용할 수도 있습니다.",
  InventoryItemStorageUnitEmptyClose: /* csgo_koreana.txt */"확인",
  InventoryItemStorageUnitEmptyTitle: /* csgo_koreana.txt */"저장 컨테이너 비어 있음",
  InventoryItemStorageUnitInspect: /* csgo_koreana.txt */"관찰",
  InventoryItemStorageUnitRetrieve: /* csgo_koreana.txt */"아이템 가져오기",
  InventoryItemSwapStatTrak: /* csgo_koreana.txt */"StatTrak™ 교환 도구 열기",
  InventoryItemTeam: /* csgo_koreana.txt */"팀:",
  InventoryItemTeamAny: /* csgo_koreana.txt */"전체",
  InventoryItemTeamCT: /* csgo_koreana.txt */"대테러부대",
  InventoryItemTeamT: /* csgo_koreana.txt */"테러리스트",
  InventoryItemUnequip: /* csgo_koreana.txt */"장착 해제",
  InventoryItemUnlockContainer: /* csgo_koreana.txt */"상자 열기",
  InventoryItemUseStorageUnit: /* csgo_koreana.txt */"저장 컨테이너 사용",
  InventorySelectAnItem: /* csgo_koreana.txt */"사용할 아이템 선택:",
  InventorySelectInspectContents: /* csgo_koreana.txt */"관찰 중인 저장 컨테이너:",
  InventorySelectItemToDeposit: /* csgo_koreana.txt */"다음 저장 컨테이너로 이동할 아이템 선택:",
  InventorySelectItemToRetrieve: /* csgo_koreana.txt */"다음 저장 컨테이너에서 가져올 아이템 선택:",
  ItemRarityAncient: /* csgo_koreana.txt */"희귀",
  ItemRarityCommon: /* csgo_koreana.txt */"일반",
  ItemRarityDefault: /* csgo_koreana.txt */"기본",
  ItemRarityImmortal: /* csgo_koreana.txt */"전설",
  ItemRarityLegendary: /* csgo_koreana.txt */"특급",
  ItemRarityMythical: /* csgo_koreana.txt */"최고급",
  ItemRarityNameAgent: /* csgo_koreana.txt */"요원",
  ItemRarityNameCollectible: /* csgo_koreana.txt */"수집품",
  ItemRarityNameContainer: /* csgo_koreana.txt */"상자",
  ItemRarityNameContract: /* csgo_koreana.txt */"계약",
  ItemRarityNameEquipment: /* csgo_koreana.txt */"장비",
  ItemRarityNameGloves: /* csgo_koreana.txt */"장갑",
  ItemRarityNameGraffiti: /* csgo_koreana.txt */"그래피티",
  ItemRarityNameKey: /* csgo_koreana.txt */"키",
  ItemRarityNameKnife: /* csgo_koreana.txt */"칼",
  ItemRarityNameMachinegun: /* csgo_koreana.txt */"기관총",
  ItemRarityNameMusicKit: /* csgo_koreana.txt */"음악 키트",
  ItemRarityNamePatch: /* csgo_koreana.txt */"패치",
  ItemRarityNamePistol: /* csgo_koreana.txt */"권총",
  ItemRarityNameRifle: /* csgo_koreana.txt */"소총",
  ItemRarityNameSMG: /* csgo_koreana.txt */"기관단총",
  ItemRarityNameShotgun: /* csgo_koreana.txt */"산탄총",
  ItemRarityNameSniperRifle: /* csgo_koreana.txt */"저격소총",
  ItemRarityNameSticker: /* csgo_koreana.txt */"스티커",
  ItemRarityNameTool: /* csgo_koreana.txt */"도구",
  ItemRarityRare: /* csgo_koreana.txt */"고급",
  ItemRarityUncommon: /* csgo_koreana.txt */"중급",
  ItemSwapStatTrakAccept: /* csgo_koreana.txt */"수락",
  ItemSwapStatTrakClose: /* csgo_koreana.txt */"닫기",
  ItemSwapStatTrakDesc: /* csgo_koreana.txt */"이 아이템으로 유형이 같은 두 아이템의 StatTrak™ 점수를 맞바꿀 수 있습니다.",
  ItemSwapStatTrakUse: /* csgo_koreana.txt */"StatTrak™ 교환 도구",
  ItemSwapStatTrakWarn: /* csgo_koreana.txt */"StatTrak™ 교환 도구는 한 번만 사용 가능합니다.",
  ItemWeaponRarityAncient: /* csgo_koreana.txt */"극비",
  ItemWeaponRarityCommon: /* csgo_koreana.txt */"기본",
  ItemWeaponRarityDefault: /* csgo_koreana.txt */"보급",
  ItemWeaponRarityImmortal: /* csgo_koreana.txt */"전설",
  ItemWeaponRarityLegendary: /* csgo_koreana.txt */"비밀",
  ItemWeaponRarityMythical: /* csgo_koreana.txt */"제한",
  ItemWeaponRarityRare: /* csgo_koreana.txt */"군용",
  ItemWeaponRarityUncommon: /* csgo_koreana.txt */"고급",
  ItemWearBS: /* csgo_koreana.txt */"전투로 닳고 닳은",
  ItemWearFN: /* csgo_koreana.txt */"막 출고된",
  ItemWearFT: /* csgo_koreana.txt */"현장에서 쓰인",
  ItemWearMW: /* csgo_koreana.txt */"거의 깨끗한",
  ItemWearWW: /* csgo_koreana.txt */"꽤 닳은",
  RemovePatchRemove: /* csgo_koreana.txt */"패치 제거",
  RemovePatchRemoveDesc: /* csgo_koreana.txt */"요원에 부착된 패치를 제거할 지 확인해 주세요. 한 번 제거한 패치는 복구할 수 없습니다.",
  RemovePatchUse: /* csgo_koreana.txt */"패치 제거",
  RemovePatchWarn: /* csgo_koreana.txt */"에서 패치 제거하기",
  RenameCancel: /* csgo_koreana.txt */"취소",
  RenameEnterName: /* csgo_koreana.txt */"에 새 이름을 입력하세요.",
  RenameRename: /* csgo_koreana.txt */"이름 바꾸기",
  RenameStorageUnitClose: /* csgo_koreana.txt */"닫기",
  RenameStorageUnitEnterName: /* csgo_koreana.txt */"에 새 이름을 입력하세요.",
  RenameStorageUnitFirstNameWarn: /* csgo_koreana.txt */"개인 저장 컨테이너에 내용물을 알 수 있는 이름을 입력하고 아이템 저장 용도로 사용하세요.",
  RenameStorageUnitNewNameWarn: /* csgo_koreana.txt */"이 저장 컨테이너에 대한 새로운 이름을 입력하세요.",
  RenameStorageUnitRename: /* csgo_koreana.txt */"개인 설정",
  RenameStorageUnitUse: /* csgo_koreana.txt */"저장 컨테이너 개인 설정",
  RenameUse: /* csgo_koreana.txt */"이름표 사용",
  RenameWarn: /* csgo_koreana.txt */"이름표는 한 번만 사용할 수 있습니다",
  ScrapeStickerCancel: /* csgo_koreana.txt */"취소",
  ScrapeStickerClose: /* csgo_koreana.txt */"닫기",
  ScrapeStickerRemove: /* csgo_koreana.txt */"스티커 제거",
  ScrapeStickerRemoveDesc: /* csgo_koreana.txt */"이 상태에서 스티커를 긁어내면 아이템에서 스티커가 영원히 제거됩니다.",
  ScrapeStickerUse: /* csgo_koreana.txt */"스티커 긁어내기",
  ScrapeStickerWarn: /* csgo_koreana.txt */"에서 스티커 긁어내기",
  StickerPickerRemove: /* csgo_koreana.txt */"제거"
};
