/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const latam = {
  ...english,
  ApplyPatchUse: /* csgo_latam.txt */"Aplicar parche",
  ApplyPatchWarn: /* csgo_latam.txt */"Los parches se pueden aplicar una sola vez",
  ApplyStickerCancel: /* csgo_latam.txt */"Cancelar",
  ApplyStickerUse: /* csgo_latam.txt */"Aplicar calcomanía",
  ApplyStickerUseOn: /* csgo_latam.txt */"Usar en",
  ApplyStickerWarn: /* csgo_latam.txt */"Las calcomanías se pueden aplicar una sola vez",
  CaseAdd: /* csgo_latam.txt */"Agregar",
  CaseClose: /* csgo_latam.txt */"Cerrar",
  CaseContainsOne: /* csgo_latam.txt */"Contiene uno de los siguientes objetos:",
  CaseNeed: /* csgo_latam.txt */"Esta acción requiere un/a",
  CaseOnceWarn: /* csgo_latam.txt */"Este contenedor solo se puede abrir una vez",
  CaseRareItem: /* csgo_latam.txt */"★ Objeto especial raro ★",
  CaseUnlock: /* csgo_latam.txt */"Abrir",
  CaseUnlockContainer: /* csgo_latam.txt */"Abrir contenedor",
  CaseUse: /* csgo_latam.txt */"Utilizar",
  CategoryAgent: /* csgo_latam.txt */"Agente",
  CategoryCase: /* csgo_latam.txt */"Contenedor",
  CategoryCollectible: /* csgo_latam.txt */"Coleccionable",
  CategoryEquipment: /* csgo_latam.txt */"Equipamiento",
  CategoryGlove: /* csgo_latam.txt */"Guantes",
  CategoryGraffiti: /* csgo_latam.txt */"Grafiti",
  CategoryHeavy: /* csgo_latam.txt */"Armas pesadas",
  CategoryKey: /* csgo_latam.txt */"Llave",
  CategoryKeychain: /* csgo_latam.txt */"Colgante",
  CategoryKnife: /* csgo_latam.txt */"Cuchillo",
  CategoryMusicKit: /* csgo_latam.txt */"Kit de música",
  CategoryPatch: /* csgo_latam.txt */"Parche",
  CategoryPistol: /* csgo_latam.txt */"Pistola",
  CategoryRifle: /* csgo_latam.txt */"Rifle",
  CategorySMG: /* csgo_latam.txt */"Subfusil",
  CategorySticker: /* csgo_latam.txt */"Calcomanía",
  CategoryTool: /* csgo_latam.txt */"Herramienta",
  EditorCancel: /* csgo_latam.txt */"Cancelar",
  EditorConfirmPick: /* csgo_latam.txt */"Confirmar elección",
  EditorNametag: /* csgo_latam.txt */"Etiqueta de nombre",
  EditorPatches: /* csgo_latam.txt */"Parches",
  EditorPick: /* csgo_latam.txt */"Elegir",
  EditorQuantity: /* csgo_latam.txt */"Cantidad",
  EditorRandom: /* csgo_latam.txt */"Aleatorio",
  EditorReset: /* csgo_latam.txt */"Restablecer",
  EditorSave: /* csgo_latam.txt */"Guardar",
  EditorSeed: /* csgo_latam.txt */"Patrón",
  EditorStatTrak: /* csgo_latam.txt */"StatTrak™",
  EditorStickers: /* csgo_latam.txt */"Calcomanías",
  EditorWear: /* csgo_latam.txt */"Desgaste",
  GenericCancel: /* csgo_latam.txt */"Cancelar",
  GenericNo: /* csgo_latam.txt */"No",
  GenericYes: /* csgo_latam.txt */"Sí",
  InspectClose: /* csgo_latam.txt */"Cerrar",
  InventoryApplyPatch: /* csgo_latam.txt */"Aplicar parche",
  InventoryApplySticker: /* csgo_latam.txt */"Aplicar calcomanía",
  InventoryFilterAgents: /* csgo_latam.txt */"Agentes",
  InventoryFilterAll: /* csgo_latam.txt */"Todos",
  InventoryFilterAllEquipment: /* csgo_latam.txt */"Todo el equipamiento",
  InventoryFilterAllGraphicArt: /* csgo_latam.txt */"Todo el arte gráfico",
  InventoryFilterAlphabetical: /* csgo_latam.txt */"Orden alfabético",
  InventoryFilterCharms: /* csgo_latam.txt */"Colgantes",
  InventoryFilterCollection: /* csgo_latam.txt */"Colección",
  InventoryFilterContainers: /* csgo_latam.txt */"CONTENEDORES",
  InventoryFilterDisplay: /* csgo_latam.txt */"EXHIBIDOR",
  InventoryFilterEquipment: /* csgo_latam.txt */"EQUIPAMIENTO",
  InventoryFilterEquipped: /* csgo_latam.txt */"Equipado",
  InventoryFilterEverything: /* csgo_latam.txt */"TODO",
  InventoryFilterGloves: /* csgo_latam.txt */"Guantes",
  InventoryFilterGraffiti: /* csgo_latam.txt */"Grafitis",
  InventoryFilterGraffitiBoxes: /* csgo_latam.txt */"Cajas de grafitis",
  InventoryFilterGraphicArt: /* csgo_latam.txt */"ARTE GRÁFICO",
  InventoryFilterMedals: /* csgo_latam.txt */"Medallas",
  InventoryFilterMelee: /* csgo_latam.txt */"Cuerpo a cuerpo",
  InventoryFilterMidTier: /* csgo_latam.txt */"Nivel medio",
  InventoryFilterMisc: /* csgo_latam.txt */"Varios",
  InventoryFilterMusicKits: /* csgo_latam.txt */"Kits de música",
  InventoryFilterNewest: /* csgo_latam.txt */"Más reciente",
  InventoryFilterPatches: /* csgo_latam.txt */"Parches",
  InventoryFilterPistols: /* csgo_latam.txt */"Pistolas",
  InventoryFilterQuality: /* csgo_latam.txt */"Calidad",
  InventoryFilterRifles: /* csgo_latam.txt */"Rifles",
  InventoryFilterSearch: /* csgo_latam.txt */"Escribe la búsqueda aquí",
  InventoryFilterSouvenirCases: /* csgo_latam.txt */"Paquetes de recuerdo",
  InventoryFilterStickerCapsules: /* csgo_latam.txt */"Cápsulas de calcomanías",
  InventoryFilterStickers: /* csgo_latam.txt */"Calcomanías",
  InventoryFilterTools: /* csgo_latam.txt */"Herramientas",
  InventoryFilterType: /* csgo_latam.txt */"Tipo",
  InventoryFilterWeaponCases: /* csgo_latam.txt */"Cajas de armas",
  InventoryItemContainsOne: /* csgo_latam.txt */"Contiene uno de los siguientes objetos:",
  InventoryItemDelete: /* csgo_latam.txt */"Borrar",
  InventoryItemDeleteConfirm: /* csgo_latam.txt */"Eliminar objeto",
  InventoryItemDeleteConfirmDesc: /* csgo_latam.txt */"¿Seguro que quieres eliminar este objeto?",
  InventoryItemEdit: /* csgo_latam.txt */"Modificar",
  InventoryItemEquip: /* csgo_latam.txt */"Equipar",
  InventoryItemExterior: /* csgo_latam.txt */"Exterior:",
  InventoryItemInspect: /* csgo_latam.txt */"Inspeccionar",
  InventoryItemInspectFinishCatalog: /* csgo_latam.txt */"Catálogo de acabados",
  InventoryItemInspectInGame: /* csgo_latam.txt */"Inspeccionar en el juego...",
  InventoryItemInspectPatternTemplate: /* csgo_latam.txt */"Plantilla de patrón",
  InventoryItemInspectWearRating: /* csgo_latam.txt */"Índice de desgaste",
  InventoryItemMVPStatTrakCount: /* csgo_latam.txt */"Premios al MJ en Competitivo oficial StatTrak™:",
  InventoryItemNew: /* csgo_latam.txt */"¡Nuevo!",
  InventoryItemRareItem: /* csgo_latam.txt */"¡o un objeto especial extraordinariamente raro!",
  InventoryItemRarity: /* csgo_latam.txt */"Rareza:",
  InventoryItemRemovePatch: /* csgo_latam.txt */"Quitar parche",
  InventoryItemRename: /* csgo_latam.txt */"Renombrar",
  InventoryItemRenameClearTooltip: /* csgo_latam.txt */"Empezar de nuevo.",
  InventoryItemRenameInvalidTooltip: /* csgo_latam.txt */"Introduce un nombre válido.",
  InventoryItemRenamePlaceholder: /* csgo_latam.txt */"Nuevo nombre",
  InventoryItemRenameStorageUnit: /* csgo_latam.txt */"Cambiar etiqueta",
  InventoryItemScrapeSticker: /* csgo_latam.txt */"Raspar calcomanía",
  InventoryItemStatTrak: /* csgo_latam.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_latam.txt */"Víctimas confirmadas por StatTrak™:",
  InventoryItemStatTrakDesc: /* csgo_latam.txt */"Este objeto cuenta con el dispositivo StatTrak™, el cual registra ciertas estadísticas cuando lo equipa su propietario.",
  InventoryItemStorageUnitDeposit: /* csgo_latam.txt */"Depositar objetos",
  InventoryItemStorageUnitEmptyBody: /* csgo_latam.txt */"Esta unidad de almacenamiento te permite guardar hasta {1} objetos excedentes que de otro modo superarían el límite del inventario. La unidad de almacenamiento seleccionada está vacía actualmente. En cualquier momento, puedes transferir objetos del inventario a esta unidad, devolverlos al inventario o simplemente puedes utilizarla para organizar tus colecciones.",
  InventoryItemStorageUnitEmptyClose: /* csgo_latam.txt */"Aceptar",
  InventoryItemStorageUnitEmptyTitle: /* csgo_latam.txt */"Unidad de almacenamiento vacía",
  InventoryItemStorageUnitInspect: /* csgo_latam.txt */"Inspeccionar",
  InventoryItemStorageUnitRetrieve: /* csgo_latam.txt */"Recuperar objetos",
  InventoryItemSwapStatTrak: /* csgo_latam.txt */"Abrir herramienta de intercambio de StatTrak™",
  InventoryItemTeam: /* csgo_latam.txt */"Equipo:",
  InventoryItemTeamAny: /* csgo_latam.txt */"Ambos",
  InventoryItemTeamCT: /* csgo_latam.txt */"Antiterrorista",
  InventoryItemTeamT: /* csgo_latam.txt */"Terrorista",
  InventoryItemUnequip: /* csgo_latam.txt */"Desequipar",
  InventoryItemUnlockContainer: /* csgo_latam.txt */"Abrir paquete",
  InventoryItemUseStorageUnit: /* csgo_latam.txt */"Comenzar a usar esta unidad",
  InventorySelectAnItem: /* csgo_latam.txt */"Selecciona un objeto con el que usarlo:",
  InventorySelectInspectContents: /* csgo_latam.txt */"Revisando el contenido de",
  InventorySelectItemToDeposit: /* csgo_latam.txt */"Selecciona los objetos que deseas recuperar de",
  InventorySelectItemToRetrieve: /* csgo_latam.txt */"Selecciona los objetos que deseas recuperar de",
  ItemRarityAncient: /* csgo_latam.txt */"de aspecto extraordinario",
  ItemRarityCommon: /* csgo_latam.txt */"de grado básico",
  ItemRarityDefault: /* csgo_latam.txt */"estándar",
  ItemRarityImmortal: /* csgo_latam.txt */"de contrabando",
  ItemRarityLegendary: /* csgo_latam.txt */"de aspecto exótico",
  ItemRarityMythical: /* csgo_latam.txt */"singular",
  ItemRarityNameAgent: /* csgo_latam.txt */"Agente",
  ItemRarityNameC4: /* csgo_latam.txt */"C4",
  ItemRarityNameCharm: /* csgo_latam.txt */"Colgante",
  ItemRarityNameCollectible: /* csgo_latam.txt */"Coleccionable",
  ItemRarityNameContainer: /* csgo_latam.txt */"Contenedor",
  ItemRarityNameContract: /* csgo_latam.txt */"Contrato",
  ItemRarityNameEquipment: /* csgo_latam.txt */"Equipamiento",
  ItemRarityNameGloves: /* csgo_latam.txt */"Guantes",
  ItemRarityNameGraffiti: /* csgo_latam.txt */"Grafiti",
  ItemRarityNameKey: /* csgo_latam.txt */"Llave",
  ItemRarityNameKnife: /* csgo_latam.txt */"Cuchillo",
  ItemRarityNameMachinegun: /* csgo_latam.txt */"Ametralladora",
  ItemRarityNameMusicKit: /* csgo_latam.txt */"Kit de música",
  ItemRarityNamePatch: /* csgo_latam.txt */"Parche",
  ItemRarityNamePistol: /* csgo_latam.txt */"Pistola",
  ItemRarityNameRifle: /* csgo_latam.txt */"Rifle",
  ItemRarityNameSMG: /* csgo_latam.txt */"Subfusil",
  ItemRarityNameShotgun: /* csgo_latam.txt */"Escopeta",
  ItemRarityNameSniperRifle: /* csgo_latam.txt */"Rifle de francotirador",
  ItemRarityNameSticker: /* csgo_latam.txt */"Calcomanía",
  ItemRarityNameTool: /* csgo_latam.txt */"Herramienta",
  ItemRarityRare: /* csgo_latam.txt */"de grado alto",
  ItemRarityUncommon: /* csgo_latam.txt */"de grado medio",
  ItemSwapStatTrakAccept: /* csgo_latam.txt */"ACEPTAR",
  ItemSwapStatTrakClose: /* csgo_latam.txt */"Cerrar",
  ItemSwapStatTrakDesc: /* csgo_latam.txt */"Este objeto intercambia los valores StatTrak™ entre dos objetos del mismo tipo.",
  ItemSwapStatTrakUse: /* csgo_latam.txt */"Herramienta de intercambio de StatTrak™",
  ItemSwapStatTrakWarn: /* csgo_latam.txt */"Esta herramienta de intercambio de StatTrak™ solo puede utilizarse una vez",
  ItemWeaponRarityAncient: /* csgo_latam.txt */"de aspecto encubierto",
  ItemWeaponRarityCommon: /* csgo_latam.txt */"de grado de consumidor",
  ItemWeaponRarityDefault: /* csgo_latam.txt */"común",
  ItemWeaponRarityImmortal: /* csgo_latam.txt */"de contrabando",
  ItemWeaponRarityLegendary: /* csgo_latam.txt */"de tipo clasificado",
  ItemWeaponRarityMythical: /* csgo_latam.txt */"de tipo restringido",
  ItemWeaponRarityRare: /* csgo_latam.txt */"de grado militar",
  ItemWeaponRarityUncommon: /* csgo_latam.txt */"de grado industrial",
  ItemWearBS: /* csgo_latam.txt */"Deplorable",
  ItemWearFN: /* csgo_latam.txt */"Recién fabricado",
  ItemWearFT: /* csgo_latam.txt */"Algo desgastado",
  ItemWearMW: /* csgo_latam.txt */"Casi nuevo",
  ItemWearWW: /* csgo_latam.txt */"Bastante desgastado",
  RemovePatchRemove: /* csgo_latam.txt */"Quitar parche",
  RemovePatchRemoveDesc: /* csgo_latam.txt */"Por favor, confirma que deseas quitar este parche de tu agente. Al retirarlo, el parche se destruirá.",
  RemovePatchUse: /* csgo_latam.txt */"Quitar parche",
  RemovePatchWarn: /* csgo_latam.txt */"Quitar un parche de",
  RenameCancel: /* csgo_latam.txt */"Cancelar",
  RenameEnterName: /* csgo_latam.txt */"Introduce un nuevo nombre para tu",
  RenameRename: /* csgo_latam.txt */"Renombrar",
  RenameStorageUnitClose: /* csgo_latam.txt */"Cerrar",
  RenameStorageUnitEnterName: /* csgo_latam.txt */"Introduce un nuevo nombre para tu",
  RenameStorageUnitFirstNameWarn: /* csgo_latam.txt */"Introduce una etiqueta descriptiva para tu unidad de almacenamiento personal y empieza a utilizarla para guardar objetos.",
  RenameStorageUnitNewNameWarn: /* csgo_latam.txt */"Introduce una nueva etiqueta descriptiva para esta unidad de almacenamiento.",
  RenameStorageUnitRename: /* csgo_latam.txt */"Personalizar",
  RenameStorageUnitUse: /* csgo_latam.txt */"Personalizar unidad de almacenamiento",
  RenameUse: /* csgo_latam.txt */"Usar etiqueta de nombre",
  RenameWarn: /* csgo_latam.txt */"Las etiquetas de nombre solo pueden utilizarse una vez",
  ScrapeStickerCancel: /* csgo_latam.txt */"Cancelar",
  ScrapeStickerClose: /* csgo_latam.txt */"Cerrar",
  ScrapeStickerRemove: /* csgo_latam.txt */"Quitar calcomanía",
  ScrapeStickerRemoveDesc: /* csgo_latam.txt */"Raspar más esta calcomanía hará que ésta sea eliminada del objeto y a continuación destruida.",
  ScrapeStickerUse: /* csgo_latam.txt */"Raspar calcomanía",
  ScrapeStickerWarn: /* csgo_latam.txt */"Raspar una calcomanía de",
  SettingsMasterVolume: /* csgo_latam.txt */"Volumen general",
  StickerPickerRemove: /* csgo_latam.txt */"Eliminar"
};
