/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const polish = {
  ...english,
  ApplyPatchUse: /* csgo_polish.txt */"Użyj naszywki",
  ApplyPatchWarn: /* csgo_polish.txt */"Naszywka może zostać użyta tylko raz",
  ApplyStickerCancel: /* csgo_polish.txt */"Anuluj",
  ApplyStickerUse: /* csgo_polish.txt */"Nalep naklejkę",
  ApplyStickerUseOn: /* csgo_polish.txt */"Użyj na:",
  ApplyStickerWarn: /* csgo_polish.txt */"Naklejka może zostać użyta tylko raz",
  CaseAdd: /* csgo_polish.txt */"Dodaj",
  CaseClose: /* csgo_polish.txt */"Zamknij",
  CaseContainsOne: /* csgo_polish.txt */"Zawiera jedną rzecz z poniższych:",
  CaseNeed: /* csgo_polish.txt */"To działanie wymaga:",
  CaseOnceWarn: /* csgo_polish.txt */"Ten pojemnik może zostać otwarty tylko raz",
  CaseRareItem: /* csgo_polish.txt */"★ Rzadki przedmiot specjalny ★",
  CaseUnlock: /* csgo_polish.txt */"Otwórz:",
  CaseUnlockContainer: /* csgo_polish.txt */"Otwórz pojemnik",
  CaseUse: /* csgo_polish.txt */"Użyj:",
  CategoryAgent: /* csgo_polish.txt */"Agent",
  CategoryCase: /* csgo_polish.txt */"Pojemnik",
  CategoryCollectible: /* csgo_polish.txt */"Przedmiot kolekcjonerski",
  CategoryEquipment: /* csgo_polish.txt */"Wyposażenie",
  CategoryGlove: /* csgo_polish.txt */"Rękawice",
  CategoryGraffiti: /* csgo_polish.txt */"Graffiti",
  CategoryHeavy: /* csgo_polish.txt */"Ciężkie",
  CategoryKey: /* csgo_polish.txt */"Klucz",
  CategoryKeychain: /* csgo_polish.txt */"Przywieszka",
  CategoryKnife: /* csgo_polish.txt */"Nóż",
  CategoryMusicKit: /* csgo_polish.txt */"Zestaw utworów",
  CategoryPatch: /* csgo_polish.txt */"Naszywka",
  CategoryPistol: /* csgo_polish.txt */"Pistolet",
  CategoryRifle: /* csgo_polish.txt */"Karabin",
  CategorySMG: /* csgo_polish.txt */"PM",
  CategorySticker: /* csgo_polish.txt */"Naklejka",
  CategoryTool: /* csgo_polish.txt */"Narzędzie",
  EditorCancel: /* csgo_polish.txt */"Anuluj",
  EditorConfirmPick: /* csgo_polish.txt */"Potwierdź typowanie",
  EditorNametag: /* csgo_polish.txt */"Tabliczka z nazwą",
  EditorPatches: /* csgo_polish.txt */"Naszywki",
  EditorPick: /* csgo_polish.txt */"Wybór",
  EditorQuantity: /* csgo_polish.txt */"Ilość",
  EditorRandom: /* csgo_polish.txt */"Losowa",
  EditorReset: /* csgo_polish.txt */"Zresetuj",
  EditorSave: /* csgo_polish.txt */"Zapisz",
  EditorSeed: /* csgo_polish.txt */"Wzór",
  EditorStatTrak: /* csgo_polish.txt */"StatTrak™",
  EditorStickers: /* csgo_polish.txt */"Naklejki",
  EditorWear: /* csgo_polish.txt */"Zużycie",
  GenericCancel: /* csgo_polish.txt */"Anuluj",
  GenericNo: /* csgo_polish.txt */"Nie",
  GenericYes: /* csgo_polish.txt */"Tak",
  InspectClose: /* csgo_polish.txt */"Zamknij",
  InventoryApplyPatch: /* csgo_polish.txt */"Użyj naszywki",
  InventoryApplySticker: /* csgo_polish.txt */"Nalep naklejkę",
  InventoryFilterAgents: /* csgo_polish.txt */"Agenci",
  InventoryFilterAll: /* csgo_polish.txt */"Wszystkie",
  InventoryFilterAllEquipment: /* csgo_polish.txt */"Całe wyposażenie",
  InventoryFilterAllGraphicArt: /* csgo_polish.txt */"Wszystkie prace graficzne",
  InventoryFilterAlphabetical: /* csgo_polish.txt */"Alfabetycznie",
  InventoryFilterCharms: /* csgo_polish.txt */"Przywieszki",
  InventoryFilterCollection: /* csgo_polish.txt */"Kolekcja",
  InventoryFilterContainers: /* csgo_polish.txt */"POJEMNIKI",
  InventoryFilterDisplay: /* csgo_polish.txt */"GABLOTA",
  InventoryFilterEquipment: /* csgo_polish.txt */"EKWIPUNEK",
  InventoryFilterEquipped: /* csgo_polish.txt */"W użyciu",
  InventoryFilterEverything: /* csgo_polish.txt */"WSZYSTKO",
  InventoryFilterGloves: /* csgo_polish.txt */"Rękawice",
  InventoryFilterGraffiti: /* csgo_polish.txt */"Graffiti",
  InventoryFilterGraffitiBoxes: /* csgo_polish.txt */"Skrzynie z graffiti",
  InventoryFilterGraphicArt: /* csgo_polish.txt */"PRACE GRAFICZNE",
  InventoryFilterMedals: /* csgo_polish.txt */"Medale",
  InventoryFilterMelee: /* csgo_polish.txt */"Broń biała",
  InventoryFilterMidTier: /* csgo_polish.txt */"Pośrednie",
  InventoryFilterMisc: /* csgo_polish.txt */"Różne",
  InventoryFilterMusicKits: /* csgo_polish.txt */"Zestawy utworów",
  InventoryFilterNewest: /* csgo_polish.txt */"Najnowsze",
  InventoryFilterPatches: /* csgo_polish.txt */"Naszywki",
  InventoryFilterPistols: /* csgo_polish.txt */"Pistolety",
  InventoryFilterQuality: /* csgo_polish.txt */"Jakość",
  InventoryFilterRifles: /* csgo_polish.txt */"Karabiny",
  InventoryFilterSearch: /* csgo_polish.txt */"Wpisz frazę wyszukiwania tutaj",
  InventoryFilterSouvenirCases: /* csgo_polish.txt */"Zestawy pamiątkowe",
  InventoryFilterStickerCapsules: /* csgo_polish.txt */"Pojemniki z naklejką",
  InventoryFilterStickers: /* csgo_polish.txt */"Naklejki",
  InventoryFilterTools: /* csgo_polish.txt */"Narzędzia",
  InventoryFilterType: /* csgo_polish.txt */"Rodzaj",
  InventoryFilterWeaponCases: /* csgo_polish.txt */"Skrzynie z bronią",
  InventoryItemContainsOne: /* csgo_polish.txt */"Zawiera jedną rzecz z poniższych:",
  InventoryItemDelete: /* csgo_polish.txt */"Usuń",
  InventoryItemDeleteConfirm: /* csgo_polish.txt */"Usuń przedmiot",
  InventoryItemDeleteConfirmDesc: /* csgo_polish.txt */"Czy na pewno chcesz usunąć ten przedmiot?",
  InventoryItemEdit: /* csgo_polish.txt */"Edytuj",
  InventoryItemEquip: /* csgo_polish.txt */"Użyj",
  InventoryItemExterior: /* csgo_polish.txt */"Wygląd:",
  InventoryItemInspect: /* csgo_polish.txt */"Zbadaj",
  InventoryItemInspectFinishCatalog: /* csgo_polish.txt */"Nr w katalogu wykończenia",
  InventoryItemInspectInGame: /* csgo_polish.txt */"Zbadaj w grze...",
  InventoryItemInspectPatternTemplate: /* csgo_polish.txt */"Wzór szablonu",
  InventoryItemInspectWearRating: /* csgo_polish.txt */"Współczynnik zużycia",
  InventoryItemMVPStatTrakCount: /* csgo_polish.txt */"Turniejowe MVP (StatTrak™):",
  InventoryItemNew: /* csgo_polish.txt */"Nowe!",
  InventoryItemRareItem: /* csgo_polish.txt */"lub niezwykle rzadki przedmiot specjalny!",
  InventoryItemRarity: /* csgo_polish.txt */"Rzadkość:",
  InventoryItemRemovePatch: /* csgo_polish.txt */"Usuń naszywkę",
  InventoryItemRename: /* csgo_polish.txt */"Zmień nazwę:",
  InventoryItemRenameClearTooltip: /* csgo_polish.txt */"Zacznij od nowa.",
  InventoryItemRenameInvalidTooltip: /* csgo_polish.txt */"Wprowadź poprawną nazwę.",
  InventoryItemRenamePlaceholder: /* csgo_polish.txt */"Nowa nazwa",
  InventoryItemRenameStorageUnit: /* csgo_polish.txt */"Zmień nazwę",
  InventoryItemScrapeSticker: /* csgo_polish.txt */"Zdrap naklejkę",
  InventoryItemStatTrak: /* csgo_polish.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_polish.txt */"Zabójstwa potwierdzone przez StatTrak™:",
  InventoryItemStatTrakDesc: /* csgo_polish.txt */"Ten przedmiot posiada technologię StatTrak™, która pozwala śledzić pewne statystyki, kiedy jest używany przez jego właściciela.",
  InventoryItemStorageUnitDeposit: /* csgo_polish.txt */"Zdeponuj przedmioty",
  InventoryItemStorageUnitEmptyBody: /* csgo_polish.txt */"Ten schowek pozwala ci na przechowanie do {1} nadmiarowych przedmiotów, które w przeciwnym wypadku spowodowałyby przekroczenie twojego limitu ekwipunku. Wybrany schowek jest obecnie pusty. Możesz przenieść przedmioty do lub z niego lub po prostu użyć go do uporządkowania twoich zdobyczy w dowolnej chwili.",
  InventoryItemStorageUnitEmptyClose: /* csgo_polish.txt */"OK",
  InventoryItemStorageUnitEmptyTitle: /* csgo_polish.txt */"Pusty schowek",
  InventoryItemStorageUnitInspect: /* csgo_polish.txt */"Zbadaj",
  InventoryItemStorageUnitRetrieve: /* csgo_polish.txt */"Odzyskaj przedmioty",
  InventoryItemSwapStatTrak: /* csgo_polish.txt */"Otwórz narzędzie zamiany StatTrak™",
  InventoryItemTeam: /* csgo_polish.txt */"Drużyna:",
  InventoryItemTeamAny: /* csgo_polish.txt */"Obydwie",
  InventoryItemTeamCT: /* csgo_polish.txt */"Antyterroryści",
  InventoryItemTeamT: /* csgo_polish.txt */"Terroryści",
  InventoryItemUnequip: /* csgo_polish.txt */"Przestań używać",
  InventoryItemUnlockContainer: /* csgo_polish.txt */"Otwórz pojemnik",
  InventoryItemUseStorageUnit: /* csgo_polish.txt */"Zacznij korzystać z tego magazynu",
  InventorySelectAnItem: /* csgo_polish.txt */"Wybierz przedmiot do użycia:",
  InventorySelectInspectContents: /* csgo_polish.txt */"Sprawdzanie zawartości:",
  InventorySelectItemToDeposit: /* csgo_polish.txt */"Wybierz przedmioty do zdeponowania",
  InventorySelectItemToRetrieve: /* csgo_polish.txt */"Wybierz przedmioty do odzyskania",
  ItemRarityAncient: /* csgo_polish.txt */"wyjątkowej jakości",
  ItemRarityCommon: /* csgo_polish.txt */"standardowej jakości",
  ItemRarityDefault: /* csgo_polish.txt */"(standardowe wyposażenie)",
  ItemRarityImmortal: /* csgo_polish.txt */"z kontrabandy",
  ItemRarityLegendary: /* csgo_polish.txt */"egzotycznego pochodzenia",
  ItemRarityMythical: /* csgo_polish.txt */"nadzwyczajnej rzadkości",
  ItemRarityNameAgent: /* csgo_polish.txt */"Agent",
  ItemRarityNameC4: /* csgo_polish.txt */"C4",
  ItemRarityNameCharm: /* csgo_polish.txt */"Przywieszka",
  ItemRarityNameCollectible: /* csgo_polish.txt */"Przedmiot kolekcjonerski",
  ItemRarityNameContainer: /* csgo_polish.txt */"Pojemnik",
  ItemRarityNameContract: /* csgo_polish.txt */"Kontrakt",
  ItemRarityNameEquipment: /* csgo_polish.txt */"Wyposażenie",
  ItemRarityNameGloves: /* csgo_polish.txt */"Rękawice",
  ItemRarityNameGraffiti: /* csgo_polish.txt */"Graffiti",
  ItemRarityNameKey: /* csgo_polish.txt */"Klucz",
  ItemRarityNameKnife: /* csgo_polish.txt */"Nóż",
  ItemRarityNameMachinegun: /* csgo_polish.txt */"Karabin maszynowy",
  ItemRarityNameMusicKit: /* csgo_polish.txt */"Zestaw utworów",
  ItemRarityNamePatch: /* csgo_polish.txt */"Naszywka",
  ItemRarityNamePistol: /* csgo_polish.txt */"Pistolet",
  ItemRarityNameRifle: /* csgo_polish.txt */"Karabin",
  ItemRarityNameSMG: /* csgo_polish.txt */"PM",
  ItemRarityNameShotgun: /* csgo_polish.txt */"Strzelba",
  ItemRarityNameSniperRifle: /* csgo_polish.txt */"Karabin snajperski",
  ItemRarityNameSticker: /* csgo_polish.txt */"Naklejka",
  ItemRarityNameTool: /* csgo_polish.txt */"Narzędzie",
  ItemRarityRare: /* csgo_polish.txt */"wysokiej jakości",
  ItemRarityUncommon: /* csgo_polish.txt */"Średniej jakości",
  ItemSwapStatTrakAccept: /* csgo_polish.txt */"AKCEPTUJ",
  ItemSwapStatTrakClose: /* csgo_polish.txt */"Zamknij",
  ItemSwapStatTrakDesc: /* csgo_polish.txt */"Ten przedmiot zamienia wartości liczników StatTrak™ między przedmiotami tego samego rodzaju.",
  ItemSwapStatTrakUse: /* csgo_polish.txt */"Narzędzie zamiany StatTrak™",
  ItemSwapStatTrakWarn: /* csgo_polish.txt */"To narzędzie może zostać użyte tylko raz",
  ItemWeaponRarityAncient: /* csgo_polish.txt */"klasy „tajne”",
  ItemWeaponRarityCommon: /* csgo_polish.txt */"konsumenckiej jakości",
  ItemWeaponRarityDefault: /* csgo_polish.txt */"(standardowe wyposażenie)",
  ItemWeaponRarityImmortal: /* csgo_polish.txt */"z kontrabandy",
  ItemWeaponRarityLegendary: /* csgo_polish.txt */"klasy „poufne”",
  ItemWeaponRarityMythical: /* csgo_polish.txt */"spoza obiegu",
  ItemWeaponRarityRare: /* csgo_polish.txt */"wojskowej jakości",
  ItemWeaponRarityUncommon: /* csgo_polish.txt */"przemysłowej jakości",
  ItemWearBS: /* csgo_polish.txt */"po ciężkich walkach",
  ItemWearFN: /* csgo_polish.txt */"prosto z fabryki",
  ItemWearFT: /* csgo_polish.txt */"po testach bojowych",
  ItemWearMW: /* csgo_polish.txt */"lekkie zużycie",
  ItemWearWW: /* csgo_polish.txt */"mocne zużycie",
  RemovePatchRemove: /* csgo_polish.txt */"Usuń naszywkę",
  RemovePatchRemoveDesc: /* csgo_polish.txt */"Potwierdź, że chcesz usunąć tę naszywkę z twojego agenta. Usunięta naszywka zostanie zniszczona.",
  RemovePatchUse: /* csgo_polish.txt */"Usuń naszywkę",
  RemovePatchWarn: /* csgo_polish.txt */"Usuń naszywkę z:",
  RenameCancel: /* csgo_polish.txt */"Anuluj",
  RenameEnterName: /* csgo_polish.txt */"Wprowadź nową nazwę dla:",
  RenameRename: /* csgo_polish.txt */"Zmień nazwę:",
  RenameStorageUnitClose: /* csgo_polish.txt */"Zamknij",
  RenameStorageUnitEnterName: /* csgo_polish.txt */"Wprowadź nową nazwę dla:",
  RenameStorageUnitFirstNameWarn: /* csgo_polish.txt */"Wprowadź opisową nazwę dla twojego schowka i zacznij korzystać z niego do przechowywania przedmiotów.",
  RenameStorageUnitNewNameWarn: /* csgo_polish.txt */"Wprowadź nową opisową nazwę dla tego schowka.",
  RenameStorageUnitRename: /* csgo_polish.txt */"Spersonalizuj",
  RenameStorageUnitUse: /* csgo_polish.txt */"Spersonalizuj swój schowek",
  RenameUse: /* csgo_polish.txt */"Użyj tabliczki z nazwą",
  RenameWarn: /* csgo_polish.txt */"Tabliczka z nazwą może zostać użyta tylko raz",
  ScrapeStickerCancel: /* csgo_polish.txt */"Anuluj",
  ScrapeStickerClose: /* csgo_polish.txt */"Zamknij",
  ScrapeStickerRemove: /* csgo_polish.txt */"Usuń naklejkę",
  ScrapeStickerRemoveDesc: /* csgo_polish.txt */"Dalsze zdrapywanie naklejki doprowadzi do usunięcia jej z przedmiotu i zniszczenia.",
  ScrapeStickerUse: /* csgo_polish.txt */"Zdrap naklejkę",
  ScrapeStickerWarn: /* csgo_polish.txt */"Zdrap naklejkę z:",
  SettingsMasterVolume: /* csgo_polish.txt */"Głośność ogólna",
  StickerPickerRemove: /* csgo_polish.txt */"Usuń"
};
