/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const portuguese = {
  ...english,
  APIPageHeader: "API para programadores",
  ApplyPatchUse: /* csgo_portuguese.txt */"Aplicar emblema",
  ApplyPatchWarn: /* csgo_portuguese.txt */"Um emblema só pode ser aplicado uma vez",
  ApplyStickerCancel: /* csgo_portuguese.txt */"Cancelar",
  ApplyStickerUse: /* csgo_portuguese.txt */"Aplicar autocolante",
  ApplyStickerUseOn: /* csgo_portuguese.txt */"Usar em:",
  ApplyStickerWarn: /* csgo_portuguese.txt */"Um autocolante só pode ser colado uma vez.",
  CaseAdd: /* csgo_portuguese.txt */"Adicionar",
  CaseAddKeyConfirm: "Confirmar criação de chave",
  CaseClose: /* csgo_portuguese.txt */"Fechar",
  CaseContainsOne: /* csgo_portuguese.txt */"Contém um dos seguintes itens:",
  CaseNeed: /* csgo_portuguese.txt */"Esta ação requer o item:",
  CaseOnceWarn: /* csgo_portuguese.txt */"Esta caixa só pode ser aberta uma vez",
  CaseRareItem: /* csgo_portuguese.txt */"★ Item Especial Raro ★",
  CaseUnlock: /* csgo_portuguese.txt */"Desbloquear",
  CaseUnlockContainer: /* csgo_portuguese.txt */"Abrir",
  CaseUse: /* csgo_portuguese.txt */"Usar",
  CategoryAgent: /* csgo_portuguese.txt */"Agente",
  CategoryCase: /* csgo_portuguese.txt */"Caixa",
  CategoryCollectible: /* csgo_portuguese.txt */"Item de Colecionador",
  CategoryEquipment: /* csgo_portuguese.txt */"Equipamento",
  CategoryGlove: /* csgo_portuguese.txt */"Luvas",
  CategoryGraffiti: /* csgo_portuguese.txt */"Grafíti",
  CategoryHeavy: /* csgo_portuguese.txt */"Armas Pesadas",
  CategoryKey: /* csgo_portuguese.txt */"Chave",
  CategoryKnife: /* csgo_portuguese.txt */"Faca",
  CategoryMusicKit: /* csgo_portuguese.txt */"Kit de Música",
  CategoryPatch: /* csgo_portuguese.txt */"Emblema",
  CategoryPistol: /* csgo_portuguese.txt */"Pistola",
  CategoryRifle: /* csgo_portuguese.txt */"Espingarda",
  CategorySMG: /* csgo_portuguese.txt */"Submetralhadora",
  CategorySticker: /* csgo_portuguese.txt */"Autocolante",
  CategoryTool: /* csgo_portuguese.txt */"Ferramenta",
  CraftConfirmHeader: "Confirmar criação",
  CraftSearchPlaceholder: "Procurar um item...",
  CraftSelectHeader: "Criando um item...",
  EditorCancel: /* csgo_portuguese.txt */"Cancelar",
  EditorCraft: "Criar",
  EditorNametag: /* csgo_portuguese.txt */"Placa de Nome",
  EditorNametagPlaceholder: "Digite um nome...",
  EditorQuantity: /* csgo_portuguese.txt */"Quantidade",
  EditorRandom: /* csgo_portuguese.txt */"Aleatório",
  EditorReset: /* csgo_portuguese.txt */"Repor",
  EditorSave: /* csgo_portuguese.txt */"Guardar",
  EditorSeed: /* csgo_portuguese.txt */"Padrão",
  EditorStatTrak: /* csgo_portuguese.txt */"StatTrak™",
  EditorStickerWear: "Desgaste",
  EditorStickers: /* csgo_portuguese.txt */"Autocolantes",
  EditorWear: /* csgo_portuguese.txt */"Desgaste",
  GridItemNoItemsToDisplay: "Nenhum item para exibir",
  HeaderCraftLabel: "Criar Item",
  HeaderDonate: "Doar",
  HeaderInventoryLabel: "Inventário",
  HeaderSettingsLabel: "Configurações",
  HeaderSignInLabel: "Entrar e sincronizar",
  HeaderSignOutLabel: "Sair",
  HeaderSignedInAsLabel: "Entrou como",
  InspectClose: /* csgo_portuguese.txt */"Fechar",
  InventoryApplyPatch: /* csgo_portuguese.txt */"Aplicar emblema",
  InventoryApplySticker: /* csgo_portuguese.txt */"Aplicar autocolante",
  InventoryFilterAgents: /* csgo_portuguese.txt */"Agentes",
  InventoryFilterAll: /* csgo_portuguese.txt */"Todos",
  InventoryFilterAllEquipment: /* csgo_portuguese.txt */"Todo o equipamento",
  InventoryFilterAllGraphicArt: /* csgo_portuguese.txt */"Toda a arte gráfica",
  InventoryFilterAlphabetical: /* csgo_portuguese.txt */"A a Z",
  InventoryFilterCollection: /* csgo_portuguese.txt */"Coleção",
  InventoryFilterContainers: /* csgo_portuguese.txt */"CAIXAS",
  InventoryFilterDisplay: /* csgo_portuguese.txt */"CONDECORAÇÕES",
  InventoryFilterEquipment: /* csgo_portuguese.txt */"EQUIPAMENTO",
  InventoryFilterEquipped: /* csgo_portuguese.txt */"Equipados",
  InventoryFilterEverything: /* csgo_portuguese.txt */"TUDO",
  InventoryFilterGloves: /* csgo_portuguese.txt */"Luvas",
  InventoryFilterGraffiti: /* csgo_portuguese.txt */"Grafítis",
  InventoryFilterGraffitiBoxes: /* csgo_portuguese.txt */"Caixas de grafítis",
  InventoryFilterGraphicArt: /* csgo_portuguese.txt */"ARTE GRÁFICA",
  InventoryFilterMedals: /* csgo_portuguese.txt */"Medalhas",
  InventoryFilterMelee: /* csgo_portuguese.txt */"Armas corpo a corpo",
  InventoryFilterMidTier: /* csgo_portuguese.txt */"Gama média",
  InventoryFilterMisc: /* csgo_portuguese.txt */"Diversos",
  InventoryFilterMusicKits: /* csgo_portuguese.txt */"Kits de Música",
  InventoryFilterNewest: /* csgo_portuguese.txt */"Mais recentes",
  InventoryFilterPatches: /* csgo_portuguese.txt */"Emblemas",
  InventoryFilterPistols: /* csgo_portuguese.txt */"Pistolas",
  InventoryFilterQuality: /* csgo_portuguese.txt */"Raridade",
  InventoryFilterRifles: /* csgo_portuguese.txt */"Espingardas",
  InventoryFilterSearch: /* csgo_portuguese.txt */"Escreve p/ procurar",
  InventoryFilterSouvenirCases: /* csgo_portuguese.txt */"Caixas de brindes",
  InventoryFilterStickerCapsules: /* csgo_portuguese.txt */"Cápsulas de autocolantes",
  InventoryFilterStickers: /* csgo_portuguese.txt */"Autocolantes",
  InventoryFilterTools: /* csgo_portuguese.txt */"Ferramentas",
  InventoryFilterType: /* csgo_portuguese.txt */"Tipo",
  InventoryFilterWeaponCases: /* csgo_portuguese.txt */"Caixas de armas",
  InventoryItemContainsOne: /* csgo_portuguese.txt */"Contém um dos seguintes itens:",
  InventoryItemDelete: /* csgo_portuguese.txt */"Eliminar",
  InventoryItemEdit: /* csgo_portuguese.txt */"Editar",
  InventoryItemEquip: /* csgo_portuguese.txt */"Equipar",
  InventoryItemEquipBothTeams: "Equipar Ambas Equipes",
  InventoryItemEquipCT: "Equipar CT",
  InventoryItemEquipT: "Equipar T",
  InventoryItemExterior: /* csgo_portuguese.txt */"Condição:",
  InventoryItemInspect: /* csgo_portuguese.txt */"Examinar",
  InventoryItemInspectFinishCatalog: /* csgo_portuguese.txt */"Número de catálogo",
  InventoryItemInspectInGame: /* csgo_portuguese.txt */"Examinar no jogo...",
  InventoryItemInspectPatternTemplate: /* csgo_portuguese.txt */"Modelo do padrão",
  InventoryItemInspectWearRating: /* csgo_portuguese.txt */"Valor do desgaste",
  InventoryItemMVPStatTrakCount: /* csgo_portuguese.txt */"MVPs no modo competitivo:",
  InventoryItemNew: /* csgo_portuguese.txt */"Novo!",
  InventoryItemRareItem: /* csgo_portuguese.txt */"ou um item especial extremamente raro!",
  InventoryItemRarity: /* csgo_portuguese.txt */"Raridade:",
  InventoryItemRemovePatch: /* csgo_portuguese.txt */"Remover emblema",
  InventoryItemRename: /* csgo_portuguese.txt */"Renomear",
  InventoryItemRenameStorageUnit: /* csgo_portuguese.txt */"Editar nome",
  InventoryItemScrapeSticker: /* csgo_portuguese.txt */"Raspar autocolante",
  InventoryItemStatTrak: /* csgo_portuguese.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_portuguese.txt */"Vítimas confirmadas:",
  InventoryItemStatTrakDesc: /* csgo_portuguese.txt */"Este item possui a tecnologia StatTrak™, que faz a contagem de certas estatísticas enquanto estiver equipado.",
  InventoryItemStorageUnitDeposit: /* csgo_portuguese.txt */"Depositar itens",
  InventoryItemStorageUnitEmptyBody: /* csgo_portuguese.txt */"Nesta Unidade de Armazenamento podes guardar até {1} itens que iriam de outra forma exceder o limite do teu inventário. A Unidade de Armazenamento selecionada está atualmente vazia. A qualquer momento, podes mover itens do teu inventário para esta Unidade de Armazenamento e vice-versa, ou podes simplesmente usá-la para organizar os teus itens favoritos.",
  InventoryItemStorageUnitEmptyClose: /* csgo_portuguese.txt */"OK",
  InventoryItemStorageUnitEmptyTitle: /* csgo_portuguese.txt */"Unidade de Armazenamento vazia",
  InventoryItemStorageUnitInspect: /* csgo_portuguese.txt */"Examinar",
  InventoryItemStorageUnitRetrieve: /* csgo_portuguese.txt */"Retirar itens",
  InventoryItemSwapStatTrak: /* csgo_portuguese.txt */"Abrir Trocador de Estatísticas StatTrak™",
  InventoryItemTeam: /* csgo_portuguese.txt */"Equipa:",
  InventoryItemTeamAny: /* csgo_portuguese.txt */"Qualquer",
  InventoryItemTeamCT: /* csgo_portuguese.txt */"Contraterrorista",
  InventoryItemTeamT: /* csgo_portuguese.txt */"Terrorista",
  InventoryItemUnequip: /* csgo_portuguese.txt */"Desequipar",
  InventoryItemUnequipCT: "Desequipar CT",
  InventoryItemUnequipT: "Desequipar T",
  InventoryItemUnlockContainer: /* csgo_portuguese.txt */"Abrir",
  InventoryItemUseStorageUnit: /* csgo_portuguese.txt */"Usar esta unidade",
  InventoryNoItemsToDisplay: "Nenhum item para exibir",
  InventoryScrapeSticker: "Raspar autocolante",
  InventorySelectAnItem: /* csgo_portuguese.txt */"Seleciona um item para usar com:",
  InventorySelectInspectContents: /* csgo_portuguese.txt */"A ver conteúdo de",
  InventorySelectItemToDeposit: /* csgo_portuguese.txt */"Seleciona quais itens guardar em",
  InventorySelectItemToRetrieve: /* csgo_portuguese.txt */"Seleciona quais itens retirar de",
  InvnetoryFilterSearch: "Buscar",
  ItemRarityAncient: /* csgo_portuguese.txt */"Extraordinário",
  ItemRarityCommon: /* csgo_portuguese.txt */"Qualidade Básica",
  ItemRarityDefault: /* csgo_portuguese.txt */"Standard",
  ItemRarityFormat: "{2} ({1})",
  ItemRarityImmortal: /* csgo_portuguese.txt */"Contrabando",
  ItemRarityLegendary: /* csgo_portuguese.txt */"Exótico",
  ItemRarityMythical: /* csgo_portuguese.txt */"Notável",
  ItemRarityNameAgent: /* csgo_portuguese.txt */"Agente",
  ItemRarityNameCollectible: /* csgo_portuguese.txt */"Item de Colecionador",
  ItemRarityNameContainer: /* csgo_portuguese.txt */"Caixa",
  ItemRarityNameContract: /* csgo_portuguese.txt */"Contrato",
  ItemRarityNameEquipment: /* csgo_portuguese.txt */"Equipamento",
  ItemRarityNameGloves: /* csgo_portuguese.txt */"Luvas",
  ItemRarityNameGraffiti: /* csgo_portuguese.txt */"Grafíti",
  ItemRarityNameKey: /* csgo_portuguese.txt */"Chave",
  ItemRarityNameKnife: /* csgo_portuguese.txt */"Faca",
  ItemRarityNameMachinegun: /* csgo_portuguese.txt */"Metralhadora",
  ItemRarityNameMusicKit: /* csgo_portuguese.txt */"Kit de Música",
  ItemRarityNamePatch: /* csgo_portuguese.txt */"Emblema",
  ItemRarityNamePistol: /* csgo_portuguese.txt */"Pistola",
  ItemRarityNameRifle: /* csgo_portuguese.txt */"Espingarda",
  ItemRarityNameSMG: /* csgo_portuguese.txt */"Submetralhadora",
  ItemRarityNameShotgun: /* csgo_portuguese.txt */"Caçadeira",
  ItemRarityNameSniperRifle: /* csgo_portuguese.txt */"Espingarda Sniper",
  ItemRarityNameSticker: /* csgo_portuguese.txt */"Autocolante",
  ItemRarityNameTool: /* csgo_portuguese.txt */"Ferramenta",
  ItemRarityRare: /* csgo_portuguese.txt */"Alta Qualidade",
  ItemRarityUncommon: /* csgo_portuguese.txt */"Qualidade Média",
  ItemSwapStatTrakAccept: /* csgo_portuguese.txt */"ACEITAR",
  ItemSwapStatTrakClose: /* csgo_portuguese.txt */"Fechar",
  ItemSwapStatTrakDesc: /* csgo_portuguese.txt */"Este item troca as estatísticas StatTrak™ entre dois itens do mesmo tipo.",
  ItemSwapStatTrakUse: /* csgo_portuguese.txt */"Trocador de estatísticas StatTrak™",
  ItemSwapStatTrakWarn: /* csgo_portuguese.txt */"Este Trocador de Estatísticas StatTrak™ só pode ser usado uma vez",
  ItemWeaponRarityAncient: /* csgo_portuguese.txt */"Secreto",
  ItemWeaponRarityCommon: /* csgo_portuguese.txt */"Padrão Doméstico",
  ItemWeaponRarityDefault: /* csgo_portuguese.txt */"Standard",
  ItemWeaponRarityImmortal: /* csgo_portuguese.txt */"Contrabando",
  ItemWeaponRarityLegendary: /* csgo_portuguese.txt */"Confidencial",
  ItemWeaponRarityMythical: /* csgo_portuguese.txt */"Restrito",
  ItemWeaponRarityRare: /* csgo_portuguese.txt */"Padrão Militar",
  ItemWeaponRarityUncommon: /* csgo_portuguese.txt */"Padrão Industrial",
  ItemWearBS: /* csgo_portuguese.txt */"Gasto",
  ItemWearFN: /* csgo_portuguese.txt */"Original de Fábrica",
  ItemWearFT: /* csgo_portuguese.txt */"Testado no Terreno",
  ItemWearMW: /* csgo_portuguese.txt */"Com Pouco Uso",
  ItemWearWW: /* csgo_portuguese.txt */"Com Muito Uso",
  JavaScriptRequired: "Por favor, habilite o JavaScript e atualize a página.",
  RemovePatchRemove: /* csgo_portuguese.txt */"Remover emblema",
  RemovePatchRemoveDesc: /* csgo_portuguese.txt */"Confirma que gostarias de remover este emblema do teu agente. O emblema removido será destruído.",
  RemovePatchUse: /* csgo_portuguese.txt */"Remover emblema",
  RemovePatchWarn: /* csgo_portuguese.txt */"Remover um emblema de",
  RenameCancel: /* csgo_portuguese.txt */"Cancelar",
  RenameEnterName: /* csgo_portuguese.txt */"Escreve um nome novo para:",
  RenameRename: /* csgo_portuguese.txt */"Renomear",
  RenameStorageUnitClose: /* csgo_portuguese.txt */"Fechar",
  RenameStorageUnitEnterName: /* csgo_portuguese.txt */"Escreve um nome novo para:",
  RenameStorageUnitFirstNameWarn: /* csgo_portuguese.txt */"Dá um nome à tua Unidade de Armazenamento para começares a usá-la para guardar itens.",
  RenameStorageUnitNewNameWarn: /* csgo_portuguese.txt */"Dá um nome novo a esta Unidade de Armazenamento.",
  RenameStorageUnitRename: /* csgo_portuguese.txt */"Personalizar",
  RenameStorageUnitUse: /* csgo_portuguese.txt */"Personalizar Unidade de Armazenamento",
  RenameUse: /* csgo_portuguese.txt */"Usar Placa de Nome",
  RenameWarn: /* csgo_portuguese.txt */"Uma Placa de Nome só pode ser usada uma vez",
  ScrapeStickerCancel: /* csgo_portuguese.txt */"Cancelar",
  ScrapeStickerClose: /* csgo_portuguese.txt */"Fechar",
  ScrapeStickerRemove: /* csgo_portuguese.txt */"Remover autocolante",
  ScrapeStickerRemoveDesc: /* csgo_portuguese.txt */"Raspar este autocolante ainda mais irá removê-lo da arma e será destruído.",
  ScrapeStickerUse: /* csgo_portuguese.txt */"Raspar autocolante",
  ScrapeStickerWarn: /* csgo_portuguese.txt */"Raspar um autocolante de",
  SettingsBackground: "Plano de Fundo",
  SettingsBackgroundRandom: "Aleatório",
  SettingsConfirmRemoveAllItems: "Tem certeza de que deseja remover todos os itens do seu inventário?\n\nESSA AÇÃO NÃO PODE SER DESFEITA.",
  SettingsHeader: "Configurações",
  SettingsHideFilters: "Ocultar Filtros",
  SettingsHideFreeItems: "Ocultar Itens Gratuitos",
  SettingsLanguage: "Idioma",
  SettingsRemoveAllItems: "Redefinir meu inventário",
  SettingsSave: "Salvar",
  SettingsStatsForNerds: "Estatísticas para Nerds",
  StickerPickerFilterPlaceholder: "Filtrar por categoria...",
  StickerPickerHeader: "Escolha um adesivo...",
  StickerPickerRemove: /* csgo_portuguese.txt */"Remover",
  StickerPickerSearchPlaceholder: "Procurar adesivo...",
  SyncErrorContinue: "Tentar novamente",
  SyncErrorDesc: "Não foi possível sincronizar as suas mudanças.",
  SyncErrorTitle: "Erro de sincronização",
  SyncWarnText: "Você não está autenticado, suas mudanças não serão sincronizadas."
};
