/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const romanian = {
  ...english,
  ApplyPatchUse: /* csgo_romanian.txt */"Aplică ecusonul brodat",
  ApplyPatchWarn: /* csgo_romanian.txt */"Un ecuson brodat poate fi aplicat doar o dată",
  ApplyStickerCancel: /* csgo_romanian.txt */"Anulează",
  ApplyStickerUse: /* csgo_romanian.txt */"Lipește abțibildul",
  ApplyStickerUseOn: /* csgo_romanian.txt */"Folosește pe",
  ApplyStickerWarn: /* csgo_romanian.txt */"Un abțibild poate fi lipit doar o dată",
  CaseAdd: /* csgo_romanian.txt */"Adaugă",
  CaseClose: /* csgo_romanian.txt */"Închide",
  CaseContainsOne: /* csgo_romanian.txt */"Conține unul din obiectele următoarele:",
  CaseNeed: /* csgo_romanian.txt */"Această acțiune necesită:",
  CaseOnceWarn: /* csgo_romanian.txt */"Acest container poate fi deschis doar o singură dată",
  CaseRareItem: /* csgo_romanian.txt */"★ Obiect special rar ★",
  CaseUnlock: /* csgo_romanian.txt */"Deblocheză",
  CaseUnlockContainer: /* csgo_romanian.txt */"Deschide containerul",
  CaseUse: /* csgo_romanian.txt */"Folosește",
  CategoryAgent: /* csgo_romanian.txt */"Agent",
  CategoryCase: /* csgo_romanian.txt */"Container",
  CategoryCollectible: /* csgo_romanian.txt */"De colecție",
  CategoryEquipment: /* csgo_romanian.txt */"Echipament",
  CategoryGlove: /* csgo_romanian.txt */"Mănuși",
  CategoryGraffiti: /* csgo_romanian.txt */"Graffiti",
  CategoryHeavy: /* csgo_romanian.txt */"Arme grele",
  CategoryKey: /* csgo_romanian.txt */"Cheie",
  CategoryKnife: /* csgo_romanian.txt */"Cuțit",
  CategoryMusicKit: /* csgo_romanian.txt */"Pachet muzical",
  CategoryPatch: /* csgo_romanian.txt */"Ecuson brodat",
  CategoryPistol: /* csgo_romanian.txt */"Pistol",
  CategoryRifle: /* csgo_romanian.txt */"Pușcă ghintuită",
  CategorySMG: /* csgo_romanian.txt */"Pistol-mitralieră",
  CategorySticker: /* csgo_romanian.txt */"Abțibild",
  CategoryTool: /* csgo_romanian.txt */"Instrument",
  EditorCancel: /* csgo_romanian.txt */"Anulează",
  EditorNametag: /* csgo_romanian.txt */"Etichetă",
  EditorPatches: /* csgo_romanian.txt */"Ecusoane brodate",
  EditorQuantity: /* csgo_romanian.txt */"Cantitate",
  EditorRandom: /* csgo_romanian.txt */"Aleatorie",
  EditorReset: /* csgo_romanian.txt */"Resetează",
  EditorSave: /* csgo_romanian.txt */"Salvează",
  EditorSeed: /* csgo_romanian.txt */"Tipar",
  EditorStatTrak: /* csgo_romanian.txt */"StatTrak™",
  EditorStickers: /* csgo_romanian.txt */"Abțibilduri",
  EditorWear: /* csgo_romanian.txt */"Uzură",
  InspectClose: /* csgo_romanian.txt */"Închide",
  InventoryApplyPatch: /* csgo_romanian.txt */"Aplică ecusonul brodat",
  InventoryApplySticker: /* csgo_romanian.txt */"Lipește abțibildul",
  InventoryFilterAgents: /* csgo_romanian.txt */"Agenți",
  InventoryFilterAll: /* csgo_romanian.txt */"Toate",
  InventoryFilterAllEquipment: /* csgo_romanian.txt */"Tot echipamentul",
  InventoryFilterAllGraphicArt: /* csgo_romanian.txt */"Toate ilustrațiile",
  InventoryFilterAlphabetical: /* csgo_romanian.txt */"Alfabetică",
  InventoryFilterCollection: /* csgo_romanian.txt */"Colecție",
  InventoryFilterContainers: /* csgo_romanian.txt */"CONTAINERE",
  InventoryFilterDisplay: /* csgo_romanian.txt */"DISTINCȚII",
  InventoryFilterEquipment: /* csgo_romanian.txt */"ECHIPAMENT",
  InventoryFilterEquipped: /* csgo_romanian.txt */"Echipat",
  InventoryFilterEverything: /* csgo_romanian.txt */"TOT",
  InventoryFilterGloves: /* csgo_romanian.txt */"Mănuși",
  InventoryFilterGraffiti: /* csgo_romanian.txt */"Graffitiuri",
  InventoryFilterGraffitiBoxes: /* csgo_romanian.txt */"Cutii cu graffiti",
  InventoryFilterGraphicArt: /* csgo_romanian.txt */"ILUSTRAȚII",
  InventoryFilterMedals: /* csgo_romanian.txt */"Medalii",
  InventoryFilterMelee: /* csgo_romanian.txt */"Cuțit",
  InventoryFilterMidTier: /* csgo_romanian.txt */"Intermediare",
  InventoryFilterMisc: /* csgo_romanian.txt */"Diverse",
  InventoryFilterMusicKits: /* csgo_romanian.txt */"Pachete muzicale",
  InventoryFilterNewest: /* csgo_romanian.txt */"Cele mai noi",
  InventoryFilterPatches: /* csgo_romanian.txt */"Ecusoane brodate",
  InventoryFilterPistols: /* csgo_romanian.txt */"Pistoale",
  InventoryFilterQuality: /* csgo_romanian.txt */"Calitate",
  InventoryFilterRifles: /* csgo_romanian.txt */"Puști ghintuite",
  InventoryFilterSearch: /* csgo_romanian.txt */"Tastează termenul căutat",
  InventoryFilterSouvenirCases: /* csgo_romanian.txt */"Cutii cu suvenir",
  InventoryFilterStickerCapsules: /* csgo_romanian.txt */"Capsule cu abțibild",
  InventoryFilterStickers: /* csgo_romanian.txt */"Abțibilduri",
  InventoryFilterTools: /* csgo_romanian.txt */"Instrumente",
  InventoryFilterType: /* csgo_romanian.txt */"Tip",
  InventoryFilterWeaponCases: /* csgo_romanian.txt */"Cutii cu armă",
  InventoryItemContainsOne: /* csgo_romanian.txt */"Conține unul din obiectele următoarele:",
  InventoryItemDelete: /* csgo_romanian.txt */"Șterge",
  InventoryItemEdit: /* csgo_romanian.txt */"Editează",
  InventoryItemEquip: /* csgo_romanian.txt */"Echipează",
  InventoryItemExterior: /* csgo_romanian.txt */"Exterior:",
  InventoryItemInspect: /* csgo_romanian.txt */"Inspectează",
  InventoryItemInspectFinishCatalog: /* csgo_romanian.txt */"Catalogul finisajului",
  InventoryItemInspectInGame: /* csgo_romanian.txt */"Inspectează în joc...",
  InventoryItemInspectPatternTemplate: /* csgo_romanian.txt */"Șablonul modelului",
  InventoryItemInspectWearRating: /* csgo_romanian.txt */"Grad de uzură",
  InventoryItemMVPStatTrakCount: /* csgo_romanian.txt */"MVP-uri competitive oficiale StatTrak™:",
  InventoryItemNew: /* csgo_romanian.txt */"Nou!",
  InventoryItemRareItem: /* csgo_romanian.txt */"sau un obiect extrem de rar și special!",
  InventoryItemRarity: /* csgo_romanian.txt */"Raritate:",
  InventoryItemRemovePatch: /* csgo_romanian.txt */"Înlătură ecusonul brodat",
  InventoryItemRename: /* csgo_romanian.txt */"Redenumește",
  InventoryItemRenameStorageUnit: /* csgo_romanian.txt */"Schimbă denumirea",
  InventoryItemScrapeSticker: /* csgo_romanian.txt */"Răzuiește abțibildul",
  InventoryItemStatTrak: /* csgo_romanian.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_romanian.txt */"Ucideri StatTrak™ confirmate:",
  InventoryItemStatTrakDesc: /* csgo_romanian.txt */"Acest obiect beneficiază de tehnologia StatTrak™, care urmărește anumite statistici când este echipat de proprietarul lui.",
  InventoryItemStorageUnitDeposit: /* csgo_romanian.txt */"Depozitează obiecte",
  InventoryItemStorageUnitEmptyBody: /* csgo_romanian.txt */"Unitatea de stocare îți permite să depozitezi până la {1} de obiecte care altfel ar depăși capacitatea inventarului tău. Unitatea de stocare selectată este în prezent goală. Îți poți muta oricând obiectele din inventar în această unitate de stocare sau viceversa. De asemenea, poți utiliza unitatea de stocare pentru a-ți organiza colecțiile de obiecte.",
  InventoryItemStorageUnitEmptyClose: /* csgo_romanian.txt */"OK",
  InventoryItemStorageUnitEmptyTitle: /* csgo_romanian.txt */"Unitate de stocare goală",
  InventoryItemStorageUnitInspect: /* csgo_romanian.txt */"Inspectează",
  InventoryItemStorageUnitRetrieve: /* csgo_romanian.txt */"Preia obiecte",
  InventoryItemSwapStatTrak: /* csgo_romanian.txt */"Deschide schimbătorul StatTrak™",
  InventoryItemTeam: /* csgo_romanian.txt */"Echipa:",
  InventoryItemTeamAny: /* csgo_romanian.txt */"Oricare",
  InventoryItemTeamCT: /* csgo_romanian.txt */"Contraterorist",
  InventoryItemTeamT: /* csgo_romanian.txt */"Terorist",
  InventoryItemUnequip: /* csgo_romanian.txt */"Dezechipează",
  InventoryItemUnlockContainer: /* csgo_romanian.txt */"Deschide containerul",
  InventoryItemUseStorageUnit: /* csgo_romanian.txt */"Începe să folosești această unitate de stocare",
  InventorySelectAnItem: /* csgo_romanian.txt */"Selectează un obiect pe care să îl folosești cu:",
  InventorySelectInspectContents: /* csgo_romanian.txt */"Inspectezi conținutul pentru:",
  InventorySelectItemToDeposit: /* csgo_romanian.txt */"Selecteză obiectele pe care să le depozitezi",
  InventorySelectItemToRetrieve: /* csgo_romanian.txt */"Selectează obiectele pe care să le preiei",
  ItemRarityAncient: /* csgo_romanian.txt */"Extraordinar(ă)",
  ItemRarityCommon: /* csgo_romanian.txt */"Calitate de bază",
  ItemRarityDefault: /* csgo_romanian.txt */"Implicit(ă)",
  ItemRarityImmortal: /* csgo_romanian.txt */"Contrabandă",
  ItemRarityLegendary: /* csgo_romanian.txt */"Exotic(ă)",
  ItemRarityMythical: /* csgo_romanian.txt */"Remarcabil(ă)",
  ItemRarityNameAgent: /* csgo_romanian.txt */"Agent",
  ItemRarityNameCollectible: /* csgo_romanian.txt */"De colecție",
  ItemRarityNameContainer: /* csgo_romanian.txt */"Container",
  ItemRarityNameContract: /* csgo_romanian.txt */"Contract",
  ItemRarityNameEquipment: /* csgo_romanian.txt */"Echipament",
  ItemRarityNameGloves: /* csgo_romanian.txt */"Mănuși",
  ItemRarityNameGraffiti: /* csgo_romanian.txt */"Graffiti",
  ItemRarityNameKey: /* csgo_romanian.txt */"Cheie",
  ItemRarityNameKnife: /* csgo_romanian.txt */"Cuțit",
  ItemRarityNameMachinegun: /* csgo_romanian.txt */"Mitralieră",
  ItemRarityNameMusicKit: /* csgo_romanian.txt */"Pachet muzical",
  ItemRarityNamePatch: /* csgo_romanian.txt */"Ecuson brodat",
  ItemRarityNamePistol: /* csgo_romanian.txt */"Pistol",
  ItemRarityNameRifle: /* csgo_romanian.txt */"Pușcă ghintuită",
  ItemRarityNameSMG: /* csgo_romanian.txt */"Pistol-mitralieră",
  ItemRarityNameShotgun: /* csgo_romanian.txt */"Pușcă",
  ItemRarityNameSniperRifle: /* csgo_romanian.txt */"Armă cu lunetă",
  ItemRarityNameSticker: /* csgo_romanian.txt */"Abțibild",
  ItemRarityNameTool: /* csgo_romanian.txt */"Instrument",
  ItemRarityRare: /* csgo_romanian.txt */"Calitate ridicată",
  ItemRarityUncommon: /* csgo_romanian.txt */"Calitate medie",
  ItemSwapStatTrakAccept: /* csgo_romanian.txt */"ACCEPTĂ",
  ItemSwapStatTrakClose: /* csgo_romanian.txt */"Închide",
  ItemSwapStatTrakDesc: /* csgo_romanian.txt */"Acest obiect schimbă între ele valorile StatTrak™ pentru două obiecte de același tip.",
  ItemSwapStatTrakUse: /* csgo_romanian.txt */"Schimbător StatTrak™",
  ItemSwapStatTrakWarn: /* csgo_romanian.txt */"Acest schimbător StatTrak™ poate fi folosit doar o dată",
  ItemWeaponRarityAncient: /* csgo_romanian.txt */"Clandestin(ă)",
  ItemWeaponRarityCommon: /* csgo_romanian.txt */"Calitate obișnuită",
  ItemWeaponRarityDefault: /* csgo_romanian.txt */"Standard",
  ItemWeaponRarityImmortal: /* csgo_romanian.txt */"Contrabandă",
  ItemWeaponRarityLegendary: /* csgo_romanian.txt */"Secret(ă)",
  ItemWeaponRarityMythical: /* csgo_romanian.txt */"Restricționat(ă)",
  ItemWeaponRarityRare: /* csgo_romanian.txt */"Calitate militară",
  ItemWeaponRarityUncommon: /* csgo_romanian.txt */"Calitate industrială",
  ItemWearBS: /* csgo_romanian.txt */"Deteriorată",
  ItemWearFN: /* csgo_romanian.txt */"Nouă",
  ItemWearFT: /* csgo_romanian.txt */"Testată",
  ItemWearMW: /* csgo_romanian.txt */"Uzură minimă",
  ItemWearWW: /* csgo_romanian.txt */"Uzată",
  RemovePatchRemove: /* csgo_romanian.txt */"Înlătură ecusonul brodat",
  RemovePatchRemoveDesc: /* csgo_romanian.txt */"Te rugăm să confirmi faptul că vrei să înlături ecusonul brodat de pe agentul tău. Ecusonul brodat va fi distrus după înlăturare.",
  RemovePatchUse: /* csgo_romanian.txt */"Înlătură ecusonul brodat",
  RemovePatchWarn: /* csgo_romanian.txt */"Înlătură un ecuson brodat de pe",
  RenameCancel: /* csgo_romanian.txt */"Anulează",
  RenameEnterName: /* csgo_romanian.txt */"Introdu un nume nou pentru:",
  RenameRename: /* csgo_romanian.txt */"Redenumește",
  RenameStorageUnitClose: /* csgo_romanian.txt */"Închide",
  RenameStorageUnitEnterName: /* csgo_romanian.txt */"Introdu un nume nou pentru:",
  RenameStorageUnitFirstNameWarn: /* csgo_romanian.txt */"Introdu o denumire descriptivă pentru unitatea de stocare personală și începe să o folosești pentru depozitarea obiectelor.",
  RenameStorageUnitNewNameWarn: /* csgo_romanian.txt */"Introdu o nouă denumire descriptivă pentru această unitate de stocare.",
  RenameStorageUnitRename: /* csgo_romanian.txt */"Personalizează",
  RenameStorageUnitUse: /* csgo_romanian.txt */"Personalizează-ți unitatea de stocare",
  RenameUse: /* csgo_romanian.txt */"Folosește eticheta",
  RenameWarn: /* csgo_romanian.txt */"O etichetă nu poate fi folosită decât o dată.",
  ScrapeStickerCancel: /* csgo_romanian.txt */"Anulează",
  ScrapeStickerClose: /* csgo_romanian.txt */"Închide",
  ScrapeStickerRemove: /* csgo_romanian.txt */"Înlătură abțibildul",
  ScrapeStickerRemoveDesc: /* csgo_romanian.txt */"Dacă răzuiești în continuare acest abțibild, îl vei șterge de pe obiect și-l vei distruge.",
  ScrapeStickerUse: /* csgo_romanian.txt */"Răzuiește abțibildul",
  ScrapeStickerWarn: /* csgo_romanian.txt */"Răzuiește un abțibild de pe",
  StickerPickerRemove: /* csgo_romanian.txt */"Șterge"
};
