/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const russian = {
  ...english,
  ApplyPatchUse: /* csgo_russian.txt */"Нанести нашивку",
  ApplyPatchWarn: /* csgo_russian.txt */"Нашивку можно использовать только один раз",
  ApplyStickerCancel: /* csgo_russian.txt */"Отмена",
  ApplyStickerUse: /* csgo_russian.txt */"Нанести наклейку",
  ApplyStickerUseOn: /* csgo_russian.txt */"Использовать на",
  ApplyStickerWarn: /* csgo_russian.txt */"Наклейку можно использовать только один раз",
  CaseAdd: /* csgo_russian.txt */"Добавить",
  CaseClose: /* csgo_russian.txt */"Закрыть",
  CaseContainsOne: /* csgo_russian.txt */"Внутри находится один из следующих предметов:",
  CaseNeed: /* csgo_russian.txt */"Требуется",
  CaseOnceWarn: /* csgo_russian.txt */"Этот контейнер можно открыть только один раз",
  CaseRareItem: /* csgo_russian.txt */"★ Особый редкий предмет ★",
  CaseUnlock: /* csgo_russian.txt */"Открыть",
  CaseUnlockContainer: /* csgo_russian.txt */"Открыть контейнер",
  CaseUse: /* csgo_russian.txt */"Использовать",
  CategoryAgent: /* csgo_russian.txt */"Агент",
  CategoryCase: /* csgo_russian.txt */"Контейнер",
  CategoryCollectible: /* csgo_russian.txt */"Сувенир",
  CategoryEquipment: /* csgo_russian.txt */"Снаряжение",
  CategoryGlove: /* csgo_russian.txt */"Перчатки",
  CategoryGraffiti: /* csgo_russian.txt */"Граффити",
  CategoryHeavy: /* csgo_russian.txt */"Тяжелое",
  CategoryKey: /* csgo_russian.txt */"Ключ",
  CategoryKeychain: /* csgo_russian.txt */"Брелок",
  CategoryKnife: /* csgo_russian.txt */"Нож",
  CategoryMusicKit: /* csgo_russian.txt */"Набор музыки",
  CategoryPatch: /* csgo_russian.txt */"Нашивка",
  CategoryPistol: /* csgo_russian.txt */"Пистолет",
  CategoryRifle: /* csgo_russian.txt */"Винтовка",
  CategorySMG: /* csgo_russian.txt */"Пистолет-пулемёт",
  CategorySticker: /* csgo_russian.txt */"Наклейка",
  CategoryTool: /* csgo_russian.txt */"Инструмент",
  EditorCancel: /* csgo_russian.txt */"Отмена",
  EditorConfirmPick: /* csgo_russian.txt */"Подтвердить",
  EditorNametag: /* csgo_russian.txt */"Именной ярлык",
  EditorPatches: /* csgo_russian.txt */"Нашивки",
  EditorPick: /* csgo_russian.txt */"Выбираем",
  EditorQuantity: /* csgo_russian.txt */"Кол-во",
  EditorRandom: /* csgo_russian.txt */"Случайно",
  EditorReset: /* csgo_russian.txt */"Сброс",
  EditorSave: /* csgo_russian.txt */"Сохранить",
  EditorSeed: /* csgo_russian.txt */"Шаблон",
  EditorStatTrak: /* csgo_russian.txt */"StatTrak™",
  EditorStickers: /* csgo_russian.txt */"Наклейки",
  EditorWear: /* csgo_russian.txt */"Износ",
  GenericCancel: /* csgo_russian.txt */"Отмена",
  GenericNo: /* csgo_russian.txt */"Нет",
  GenericYes: /* csgo_russian.txt */"Да",
  InspectClose: /* csgo_russian.txt */"Закрыть",
  InventoryApplyPatch: /* csgo_russian.txt */"Нанести нашивку",
  InventoryApplySticker: /* csgo_russian.txt */"Нанести наклейку",
  InventoryFilterAgents: /* csgo_russian.txt */"Агенты",
  InventoryFilterAll: /* csgo_russian.txt */"Все",
  InventoryFilterAllEquipment: /* csgo_russian.txt */"Вся экипировка",
  InventoryFilterAllGraphicArt: /* csgo_russian.txt */"Вся графика",
  InventoryFilterAlphabetical: /* csgo_russian.txt */"По алфавиту",
  InventoryFilterCharms: /* csgo_russian.txt */"Брелки",
  InventoryFilterCollection: /* csgo_russian.txt */"По коллекции",
  InventoryFilterContainers: /* csgo_russian.txt */"КОНТЕЙНЕРЫ",
  InventoryFilterDisplay: /* csgo_russian.txt */"ПРОФИЛЬ",
  InventoryFilterEquipment: /* csgo_russian.txt */"ЭКИПИРОВКА",
  InventoryFilterEquipped: /* csgo_russian.txt */"По использованию",
  InventoryFilterEverything: /* csgo_russian.txt */"ВСЁ",
  InventoryFilterGloves: /* csgo_russian.txt */"Перчатки",
  InventoryFilterGraffiti: /* csgo_russian.txt */"Граффити",
  InventoryFilterGraffitiBoxes: /* csgo_russian.txt */"Ящики с граффити",
  InventoryFilterGraphicArt: /* csgo_russian.txt */"ГРАФИКА",
  InventoryFilterMedals: /* csgo_russian.txt */"Медали",
  InventoryFilterMelee: /* csgo_russian.txt */"Оружие ближнего боя",
  InventoryFilterMidTier: /* csgo_russian.txt */"Промежуточное",
  InventoryFilterMisc: /* csgo_russian.txt */"Прочее",
  InventoryFilterMusicKits: /* csgo_russian.txt */"Наборы музыки",
  InventoryFilterNewest: /* csgo_russian.txt */"По новизне",
  InventoryFilterPatches: /* csgo_russian.txt */"Нашивки",
  InventoryFilterPistols: /* csgo_russian.txt */"Пистолеты",
  InventoryFilterQuality: /* csgo_russian.txt */"По качеству",
  InventoryFilterRifles: /* csgo_russian.txt */"Винтовки",
  InventoryFilterSearch: /* csgo_russian.txt */"Поиск",
  InventoryFilterSouvenirCases: /* csgo_russian.txt */"Сувенирные кейсы",
  InventoryFilterStickerCapsules: /* csgo_russian.txt */"Капсулы с наклейками",
  InventoryFilterStickers: /* csgo_russian.txt */"Наклейки",
  InventoryFilterTools: /* csgo_russian.txt */"Инструменты",
  InventoryFilterType: /* csgo_russian.txt */"По типу",
  InventoryFilterWeaponCases: /* csgo_russian.txt */"Оружейные кейсы",
  InventoryItemContainsOne: /* csgo_russian.txt */"Внутри находится один из следующих предметов:",
  InventoryItemDelete: /* csgo_russian.txt */"Удалить",
  InventoryItemDeleteConfirm: /* csgo_russian.txt */"Удалить предмет",
  InventoryItemDeleteConfirmDesc: /* csgo_russian.txt */"Вы уверены, что хотите удалить этот предмет?",
  InventoryItemEdit: /* csgo_russian.txt */"Изменить",
  InventoryItemEquip: /* csgo_russian.txt */"Надеть",
  InventoryItemExterior: /* csgo_russian.txt */"Износ:",
  InventoryItemInspect: /* csgo_russian.txt */"Осмотреть",
  InventoryItemInspectFinishCatalog: /* csgo_russian.txt */"Номер в каталоге",
  InventoryItemInspectInGame: /* csgo_russian.txt */"Осмотреть в игре…",
  InventoryItemInspectPatternTemplate: /* csgo_russian.txt */"Шаблон раскраски",
  InventoryItemInspectWearRating: /* csgo_russian.txt */"Степень износа",
  InventoryItemMVPStatTrakCount: /* csgo_russian.txt */"Награды СЦИ в соревновательных играх, записанные StatTrak™:",
  InventoryItemNew: /* csgo_russian.txt */"Новое!",
  InventoryItemRareItem: /* csgo_russian.txt */"или крайне редкий особый предмет!",
  InventoryItemRarity: /* csgo_russian.txt */"Редкость:",
  InventoryItemRemovePatch: /* csgo_russian.txt */"Снять нашивку",
  InventoryItemRename: /* csgo_russian.txt */"Переименовать",
  InventoryItemRenameClearTooltip: /* csgo_russian.txt */"Начать сначала.",
  InventoryItemRenameInvalidTooltip: /* csgo_russian.txt */"Введите допустимое имя.",
  InventoryItemRenamePlaceholder: /* csgo_russian.txt */"Новое название",
  InventoryItemRenameStorageUnit: /* csgo_russian.txt */"Сменить ярлык",
  InventoryItemScrapeSticker: /* csgo_russian.txt */"Поскрести наклейку",
  InventoryItemStatTrak: /* csgo_russian.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_russian.txt */"Убийства, записанные StatTrak™:",
  InventoryItemStatTrakDesc: /* csgo_russian.txt */"На этом предмете используется технология StatTrak™, которая отслеживает определённые показатели владельца.",
  InventoryItemStorageUnitDeposit: /* csgo_russian.txt */"Поместить предметы",
  InventoryItemStorageUnitEmptyBody: /* csgo_russian.txt */"В хранилище можно поместить до {1} лишних предметов, которым не хватает места в вашем инвентаре. Предметы можно перемещать в хранилище и из него когда угодно. Также с его помощью можно упорядочить свои ценные предметы.",
  InventoryItemStorageUnitEmptyClose: /* csgo_russian.txt */"OK",
  InventoryItemStorageUnitEmptyTitle: /* csgo_russian.txt */"Хранилище пустое",
  InventoryItemStorageUnitInspect: /* csgo_russian.txt */"Осмотреть",
  InventoryItemStorageUnitRetrieve: /* csgo_russian.txt */"Извлечь предметы",
  InventoryItemSwapStatTrak: /* csgo_russian.txt */"Открыть обменник StatTrak™",
  InventoryItemTeam: /* csgo_russian.txt */"Команда:",
  InventoryItemTeamAny: /* csgo_russian.txt */"Любая",
  InventoryItemTeamCT: /* csgo_russian.txt */"Спецназ",
  InventoryItemTeamT: /* csgo_russian.txt */"Террористы",
  InventoryItemUnequip: /* csgo_russian.txt */"Снять",
  InventoryItemUnlockContainer: /* csgo_russian.txt */"Открыть контейнер",
  InventoryItemUseStorageUnit: /* csgo_russian.txt */"Активировать хранилище",
  InventorySelectAnItem: /* csgo_russian.txt */"Выберите предмет для использования с:",
  InventorySelectInspectContents: /* csgo_russian.txt */"Просмотр содержимого:",
  InventorySelectItemToDeposit: /* csgo_russian.txt */"Убрать в хранилище:",
  InventorySelectItemToRetrieve: /* csgo_russian.txt */"Извлечь предметы:",
  ItemRarityAncient: /* csgo_russian.txt */"экстраординарного типа",
  ItemRarityCommon: /* csgo_russian.txt */"базового класса",
  ItemRarityDefault: /* csgo_russian.txt */"Стандартное",
  ItemRarityImmortal: /* csgo_russian.txt */"Контрабанда",
  ItemRarityLegendary: /* csgo_russian.txt */"экзотичного вида",
  ItemRarityMythical: /* csgo_russian.txt */"примечательного типа",
  ItemRarityNameAgent: /* csgo_russian.txt */"Агент",
  ItemRarityNameC4: /* csgo_russian.txt */"C4",
  ItemRarityNameCharm: /* csgo_russian.txt */"Брелок",
  ItemRarityNameCollectible: /* csgo_russian.txt */"Сувенир",
  ItemRarityNameContainer: /* csgo_russian.txt */"Контейнер",
  ItemRarityNameContract: /* csgo_russian.txt */"Контракт",
  ItemRarityNameEquipment: /* csgo_russian.txt */"Снаряжение",
  ItemRarityNameGloves: /* csgo_russian.txt */"Перчатки",
  ItemRarityNameGraffiti: /* csgo_russian.txt */"Граффити",
  ItemRarityNameKey: /* csgo_russian.txt */"Ключ",
  ItemRarityNameKnife: /* csgo_russian.txt */"Нож",
  ItemRarityNameMachinegun: /* csgo_russian.txt */"Пулемёт",
  ItemRarityNameMusicKit: /* csgo_russian.txt */"Набор музыки",
  ItemRarityNamePatch: /* csgo_russian.txt */"Нашивка",
  ItemRarityNamePistol: /* csgo_russian.txt */"Пистолет",
  ItemRarityNameRifle: /* csgo_russian.txt */"Винтовка",
  ItemRarityNameSMG: /* csgo_russian.txt */"Пистолет-пулемёт",
  ItemRarityNameShotgun: /* csgo_russian.txt */"Дробовик",
  ItemRarityNameSniperRifle: /* csgo_russian.txt */"Снайперская винтовка",
  ItemRarityNameSticker: /* csgo_russian.txt */"Наклейка",
  ItemRarityNameTool: /* csgo_russian.txt */"Инструмент",
  ItemRarityRare: /* csgo_russian.txt */"высшего класса",
  ItemRarityUncommon: /* csgo_russian.txt */"Среднего класса",
  ItemSwapStatTrakAccept: /* csgo_russian.txt */"ПРИНЯТЬ",
  ItemSwapStatTrakClose: /* csgo_russian.txt */"Закрыть",
  ItemSwapStatTrakDesc: /* csgo_russian.txt */"Этот предмет может обменять значения StatTrak™ у двух одинаковых раскрасок предмета.",
  ItemSwapStatTrakUse: /* csgo_russian.txt */"Обменник StatTrak™",
  ItemSwapStatTrakWarn: /* csgo_russian.txt */"Этот обменник StatTrak™ может быть использован только один раз",
  ItemWeaponRarityAncient: /* csgo_russian.txt */"Тайное",
  ItemWeaponRarityCommon: /* csgo_russian.txt */"Ширпотреб",
  ItemWeaponRarityDefault: /* csgo_russian.txt */"Стандартное",
  ItemWeaponRarityImmortal: /* csgo_russian.txt */"Контрабанда",
  ItemWeaponRarityLegendary: /* csgo_russian.txt */"Засекреченное",
  ItemWeaponRarityMythical: /* csgo_russian.txt */"Запрещённое",
  ItemWeaponRarityRare: /* csgo_russian.txt */"Армейское качество",
  ItemWeaponRarityUncommon: /* csgo_russian.txt */"Промышленное качество",
  ItemWearBS: /* csgo_russian.txt */"Закалённое в боях",
  ItemWearFN: /* csgo_russian.txt */"Прямо с завода",
  ItemWearFT: /* csgo_russian.txt */"После полевых испытаний",
  ItemWearMW: /* csgo_russian.txt */"Немного поношенное",
  ItemWearWW: /* csgo_russian.txt */"Поношенное",
  RemovePatchRemove: /* csgo_russian.txt */"Удалить нашивку",
  RemovePatchRemoveDesc: /* csgo_russian.txt */"Вы уверены, что хотите снять эту нашивку с агента? Она будет уничтожена.",
  RemovePatchUse: /* csgo_russian.txt */"Снять нашивку",
  RemovePatchWarn: /* csgo_russian.txt */"Удалить нашивку с",
  RenameCancel: /* csgo_russian.txt */"Отмена",
  RenameEnterName: /* csgo_russian.txt */"Введите новое название для:",
  RenameRename: /* csgo_russian.txt */"Переименовать",
  RenameStorageUnitClose: /* csgo_russian.txt */"Закрыть",
  RenameStorageUnitEnterName: /* csgo_russian.txt */"Введите новое название для:",
  RenameStorageUnitFirstNameWarn: /* csgo_russian.txt */"Введите содержательное название для своего личного хранилища предметов.",
  RenameStorageUnitNewNameWarn: /* csgo_russian.txt */"Введите новое название для этого хранилища.",
  RenameStorageUnitRename: /* csgo_russian.txt */"Задать",
  RenameStorageUnitUse: /* csgo_russian.txt */"Изменение хранилища",
  RenameUse: /* csgo_russian.txt */"Использовать именной ярлык",
  RenameWarn: /* csgo_russian.txt */"Именной ярлык можно использовать только 1 раз",
  ScrapeStickerCancel: /* csgo_russian.txt */"Отмена",
  ScrapeStickerClose: /* csgo_russian.txt */"Закрыть",
  ScrapeStickerRemove: /* csgo_russian.txt */"Удалить наклейку",
  ScrapeStickerRemoveDesc: /* csgo_russian.txt */"Если поскрести эту наклейку еще раз, она исчезнет с предмета и будет уничтожена.",
  ScrapeStickerUse: /* csgo_russian.txt */"Поскрести наклейку",
  ScrapeStickerWarn: /* csgo_russian.txt */"Поскрести наклейку на",
  SettingsMasterVolume: /* csgo_russian.txt */"Общая громкость",
  StickerPickerRemove: /* csgo_russian.txt */"Удалить"
};
