/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const spanish = {
  ...english,
  ApplyPatchUse: /* csgo_spanish.txt */"Aplicar parche",
  ApplyPatchWarn: /* csgo_spanish.txt */"Un parche solo puede aplicarse una vez.",
  ApplyStickerCancel: /* csgo_spanish.txt */"Cancelar",
  ApplyStickerUse: /* csgo_spanish.txt */"Aplicar pegatina",
  ApplyStickerUseOn: /* csgo_spanish.txt */"Usar en",
  ApplyStickerWarn: /* csgo_spanish.txt */"Una pegatina solo puede aplicarse una vez.",
  CaseAdd: /* csgo_spanish.txt */"Añadir",
  CaseClose: /* csgo_spanish.txt */"Cerrar",
  CaseContainsOne: /* csgo_spanish.txt */"Contiene uno de los siguientes artículos:",
  CaseNeed: /* csgo_spanish.txt */"Esta acción requiere un/a",
  CaseOnceWarn: /* csgo_spanish.txt */"Este contenedor solo se puede abrir una vez",
  CaseRareItem: /* csgo_spanish.txt */"★ Artículo especial raro ★",
  CaseUnlock: /* csgo_spanish.txt */"Abrir",
  CaseUnlockContainer: /* csgo_spanish.txt */"Abrir contenedor",
  CaseUse: /* csgo_spanish.txt */"Utilizar",
  CategoryAgent: /* csgo_spanish.txt */"Agente",
  CategoryCase: /* csgo_spanish.txt */"Contenedor",
  CategoryCollectible: /* csgo_spanish.txt */"Coleccionable",
  CategoryEquipment: /* csgo_spanish.txt */"Equipamiento",
  CategoryGlove: /* csgo_spanish.txt */"Guantes",
  CategoryGraffiti: /* csgo_spanish.txt */"Grafiti",
  CategoryHeavy: /* csgo_spanish.txt */"Armas pesadas",
  CategoryKey: /* csgo_spanish.txt */"Llave",
  CategoryKnife: /* csgo_spanish.txt */"Cuchillo",
  CategoryMusicKit: /* csgo_spanish.txt */"Kit de música",
  CategoryPatch: /* csgo_spanish.txt */"Parche",
  CategoryPistol: /* csgo_spanish.txt */"Pistola",
  CategoryRifle: /* csgo_spanish.txt */"Rifle",
  CategorySMG: /* csgo_spanish.txt */"Subfusil",
  CategorySticker: /* csgo_spanish.txt */"Pegatina",
  CategoryTool: /* csgo_spanish.txt */"Herramienta",
  EditorCancel: /* csgo_spanish.txt */"Cancelar",
  EditorNametag: /* csgo_spanish.txt */"Etiqueta de nombre",
  EditorPatches: /* csgo_spanish.txt */"Parches",
  EditorQuantity: /* csgo_spanish.txt */"Cantidad",
  EditorRandom: /* csgo_spanish.txt */"Aleatorio",
  EditorReset: /* csgo_spanish.txt */"Restablecer",
  EditorSave: /* csgo_spanish.txt */"Guardar",
  EditorSeed: /* csgo_spanish.txt */"Patrón",
  EditorStatTrak: /* csgo_spanish.txt */"StatTrak™",
  EditorStickers: /* csgo_spanish.txt */"Pegatinas",
  EditorWear: /* csgo_spanish.txt */"Desgaste",
  InspectClose: /* csgo_spanish.txt */"Cerrar",
  InventoryApplyPatch: /* csgo_spanish.txt */"Aplicar parche",
  InventoryApplySticker: /* csgo_spanish.txt */"Aplicar pegatina",
  InventoryFilterAgents: /* csgo_spanish.txt */"Agentes",
  InventoryFilterAll: /* csgo_spanish.txt */"Todos",
  InventoryFilterAllEquipment: /* csgo_spanish.txt */"Todo el equipamiento",
  InventoryFilterAllGraphicArt: /* csgo_spanish.txt */"Todo el arte gráfico",
  InventoryFilterAlphabetical: /* csgo_spanish.txt */"Alfabético",
  InventoryFilterCollection: /* csgo_spanish.txt */"Colección",
  InventoryFilterContainers: /* csgo_spanish.txt */"CONTENEDORES",
  InventoryFilterDisplay: /* csgo_spanish.txt */"VITRINA",
  InventoryFilterEquipment: /* csgo_spanish.txt */"EQUIPAMIENTO",
  InventoryFilterEquipped: /* csgo_spanish.txt */"Equipado",
  InventoryFilterEverything: /* csgo_spanish.txt */"TODO",
  InventoryFilterGloves: /* csgo_spanish.txt */"Guantes",
  InventoryFilterGraffiti: /* csgo_spanish.txt */"Grafitis",
  InventoryFilterGraffitiBoxes: /* csgo_spanish.txt */"Cajas de grafitis",
  InventoryFilterGraphicArt: /* csgo_spanish.txt */"ARTE GRÁFICO",
  InventoryFilterMedals: /* csgo_spanish.txt */"Medallas",
  InventoryFilterMelee: /* csgo_spanish.txt */"Cuerpo a cuerpo",
  InventoryFilterMidTier: /* csgo_spanish.txt */"Nivel medio",
  InventoryFilterMisc: /* csgo_spanish.txt */"Miscelánea",
  InventoryFilterMusicKits: /* csgo_spanish.txt */"Kits de música",
  InventoryFilterNewest: /* csgo_spanish.txt */"Más reciente",
  InventoryFilterPatches: /* csgo_spanish.txt */"Parches",
  InventoryFilterPistols: /* csgo_spanish.txt */"Pistolas",
  InventoryFilterQuality: /* csgo_spanish.txt */"Calidad",
  InventoryFilterRifles: /* csgo_spanish.txt */"Rifles",
  InventoryFilterSearch: /* csgo_spanish.txt */"Escribe la búsqueda aquí",
  InventoryFilterSouvenirCases: /* csgo_spanish.txt */"Paquetes regalo",
  InventoryFilterStickerCapsules: /* csgo_spanish.txt */"Cápsulas de pegatinas",
  InventoryFilterStickers: /* csgo_spanish.txt */"Pegatinas",
  InventoryFilterTools: /* csgo_spanish.txt */"Herramientas",
  InventoryFilterType: /* csgo_spanish.txt */"Tipo",
  InventoryFilterWeaponCases: /* csgo_spanish.txt */"Cajas de armas",
  InventoryItemContainsOne: /* csgo_spanish.txt */"Contiene uno de los siguientes artículos:",
  InventoryItemDelete: /* csgo_spanish.txt */"Borrar",
  InventoryItemEdit: /* csgo_spanish.txt */"Modificar",
  InventoryItemEquip: /* csgo_spanish.txt */"Equipar",
  InventoryItemExterior: /* csgo_spanish.txt */"Exterior:",
  InventoryItemInspect: /* csgo_spanish.txt */"Inspeccionar",
  InventoryItemInspectFinishCatalog: /* csgo_spanish.txt */"Catálogo de acabados",
  InventoryItemInspectInGame: /* csgo_spanish.txt */"Inspeccionar en el juego...",
  InventoryItemInspectPatternTemplate: /* csgo_spanish.txt */"Plantilla de patrón",
  InventoryItemInspectWearRating: /* csgo_spanish.txt */"Índice de desgaste",
  InventoryItemMVPStatTrakCount: /* csgo_spanish.txt */"Veces JMV en competitivo oficial de StatTrak™:",
  InventoryItemNew: /* csgo_spanish.txt */"¡Nuevo!",
  InventoryItemRareItem: /* csgo_spanish.txt */"¡o un artículo especial extraordinariamente raro!",
  InventoryItemRarity: /* csgo_spanish.txt */"Rareza:",
  InventoryItemRemovePatch: /* csgo_spanish.txt */"Eliminar parche",
  InventoryItemRename: /* csgo_spanish.txt */"Renombrar",
  InventoryItemRenameStorageUnit: /* csgo_spanish.txt */"Cambiar etiqueta",
  InventoryItemScrapeSticker: /* csgo_spanish.txt */"Raspar pegatina",
  InventoryItemStatTrak: /* csgo_spanish.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_spanish.txt */"Víctimas confirmadas por StatTrak™:",
  InventoryItemStatTrakDesc: /* csgo_spanish.txt */"Este artículo cuenta con el dispositivo StatTrak™, el cual registra ciertas estadísticas cuando lo equipa su propietario.",
  InventoryItemStorageUnitDeposit: /* csgo_spanish.txt */"Depositar artículos",
  InventoryItemStorageUnitEmptyBody: /* csgo_spanish.txt */"Esta unidad de almacenamiento te permite guardar hasta {1} artículos excedentes que de otro modo superarían el límite del inventario. La unidad de almacenamiento seleccionada está vacía actualmente. En cualquier momento, puedes transferir artículos del inventario a esta unidad, devolverlos al inventario o simplemente utilizarla para organizar tus colecciones.",
  InventoryItemStorageUnitEmptyClose: /* csgo_spanish.txt */"Aceptar",
  InventoryItemStorageUnitEmptyTitle: /* csgo_spanish.txt */"Unidad de almacenamiento vacía",
  InventoryItemStorageUnitInspect: /* csgo_spanish.txt */"Inspeccionar",
  InventoryItemStorageUnitRetrieve: /* csgo_spanish.txt */"Recuperar artículos",
  InventoryItemSwapStatTrak: /* csgo_spanish.txt */"Abrir herramienta de intercambio de StatTrak™",
  InventoryItemTeam: /* csgo_spanish.txt */"Equipo:",
  InventoryItemTeamAny: /* csgo_spanish.txt */"Ambos",
  InventoryItemTeamCT: /* csgo_spanish.txt */"Antiterrorista",
  InventoryItemTeamT: /* csgo_spanish.txt */"Terrorista",
  InventoryItemUnequip: /* csgo_spanish.txt */"Desequipar",
  InventoryItemUnlockContainer: /* csgo_spanish.txt */"Abrir paquete",
  InventoryItemUseStorageUnit: /* csgo_spanish.txt */"Comenzar a usar esta unidad",
  InventorySelectAnItem: /* csgo_spanish.txt */"Selecciona un artículo con el que usarlo:",
  InventorySelectInspectContents: /* csgo_spanish.txt */"Viendo el contenido de",
  InventorySelectItemToDeposit: /* csgo_spanish.txt */"Selecciona los artículos que deseas transferir a",
  InventorySelectItemToRetrieve: /* csgo_spanish.txt */"Selecciona los artículos que deseas recuperar de",
  ItemRarityAncient: /* csgo_spanish.txt */"de aspecto extraordinario",
  ItemRarityCommon: /* csgo_spanish.txt */"de grado básico",
  ItemRarityDefault: /* csgo_spanish.txt */"por defecto",
  ItemRarityImmortal: /* csgo_spanish.txt */"de contrabando",
  ItemRarityLegendary: /* csgo_spanish.txt */"de aspecto exótico",
  ItemRarityMythical: /* csgo_spanish.txt */"singular",
  ItemRarityNameAgent: /* csgo_spanish.txt */"Agente",
  ItemRarityNameCollectible: /* csgo_spanish.txt */"Coleccionable",
  ItemRarityNameContainer: /* csgo_spanish.txt */"Contenedor",
  ItemRarityNameContract: /* csgo_spanish.txt */"Contrato",
  ItemRarityNameEquipment: /* csgo_spanish.txt */"Equipamiento",
  ItemRarityNameGloves: /* csgo_spanish.txt */"Guantes",
  ItemRarityNameGraffiti: /* csgo_spanish.txt */"Grafiti",
  ItemRarityNameKey: /* csgo_spanish.txt */"Llave",
  ItemRarityNameKnife: /* csgo_spanish.txt */"Cuchillo",
  ItemRarityNameMachinegun: /* csgo_spanish.txt */"Ametralladora",
  ItemRarityNameMusicKit: /* csgo_spanish.txt */"Kit de música",
  ItemRarityNamePatch: /* csgo_spanish.txt */"Parche",
  ItemRarityNamePistol: /* csgo_spanish.txt */"Pistola",
  ItemRarityNameRifle: /* csgo_spanish.txt */"Rifle",
  ItemRarityNameSMG: /* csgo_spanish.txt */"Subfusil",
  ItemRarityNameShotgun: /* csgo_spanish.txt */"Escopeta",
  ItemRarityNameSniperRifle: /* csgo_spanish.txt */"Rifle de francotirador",
  ItemRarityNameSticker: /* csgo_spanish.txt */"Pegatina",
  ItemRarityNameTool: /* csgo_spanish.txt */"Herramienta",
  ItemRarityRare: /* csgo_spanish.txt */"de grado alto",
  ItemRarityUncommon: /* csgo_spanish.txt */"de grado medio",
  ItemSwapStatTrakAccept: /* csgo_spanish.txt */"ACEPTAR",
  ItemSwapStatTrakClose: /* csgo_spanish.txt */"Cerrar",
  ItemSwapStatTrakDesc: /* csgo_spanish.txt */"Este artículo intercambia los valores StatTrak™ entre dos artículos del mismo tipo.",
  ItemSwapStatTrakUse: /* csgo_spanish.txt */"Herramienta de intercambio de StatTrak™",
  ItemSwapStatTrakWarn: /* csgo_spanish.txt */"Esta herramienta de intercambio de StatTrak™ solo se puede utilizar una vez",
  ItemWeaponRarityAncient: /* csgo_spanish.txt */"de aspecto encubierto",
  ItemWeaponRarityCommon: /* csgo_spanish.txt */"de grado de consumidor",
  ItemWeaponRarityDefault: /* csgo_spanish.txt */"normal",
  ItemWeaponRarityImmortal: /* csgo_spanish.txt */"de contrabando",
  ItemWeaponRarityLegendary: /* csgo_spanish.txt */"de tipo clasificado",
  ItemWeaponRarityMythical: /* csgo_spanish.txt */"de tipo restringido",
  ItemWeaponRarityRare: /* csgo_spanish.txt */"de grado militar",
  ItemWeaponRarityUncommon: /* csgo_spanish.txt */"de grado industrial",
  ItemWearBS: /* csgo_spanish.txt */"Deplorable",
  ItemWearFN: /* csgo_spanish.txt */"Recién fabricado",
  ItemWearFT: /* csgo_spanish.txt */"Algo desgastado",
  ItemWearMW: /* csgo_spanish.txt */"Casi nuevo",
  ItemWearWW: /* csgo_spanish.txt */"Bastante desgastado",
  RemovePatchRemove: /* csgo_spanish.txt */"Eliminar parche",
  RemovePatchRemoveDesc: /* csgo_spanish.txt */"Por favor, confirma que deseas quitar este parche del agente. El parche retirado se destruirá.",
  RemovePatchUse: /* csgo_spanish.txt */"Eliminar parche",
  RemovePatchWarn: /* csgo_spanish.txt */"Quitar un parche de",
  RenameCancel: /* csgo_spanish.txt */"Cancelar",
  RenameEnterName: /* csgo_spanish.txt */"Introduce un nuevo nombre para tu",
  RenameRename: /* csgo_spanish.txt */"Renombrar",
  RenameStorageUnitClose: /* csgo_spanish.txt */"Cerrar",
  RenameStorageUnitEnterName: /* csgo_spanish.txt */"Introduce un nuevo nombre para tu",
  RenameStorageUnitFirstNameWarn: /* csgo_spanish.txt */"Introduce una etiqueta descriptiva para tu unidad de almacenamiento personal y empieza a utilizarla para guardar artículos.",
  RenameStorageUnitNewNameWarn: /* csgo_spanish.txt */"Introduce una nueva etiqueta descriptiva para esta unidad de almacenamiento.",
  RenameStorageUnitRename: /* csgo_spanish.txt */"Personalizar",
  RenameStorageUnitUse: /* csgo_spanish.txt */"Personaliza tu unidad de almacenamiento",
  RenameUse: /* csgo_spanish.txt */"Usar etiqueta de nombre",
  RenameWarn: /* csgo_spanish.txt */"Las etiquetas de nombre solo pueden utilizarse una vez",
  ScrapeStickerCancel: /* csgo_spanish.txt */"Cancelar",
  ScrapeStickerClose: /* csgo_spanish.txt */"Cerrar",
  ScrapeStickerRemove: /* csgo_spanish.txt */"Quitar pegatina",
  ScrapeStickerRemoveDesc: /* csgo_spanish.txt */"Raspar más esta pegatina hará que ésta sea eliminada del artículo y a continuación destruida.",
  ScrapeStickerUse: /* csgo_spanish.txt */"Raspar pegatina",
  ScrapeStickerWarn: /* csgo_spanish.txt */"Raspar una pegatina de",
  StickerPickerRemove: /* csgo_spanish.txt */"Eliminar"
};
