/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const swedish = {
  ...english,
  ApplyPatchUse: /* csgo_swedish.txt */"Fäst tygmärke",
  ApplyPatchWarn: /* csgo_swedish.txt */"Ett tygmärke kan endast användas en gång",
  ApplyStickerCancel: /* csgo_swedish.txt */"Avbryt",
  ApplyStickerUse: /* csgo_swedish.txt */"Fäst klistermärke",
  ApplyStickerUseOn: /* csgo_swedish.txt */"Använd på",
  ApplyStickerWarn: /* csgo_swedish.txt */"Ett klistermärke kan bara användas en gång",
  CaseAdd: /* csgo_swedish.txt */"Lägg till",
  CaseClose: /* csgo_swedish.txt */"Stäng",
  CaseContainsOne: /* csgo_swedish.txt */"Innehåller ett av följande:",
  CaseNeed: /* csgo_swedish.txt */"Denna åtgärd kräver en",
  CaseOnceWarn: /* csgo_swedish.txt */"Denna behållare kan endast öppnas en gång",
  CaseRareItem: /* csgo_swedish.txt */"★ Sällsynt specialföremål ★",
  CaseUnlock: /* csgo_swedish.txt */"Lås upp",
  CaseUnlockContainer: /* csgo_swedish.txt */"Lås upp behållare",
  CaseUse: /* csgo_swedish.txt */"Använd",
  CategoryAgent: /* csgo_swedish.txt */"Agent",
  CategoryCase: /* csgo_swedish.txt */"Behållare",
  CategoryCollectible: /* csgo_swedish.txt */"Samlingsobjekt",
  CategoryEquipment: /* csgo_swedish.txt */"Utrustning",
  CategoryGlove: /* csgo_swedish.txt */"Handskar",
  CategoryGraffiti: /* csgo_swedish.txt */"Graffiti",
  CategoryHeavy: /* csgo_swedish.txt */"Tungt",
  CategoryKey: /* csgo_swedish.txt */"Nyckel",
  CategoryKnife: /* csgo_swedish.txt */"Kniv",
  CategoryMusicKit: /* csgo_swedish.txt */"Musikpaket",
  CategoryPatch: /* csgo_swedish.txt */"Tygmärke",
  CategoryPistol: /* csgo_swedish.txt */"Pistol",
  CategoryRifle: /* csgo_swedish.txt */"Gevär",
  CategorySMG: /* csgo_swedish.txt */"SMG",
  CategorySticker: /* csgo_swedish.txt */"Klistermärke",
  CategoryTool: /* csgo_swedish.txt */"Verktyg",
  EditorCancel: /* csgo_swedish.txt */"Avbryt",
  EditorNametag: /* csgo_swedish.txt */"Namnplåt",
  EditorPatches: /* csgo_swedish.txt */"Tygmärken",
  EditorQuantity: /* csgo_swedish.txt */"Antal",
  EditorRandom: /* csgo_swedish.txt */"Slumpmässig",
  EditorReset: /* csgo_swedish.txt */"Återställ",
  EditorSave: /* csgo_swedish.txt */"Spara",
  EditorSeed: /* csgo_swedish.txt */"Mönster",
  EditorStatTrak: /* csgo_swedish.txt */"StatTrak™",
  EditorStickers: /* csgo_swedish.txt */"Klistermärken",
  EditorWear: /* csgo_swedish.txt */"Slitage",
  InspectClose: /* csgo_swedish.txt */"Stäng",
  InventoryApplyPatch: /* csgo_swedish.txt */"Fäst tygmärke",
  InventoryApplySticker: /* csgo_swedish.txt */"Applicera klistermärke",
  InventoryFilterAgents: /* csgo_swedish.txt */"Agenter",
  InventoryFilterAll: /* csgo_swedish.txt */"Alla",
  InventoryFilterAllEquipment: /* csgo_swedish.txt */"All utrustning",
  InventoryFilterAllGraphicArt: /* csgo_swedish.txt */"All grafisk konst",
  InventoryFilterAlphabetical: /* csgo_swedish.txt */"Alfabetiskt",
  InventoryFilterCollection: /* csgo_swedish.txt */"Kollektion",
  InventoryFilterContainers: /* csgo_swedish.txt */"BEHÅLLARE",
  InventoryFilterDisplay: /* csgo_swedish.txt */"UPPVISNING",
  InventoryFilterEquipment: /* csgo_swedish.txt */"UTRUSTNING",
  InventoryFilterEquipped: /* csgo_swedish.txt */"Utrustad",
  InventoryFilterEverything: /* csgo_swedish.txt */"ALLT",
  InventoryFilterGloves: /* csgo_swedish.txt */"Handskar",
  InventoryFilterGraffiti: /* csgo_swedish.txt */"Graffiti",
  InventoryFilterGraffitiBoxes: /* csgo_swedish.txt */"Graffitilådor",
  InventoryFilterGraphicArt: /* csgo_swedish.txt */"GRAFIK",
  InventoryFilterMedals: /* csgo_swedish.txt */"Medaljer",
  InventoryFilterMelee: /* csgo_swedish.txt */"Närstrid",
  InventoryFilterMidTier: /* csgo_swedish.txt */"Mid-Tier",
  InventoryFilterMisc: /* csgo_swedish.txt */"Övrigt",
  InventoryFilterMusicKits: /* csgo_swedish.txt */"Musikpaket",
  InventoryFilterNewest: /* csgo_swedish.txt */"Nyaste",
  InventoryFilterPatches: /* csgo_swedish.txt */"Tygmärken",
  InventoryFilterPistols: /* csgo_swedish.txt */"Pistoler",
  InventoryFilterQuality: /* csgo_swedish.txt */"Kvalitet",
  InventoryFilterRifles: /* csgo_swedish.txt */"Gevär",
  InventoryFilterSearch: /* csgo_swedish.txt */"Skriv sökning här",
  InventoryFilterSouvenirCases: /* csgo_swedish.txt */"Souvenirlådor",
  InventoryFilterStickerCapsules: /* csgo_swedish.txt */"Klistermärkeskapslar",
  InventoryFilterStickers: /* csgo_swedish.txt */"Klistermärken",
  InventoryFilterTools: /* csgo_swedish.txt */"Verktyg",
  InventoryFilterType: /* csgo_swedish.txt */"Typ",
  InventoryFilterWeaponCases: /* csgo_swedish.txt */"Vapenlådor",
  InventoryItemContainsOne: /* csgo_swedish.txt */"Innehåller ett av följande:",
  InventoryItemDelete: /* csgo_swedish.txt */"Radera",
  InventoryItemEdit: /* csgo_swedish.txt */"Ändra",
  InventoryItemEquip: /* csgo_swedish.txt */"Utrusta",
  InventoryItemExterior: /* csgo_swedish.txt */"Exteriör:",
  InventoryItemInspect: /* csgo_swedish.txt */"Inspektera",
  InventoryItemInspectFinishCatalog: /* csgo_swedish.txt */"Ytbehandlingskatalog",
  InventoryItemInspectInGame: /* csgo_swedish.txt */"Inspektera i spelet...",
  InventoryItemInspectPatternTemplate: /* csgo_swedish.txt */"Mönstermall",
  InventoryItemInspectWearRating: /* csgo_swedish.txt */"Slitagegradering",
  InventoryItemMVPStatTrakCount: /* csgo_swedish.txt */"StatTrak™ Officiella tävlingsinriktade MVPs:",
  InventoryItemNew: /* csgo_swedish.txt */"Ny!",
  InventoryItemRareItem: /* csgo_swedish.txt */"eller ett ytterst ovanligt specialföremål!",
  InventoryItemRarity: /* csgo_swedish.txt */"Raritet:",
  InventoryItemRemovePatch: /* csgo_swedish.txt */"Ta bort tygmärke",
  InventoryItemRename: /* csgo_swedish.txt */"Byt namn på",
  InventoryItemRenameStorageUnit: /* csgo_swedish.txt */"Ändra etikett",
  InventoryItemScrapeSticker: /* csgo_swedish.txt */"Skrapa klistermärke",
  InventoryItemStatTrak: /* csgo_swedish.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_swedish.txt */"StatTrak™ - Antal dödade:",
  InventoryItemStatTrakDesc: /* csgo_swedish.txt */"Det här föremålet har StatTrak™-teknologi, som räknar viss statistik när det används av sin ägare.",
  InventoryItemStorageUnitDeposit: /* csgo_swedish.txt */"Lagra föremål",
  InventoryItemStorageUnitEmptyBody: /* csgo_swedish.txt */"Lagringsenheten låter dig lagra upp till {1} av dina överskottsföremål som annars skulle överskrida utrymmet i ditt förråd. Den valda lagringsenheten är för närvarande tom. Du kan närsomhelst flytta föremål från ditt förråd till denna lagringsenhet, hämta tillbaka föremål till ditt förråd, eller helt enkelt använda den till att organisera dina samlarobjekt.",
  InventoryItemStorageUnitEmptyClose: /* csgo_swedish.txt */"OK",
  InventoryItemStorageUnitEmptyTitle: /* csgo_swedish.txt */"Tom lagringsenhet",
  InventoryItemStorageUnitInspect: /* csgo_swedish.txt */"Inspektera",
  InventoryItemStorageUnitRetrieve: /* csgo_swedish.txt */"Hämta föremål",
  InventoryItemSwapStatTrak: /* csgo_swedish.txt */"Öppna StatTrak™-bytesverktyg",
  InventoryItemTeam: /* csgo_swedish.txt */"Lag:",
  InventoryItemTeamAny: /* csgo_swedish.txt */"Alla",
  InventoryItemTeamCT: /* csgo_swedish.txt */"Antiterrorist",
  InventoryItemTeamT: /* csgo_swedish.txt */"Terrorist",
  InventoryItemUnequip: /* csgo_swedish.txt */"Avrusta",
  InventoryItemUnlockContainer: /* csgo_swedish.txt */"Lås upp behållare",
  InventoryItemUseStorageUnit: /* csgo_swedish.txt */"Börja använda denna enhet",
  InventorySelectAnItem: /* csgo_swedish.txt */"Välj ett föremål som ska användas med:",
  InventorySelectInspectContents: /* csgo_swedish.txt */"Inspekterar innehåll i",
  InventorySelectItemToDeposit: /* csgo_swedish.txt */"Välj föremål att lagra i",
  InventorySelectItemToRetrieve: /* csgo_swedish.txt */"Välj föremål att hämta från",
  ItemRarityAncient: /* csgo_swedish.txt */"Extraordinär",
  ItemRarityCommon: /* csgo_swedish.txt */"Grundkvalitet",
  ItemRarityDefault: /* csgo_swedish.txt */"Standard",
  ItemRarityImmortal: /* csgo_swedish.txt */"Smuggelgods",
  ItemRarityLegendary: /* csgo_swedish.txt */"Exotisk",
  ItemRarityMythical: /* csgo_swedish.txt */"Enastående",
  ItemRarityNameAgent: /* csgo_swedish.txt */"Agent",
  ItemRarityNameCollectible: /* csgo_swedish.txt */"Samlingsobjekt",
  ItemRarityNameContainer: /* csgo_swedish.txt */"Behållare",
  ItemRarityNameContract: /* csgo_swedish.txt */"Kontrakt",
  ItemRarityNameEquipment: /* csgo_swedish.txt */"Utrustning",
  ItemRarityNameGloves: /* csgo_swedish.txt */"Handskar",
  ItemRarityNameGraffiti: /* csgo_swedish.txt */"Graffiti",
  ItemRarityNameKey: /* csgo_swedish.txt */"Nyckel",
  ItemRarityNameKnife: /* csgo_swedish.txt */"Kniv",
  ItemRarityNameMachinegun: /* csgo_swedish.txt */"Maskingevär",
  ItemRarityNameMusicKit: /* csgo_swedish.txt */"Musikpaket",
  ItemRarityNamePatch: /* csgo_swedish.txt */"Tygmärke",
  ItemRarityNamePistol: /* csgo_swedish.txt */"Pistol",
  ItemRarityNameRifle: /* csgo_swedish.txt */"Gevär",
  ItemRarityNameSMG: /* csgo_swedish.txt */"SMG",
  ItemRarityNameShotgun: /* csgo_swedish.txt */"Hagelgevär",
  ItemRarityNameSniperRifle: /* csgo_swedish.txt */"Prickskyttegevär",
  ItemRarityNameSticker: /* csgo_swedish.txt */"Klistermärke",
  ItemRarityNameTool: /* csgo_swedish.txt */"Verktyg",
  ItemRarityRare: /* csgo_swedish.txt */"Högkvalitet",
  ItemRarityUncommon: /* csgo_swedish.txt */"Medelvärdig",
  ItemSwapStatTrakAccept: /* csgo_swedish.txt */"ACCEPTERA",
  ItemSwapStatTrakClose: /* csgo_swedish.txt */"Stäng",
  ItemSwapStatTrakDesc: /* csgo_swedish.txt */"Detta föremål byter StatTrak™-värden mellan två likadana föremålstyper.",
  ItemSwapStatTrakUse: /* csgo_swedish.txt */"Bytesverktyg för StatTrak™",
  ItemSwapStatTrakWarn: /* csgo_swedish.txt */"Detta StatTrak™-bytesverktyg kan bara användas en gång",
  ItemWeaponRarityAncient: /* csgo_swedish.txt */"Konfidentiell",
  ItemWeaponRarityCommon: /* csgo_swedish.txt */"Konsumentklass",
  ItemWeaponRarityDefault: /* csgo_swedish.txt */"Standard",
  ItemWeaponRarityImmortal: /* csgo_swedish.txt */"Smuggelgods",
  ItemWeaponRarityLegendary: /* csgo_swedish.txt */"Sekretessbelagd",
  ItemWeaponRarityMythical: /* csgo_swedish.txt */"Begränsad",
  ItemWeaponRarityRare: /* csgo_swedish.txt */"Militärklass",
  ItemWeaponRarityUncommon: /* csgo_swedish.txt */"Industriklass",
  ItemWearBS: /* csgo_swedish.txt */"Stridsärrad",
  ItemWearFN: /* csgo_swedish.txt */"Fabriksny",
  ItemWearFT: /* csgo_swedish.txt */"Testad i fält",
  ItemWearMW: /* csgo_swedish.txt */"Minimalt slitage",
  ItemWearWW: /* csgo_swedish.txt */"Välanvänd",
  RemovePatchRemove: /* csgo_swedish.txt */"Ta bort tygmärke",
  RemovePatchRemoveDesc: /* csgo_swedish.txt */"Bekräfta att du vill ta bort det här tygmärket från din agent. Det borttagna tygmärket kommer att förstöras.",
  RemovePatchUse: /* csgo_swedish.txt */"Ta bort tygmärke",
  RemovePatchWarn: /* csgo_swedish.txt */"Ta bort ett tygmärke från",
  RenameCancel: /* csgo_swedish.txt */"Avbryt",
  RenameEnterName: /* csgo_swedish.txt */"Ange ett nytt namn till:",
  RenameRename: /* csgo_swedish.txt */"Byt namn på",
  RenameStorageUnitClose: /* csgo_swedish.txt */"Stäng",
  RenameStorageUnitEnterName: /* csgo_swedish.txt */"Ange ett nytt namn till:",
  RenameStorageUnitFirstNameWarn: /* csgo_swedish.txt */"Ange en beskrivande etikett åt din personliga lagringsenhet och börja använda den till att lagra föremål.",
  RenameStorageUnitNewNameWarn: /* csgo_swedish.txt */"Ange en beskrivande etikett åt denna lagringsenhet.",
  RenameStorageUnitRename: /* csgo_swedish.txt */"Anpassa",
  RenameStorageUnitUse: /* csgo_swedish.txt */"Anpassa din lagringsenhet",
  RenameUse: /* csgo_swedish.txt */"Använd namnplåt",
  RenameWarn: /* csgo_swedish.txt */"En namnplåt kan endast användas en gång",
  ScrapeStickerCancel: /* csgo_swedish.txt */"Avbryt",
  ScrapeStickerClose: /* csgo_swedish.txt */"Stäng",
  ScrapeStickerRemove: /* csgo_swedish.txt */"Ta bort klistermärket",
  ScrapeStickerRemoveDesc: /* csgo_swedish.txt */"Om du skrapar bort mer av det här klistermärket tas det bort från föremålet och förstörs.",
  ScrapeStickerUse: /* csgo_swedish.txt */"Skrapa klistermärke",
  ScrapeStickerWarn: /* csgo_swedish.txt */"Skrapa ett klistermärke från",
  StickerPickerRemove: /* csgo_swedish.txt */"Ta bort"
};
