/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const thai = {
  ...english,
  ApplyPatchUse: /* csgo_thai.txt */"ใช้งานแพตช์ปัก",
  ApplyPatchWarn: /* csgo_thai.txt */"แพตช์ปักสามารถใช้ได้เพียงครั้งเดียว",
  ApplyStickerCancel: /* csgo_thai.txt */"ยกเลิก",
  ApplyStickerUse: /* csgo_thai.txt */"ใช้งานสติกเกอร์",
  ApplyStickerUseOn: /* csgo_thai.txt */"ใช้กับ",
  ApplyStickerWarn: /* csgo_thai.txt */"สติกเกอร์สามารถใช้ได้เพียงครั้งเดียว",
  CaseAdd: /* csgo_thai.txt */"เพิ่ม",
  CaseClose: /* csgo_thai.txt */"ปิด",
  CaseContainsOne: /* csgo_thai.txt */"บรรจุหนึ่งในไอเท็มต่อไปนี้:",
  CaseNeed: /* csgo_thai.txt */"การดำเนินการนี้ต้องใช้",
  CaseOnceWarn: /* csgo_thai.txt */"กล่องนี้สามารถเปิดได้เพียงครั้งเดียว",
  CaseRareItem: /* csgo_thai.txt */"★ ไอเท็มพิเศษหายาก ★",
  CaseUnlock: /* csgo_thai.txt */"ปลดล็อค",
  CaseUnlockContainer: /* csgo_thai.txt */"ปลดล็อคบรรจุภัณฑ์",
  CaseUse: /* csgo_thai.txt */"ใช้",
  CategoryAgent: /* csgo_thai.txt */"เจ้าหน้าที่",
  CategoryCase: /* csgo_thai.txt */"กล่อง",
  CategoryCollectible: /* csgo_thai.txt */"ของสะสม",
  CategoryEquipment: /* csgo_thai.txt */"อุปกรณ์",
  CategoryGlove: /* csgo_thai.txt */"ถุงมือ",
  CategoryGraffiti: /* csgo_thai.txt */"กราฟฟิตี้",
  CategoryHeavy: /* csgo_thai.txt */"ปืนกลหนัก",
  CategoryKey: /* csgo_thai.txt */"กุญแจ",
  CategoryKnife: /* csgo_thai.txt */"มีด",
  CategoryMusicKit: /* csgo_thai.txt */"ชุดอุปกรณ์เพลง",
  CategoryPatch: /* csgo_thai.txt */"แพตช์ปัก",
  CategoryPistol: /* csgo_thai.txt */"ปืนพก",
  CategoryRifle: /* csgo_thai.txt */"ปืนไรเฟิล",
  CategorySMG: /* csgo_thai.txt */"ปืนกลมือ",
  CategorySticker: /* csgo_thai.txt */"สติกเกอร์",
  CategoryTool: /* csgo_thai.txt */"เครื่องมือ",
  EditorCancel: /* csgo_thai.txt */"ยกเลิก",
  EditorNametag: /* csgo_thai.txt */"ป้ายชื่อ",
  EditorPatches: /* csgo_thai.txt */"แพตช์ปัก",
  EditorQuantity: /* csgo_thai.txt */"จำนวน",
  EditorRandom: /* csgo_thai.txt */"สุ่ม",
  EditorReset: /* csgo_thai.txt */"รีเซ็ต",
  EditorSave: /* csgo_thai.txt */"บันทึก",
  EditorSeed: /* csgo_thai.txt */"รูปแบบ",
  EditorStatTrak: /* csgo_thai.txt */"StatTrak™",
  EditorStickers: /* csgo_thai.txt */"สติกเกอร์",
  EditorWear: /* csgo_thai.txt */"สวมใส่",
  InspectClose: /* csgo_thai.txt */"ปิด",
  InventoryApplyPatch: /* csgo_thai.txt */"ใช้งานแพตช์ปัก",
  InventoryApplySticker: /* csgo_thai.txt */"ใช้งานสติกเกอร์",
  InventoryFilterAgents: /* csgo_thai.txt */"เจ้าหน้าที่",
  InventoryFilterAll: /* csgo_thai.txt */"ทั้งหมด",
  InventoryFilterAllEquipment: /* csgo_thai.txt */"อุปกรณ์ทั้งหมด",
  InventoryFilterAllGraphicArt: /* csgo_thai.txt */"อาร์ตเวิร์กกราฟิกทั้งหมด",
  InventoryFilterAlphabetical: /* csgo_thai.txt */"ตามลำดับตัวอักษร",
  InventoryFilterCollection: /* csgo_thai.txt */"ชุดสะสม",
  InventoryFilterContainers: /* csgo_thai.txt */"กล่อง",
  InventoryFilterDisplay: /* csgo_thai.txt */"แสดง",
  InventoryFilterEquipment: /* csgo_thai.txt */"อุปกรณ์",
  InventoryFilterEquipped: /* csgo_thai.txt */"สวมใส่อยู่",
  InventoryFilterEverything: /* csgo_thai.txt */"ทั้งหมด",
  InventoryFilterGloves: /* csgo_thai.txt */"ถุงมือ",
  InventoryFilterGraffiti: /* csgo_thai.txt */"กราฟฟิตี้",
  InventoryFilterGraffitiBoxes: /* csgo_thai.txt */"กล่องกราฟฟิตี้",
  InventoryFilterGraphicArt: /* csgo_thai.txt */"อาร์ตเวิร์กกราฟิก",
  InventoryFilterMedals: /* csgo_thai.txt */"เหรียญรางวัล",
  InventoryFilterMelee: /* csgo_thai.txt */"ระยะประชิด",
  InventoryFilterMidTier: /* csgo_thai.txt */"ปืนระดับกลาง",
  InventoryFilterMisc: /* csgo_thai.txt */"เบ็ดเตล็ด",
  InventoryFilterMusicKits: /* csgo_thai.txt */"ชุดอุปกรณ์เพลง",
  InventoryFilterNewest: /* csgo_thai.txt */"ใหม่ล่าสุด",
  InventoryFilterPatches: /* csgo_thai.txt */"แพตช์ปัก",
  InventoryFilterPistols: /* csgo_thai.txt */"ปินพก",
  InventoryFilterQuality: /* csgo_thai.txt */"คุณภาพ",
  InventoryFilterRifles: /* csgo_thai.txt */"ปืนไรเฟิล",
  InventoryFilterSearch: /* csgo_thai.txt */"พิมพ์คำค้นหาที่นี่",
  InventoryFilterSouvenirCases: /* csgo_thai.txt */"กล่องของที่ระลึก",
  InventoryFilterStickerCapsules: /* csgo_thai.txt */"แคปซูลสติกเกอร์",
  InventoryFilterStickers: /* csgo_thai.txt */"สติกเกอร์",
  InventoryFilterTools: /* csgo_thai.txt */"เครื่องมือ",
  InventoryFilterType: /* csgo_thai.txt */"ประเภท",
  InventoryFilterWeaponCases: /* csgo_thai.txt */"กล่องอาวุธ",
  InventoryItemContainsOne: /* csgo_thai.txt */"บรรจุหนึ่งในไอเท็มต่อไปนี้:",
  InventoryItemDelete: /* csgo_thai.txt */"ลบ",
  InventoryItemEdit: /* csgo_thai.txt */"แก้ไข",
  InventoryItemEquip: /* csgo_thai.txt */"สวมใส่",
  InventoryItemExterior: /* csgo_thai.txt */"สภาพภายนอก:",
  InventoryItemInspect: /* csgo_thai.txt */"ตรวจสอบ",
  InventoryItemInspectFinishCatalog: /* csgo_thai.txt */"แค็ตตาล็อกการลงสี",
  InventoryItemInspectInGame: /* csgo_thai.txt */"ตรวจสอบในเกม...",
  InventoryItemInspectPatternTemplate: /* csgo_thai.txt */"แม่แบบของรูปแบบ",
  InventoryItemInspectWearRating: /* csgo_thai.txt */"ระดับการสึกหรอ",
  InventoryItemMVPStatTrakCount: /* csgo_thai.txt */"จำนวน MVP แมตช์แข่งขันอย่างเป็นทางการของ StatTrak™:",
  InventoryItemNew: /* csgo_thai.txt */"ใหม่!",
  InventoryItemRareItem: /* csgo_thai.txt */"หรือไอเท็มพิเศษหายากมาก!",
  InventoryItemRarity: /* csgo_thai.txt */"ความหายาก:",
  InventoryItemRemovePatch: /* csgo_thai.txt */"ถอดแพตช์ปัก",
  InventoryItemRename: /* csgo_thai.txt */"เปลี่ยนชื่อ",
  InventoryItemRenameStorageUnit: /* csgo_thai.txt */"เปลี่ยนป้ายชื่อ",
  InventoryItemScrapeSticker: /* csgo_thai.txt */"ขูดสติกเกอร์",
  InventoryItemStatTrak: /* csgo_thai.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_thai.txt */"StatTrak™ ยืนยันการสังหาร:",
  InventoryItemStatTrakDesc: /* csgo_thai.txt */"ไอเท็มนี้มีคุณสมบัติเทคโนโลยี StatTrak™ ซึ่งจะคอยติดตามสถิติต่าง ๆ เมื่อเจ้าของสวมใส่อยู่",
  InventoryItemStorageUnitDeposit: /* csgo_thai.txt */"ฝากไอเท็ม",
  InventoryItemStorageUnitEmptyBody: /* csgo_thai.txt */"กล่องเก็บของทำให้คุณสามารถเก็บไอเท็มส่วนเกินของคุณที่เกินขีดจำกัดของช่องเก็บของได้ถึง {1} ชิ้น กล่องเก็บของที่เลือกไว้ในขณะนี้ว่างเปล่าอยู่ คุณสามารถย้ายไอเท็มจากช่องเก็บของของคุณไปยังกล่องเก็บของ เอาไอเท็มคืนกลับไปยังช่องเก็บของ หรือใช้กล่องเก็บของเพื่อจัดการของสะสมของคุณได้ทุกเวลา",
  InventoryItemStorageUnitEmptyClose: /* csgo_thai.txt */"ตกลง",
  InventoryItemStorageUnitEmptyTitle: /* csgo_thai.txt */"กล่องเก็บของว่างเปล่า",
  InventoryItemStorageUnitInspect: /* csgo_thai.txt */"ตรวจสอบ",
  InventoryItemStorageUnitRetrieve: /* csgo_thai.txt */"เอาไอเท็มคืน",
  InventoryItemSwapStatTrak: /* csgo_thai.txt */"เปิดเครื่องมือสลับ StatTrak™",
  InventoryItemTeam: /* csgo_thai.txt */"ทีม:",
  InventoryItemTeamAny: /* csgo_thai.txt */"อะไรก็ได้",
  InventoryItemTeamCT: /* csgo_thai.txt */"หน่วยต่อต้านผู้ก่อการร้าย",
  InventoryItemTeamT: /* csgo_thai.txt */"ผู้ก่อการร้าย",
  InventoryItemUnequip: /* csgo_thai.txt */"ยกเลิกใช้งาน",
  InventoryItemUnlockContainer: /* csgo_thai.txt */"ปลดล็อคบรรจุภัณฑ์",
  InventoryItemUseStorageUnit: /* csgo_thai.txt */"เริ่มใช้กล่องเก็บของนี้",
  InventorySelectAnItem: /* csgo_thai.txt */"เลือกไอเท็มเพื่อใช้กับ:",
  InventorySelectInspectContents: /* csgo_thai.txt */"ตรวจสอบเนื้อหาของ",
  InventorySelectItemToDeposit: /* csgo_thai.txt */"เลือกไอเท็มเพื่อย้ายไปยัง",
  InventorySelectItemToRetrieve: /* csgo_thai.txt */"เลือกไอเท็มเพื่อเอาคืนจาก",
  ItemRarityAncient: /* csgo_thai.txt */"Extraordinary",
  ItemRarityCommon: /* csgo_thai.txt */"เกรดพื้นฐาน",
  ItemRarityDefault: /* csgo_thai.txt */"เริ่มต้น",
  ItemRarityImmortal: /* csgo_thai.txt */"Contraband",
  ItemRarityLegendary: /* csgo_thai.txt */"Exotic",
  ItemRarityMythical: /* csgo_thai.txt */"Remarkable",
  ItemRarityNameAgent: /* csgo_thai.txt */"เจ้าหน้าที่",
  ItemRarityNameCollectible: /* csgo_thai.txt */"ของสะสม",
  ItemRarityNameContainer: /* csgo_thai.txt */"กล่อง",
  ItemRarityNameContract: /* csgo_thai.txt */"ใบสัญญา",
  ItemRarityNameEquipment: /* csgo_thai.txt */"อุปกรณ์",
  ItemRarityNameGloves: /* csgo_thai.txt */"ถุงมือ",
  ItemRarityNameGraffiti: /* csgo_thai.txt */"กราฟฟิตี้",
  ItemRarityNameKey: /* csgo_thai.txt */"กุญแจ",
  ItemRarityNameKnife: /* csgo_thai.txt */"มีด",
  ItemRarityNameMachinegun: /* csgo_thai.txt */"ปืนกล",
  ItemRarityNameMusicKit: /* csgo_thai.txt */"ชุดอุปกรณ์เพลง",
  ItemRarityNamePatch: /* csgo_thai.txt */"แพตช์ปัก",
  ItemRarityNamePistol: /* csgo_thai.txt */"ปืนพก",
  ItemRarityNameRifle: /* csgo_thai.txt */"ปืนไรเฟิล",
  ItemRarityNameSMG: /* csgo_thai.txt */"ปืนกลมือ",
  ItemRarityNameShotgun: /* csgo_thai.txt */"ปืนลูกซอง",
  ItemRarityNameSniperRifle: /* csgo_thai.txt */"ปืนสไนเปอร์ไรเฟิล",
  ItemRarityNameSticker: /* csgo_thai.txt */"สติกเกอร์",
  ItemRarityNameTool: /* csgo_thai.txt */"เครื่องมือ",
  ItemRarityRare: /* csgo_thai.txt */"เกรดสูง",
  ItemRarityUncommon: /* csgo_thai.txt */"เกรดปานกลาง",
  ItemSwapStatTrakAccept: /* csgo_thai.txt */"ยอมรับ",
  ItemSwapStatTrakClose: /* csgo_thai.txt */"ปิด",
  ItemSwapStatTrakDesc: /* csgo_thai.txt */"ไอเท็มนี้จะสลับค่า StatTrak™ ระหว่างไอเท็มประเภทเดียวกันสองชิ้น",
  ItemSwapStatTrakUse: /* csgo_thai.txt */"เครื่องมือสลับ StatTrak™",
  ItemSwapStatTrakWarn: /* csgo_thai.txt */"StatTrak™ Swap Tool นี้สามารถใช้งานได้ครั้งเดียวเท่านั้น",
  ItemWeaponRarityAncient: /* csgo_thai.txt */"ลึกลับ",
  ItemWeaponRarityCommon: /* csgo_thai.txt */"เกรดผู้บริโภค",
  ItemWeaponRarityDefault: /* csgo_thai.txt */"พื้นฐาน",
  ItemWeaponRarityImmortal: /* csgo_thai.txt */"Contraband",
  ItemWeaponRarityLegendary: /* csgo_thai.txt */"ปกปิด",
  ItemWeaponRarityMythical: /* csgo_thai.txt */"หวงห้าม",
  ItemWeaponRarityRare: /* csgo_thai.txt */"เกรดมาตรฐานทางทหาร",
  ItemWeaponRarityUncommon: /* csgo_thai.txt */"เกรดอุตสาหกรรม",
  ItemWearBS: /* csgo_thai.txt */"ถลอกปอกเปิกจากการรบ",
  ItemWearFN: /* csgo_thai.txt */"ใหม่จากโรงงาน",
  ItemWearFT: /* csgo_thai.txt */"ผ่านการทดสอบภาคสนาม",
  ItemWearMW: /* csgo_thai.txt */"มีรอยถลอกเล็กน้อย",
  ItemWearWW: /* csgo_thai.txt */"มีรอยถลอกอย่างมาก",
  RemovePatchRemove: /* csgo_thai.txt */"ถอดแพตช์ปัก",
  RemovePatchRemoveDesc: /* csgo_thai.txt */"กรุณายืนยันว่า คุณต้องการถอดแพตช์ปักนี้ออกจากเจ้าหน้าที่ของคุณ แพตช์ปักที่ถูกถอดออกจะถูกลบทิ้งไปถาวร",
  RemovePatchUse: /* csgo_thai.txt */"ถอดแพตช์ปัก",
  RemovePatchWarn: /* csgo_thai.txt */"ถอดแพตช์ปักออกจาก",
  RenameCancel: /* csgo_thai.txt */"ยกเลิก",
  RenameEnterName: /* csgo_thai.txt */"กรอกชื่อใหม่สำหรับ:",
  RenameRename: /* csgo_thai.txt */"เปลี่ยนชื่อ",
  RenameStorageUnitClose: /* csgo_thai.txt */"ปิด",
  RenameStorageUnitEnterName: /* csgo_thai.txt */"กรอกชื่อใหม่สำหรับ:",
  RenameStorageUnitFirstNameWarn: /* csgo_thai.txt */"กรอกคำอธิบายป้ายชื่อสำหรับกล่องเก็บของส่วนตัวของคุณและเริ่มใช้กล่องเก็บของเพื่อเก็บไอเท็ม",
  RenameStorageUnitNewNameWarn: /* csgo_thai.txt */"กรอกคำอธิบายป้ายชื่อสำหรับกล่องเก็บของนี้",
  RenameStorageUnitRename: /* csgo_thai.txt */"ปรับแต่ง",
  RenameStorageUnitUse: /* csgo_thai.txt */"ปรับแต่งกล่องเก็บของของคุณ",
  RenameUse: /* csgo_thai.txt */"ใช้ป้ายชื่อ",
  RenameWarn: /* csgo_thai.txt */"ป้ายชื่อสามารถใช้ได้เพียงครั้งเดียว",
  ScrapeStickerCancel: /* csgo_thai.txt */"ยกเลิก",
  ScrapeStickerClose: /* csgo_thai.txt */"ปิด",
  ScrapeStickerRemove: /* csgo_thai.txt */"ลบสติกเกอร์",
  ScrapeStickerRemoveDesc: /* csgo_thai.txt */"การขูดสติกเกอร์นี้มากไปกว่านี้จะเป็นการเอามันออกไปจากไอเท็มและมันจะถูกทำลาย",
  ScrapeStickerUse: /* csgo_thai.txt */"ขูดสติกเกอร์",
  ScrapeStickerWarn: /* csgo_thai.txt */"ขูดสติกเกอร์ออกจาก",
  StickerPickerRemove: /* csgo_thai.txt */"ลบ"
};
