/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const turkish = {
  ...english,
  ApplyPatchUse: /* csgo_turkish.txt */"Yamayı İliştir",
  ApplyPatchWarn: /* csgo_turkish.txt */"Bir yama sadece bir kere kullanılabilir",
  ApplyStickerCancel: /* csgo_turkish.txt */"İptal",
  ApplyStickerUse: /* csgo_turkish.txt */"Çıkartmayı Yapıştır",
  ApplyStickerUseOn: /* csgo_turkish.txt */"üzerinde kullan",
  ApplyStickerWarn: /* csgo_turkish.txt */"Bir çıkartma sadece bir kere kullanılabilir",
  CaseAdd: /* csgo_turkish.txt */"Ekle",
  CaseClose: /* csgo_turkish.txt */"Kapat",
  CaseContainsOne: /* csgo_turkish.txt */"Aşağıdaki eşyalardan birini içerir:",
  CaseNeed: /* csgo_turkish.txt */"Bu eylem bir  gerektirir",
  CaseOnceWarn: /* csgo_turkish.txt */"Bu kutu sadece bir kere açılabilir",
  CaseRareItem: /* csgo_turkish.txt */"★ Nadir Özel Eşya ★",
  CaseUnlock: /* csgo_turkish.txt */"öğesinin kilidini açın",
  CaseUnlockContainer: /* csgo_turkish.txt */"Kasayı Aç",
  CaseUse: /* csgo_turkish.txt */"öğesini kullanın",
  CategoryAgent: /* csgo_turkish.txt */"Ajan",
  CategoryCase: /* csgo_turkish.txt */"Kasa",
  CategoryCollectible: /* csgo_turkish.txt */"Koleksiyon Öğesi",
  CategoryEquipment: /* csgo_turkish.txt */"Teçhizat",
  CategoryGlove: /* csgo_turkish.txt */"Eldivenler",
  CategoryGraffiti: /* csgo_turkish.txt */"Grafiti",
  CategoryHeavy: /* csgo_turkish.txt */"Ağır Silahlar",
  CategoryKey: /* csgo_turkish.txt */"Anahtar",
  CategoryKnife: /* csgo_turkish.txt */"Bıçak",
  CategoryMusicKit: /* csgo_turkish.txt */"Müzik Kiti",
  CategoryPatch: /* csgo_turkish.txt */"Yama",
  CategoryPistol: /* csgo_turkish.txt */"Tabanca",
  CategoryRifle: /* csgo_turkish.txt */"Tüfek",
  CategorySMG: /* csgo_turkish.txt */"Hafif Makineli",
  CategorySticker: /* csgo_turkish.txt */"Çıkartma",
  CategoryTool: /* csgo_turkish.txt */"Araç",
  EditorCancel: /* csgo_turkish.txt */"İptal",
  EditorNametag: /* csgo_turkish.txt */"İsim Etiketi",
  EditorPatches: /* csgo_turkish.txt */"Yamalar",
  EditorQuantity: /* csgo_turkish.txt */"Miktar",
  EditorRandom: /* csgo_turkish.txt */"Rastgele",
  EditorReset: /* csgo_turkish.txt */"Sıfırla",
  EditorSave: /* csgo_turkish.txt */"Kaydet",
  EditorSeed: /* csgo_turkish.txt */"Model",
  EditorStatTrak: /* csgo_turkish.txt */"StatTrak™",
  EditorStickers: /* csgo_turkish.txt */"Çıkartmalar",
  EditorWear: /* csgo_turkish.txt */"Aşınma",
  GenericCancel: /* csgo_turkish.txt */"İptal",
  InspectClose: /* csgo_turkish.txt */"Kapat",
  InventoryApplyPatch: /* csgo_turkish.txt */"Yamayı İliştir",
  InventoryApplySticker: /* csgo_turkish.txt */"Çıkartmayı Yapıştır",
  InventoryFilterAgents: /* csgo_turkish.txt */"Ajanlar",
  InventoryFilterAll: /* csgo_turkish.txt */"Tümü",
  InventoryFilterAllEquipment: /* csgo_turkish.txt */"Tüm Teçhizat",
  InventoryFilterAllGraphicArt: /* csgo_turkish.txt */"Tüm Grafik Sanatlar",
  InventoryFilterAlphabetical: /* csgo_turkish.txt */"Alfabetik",
  InventoryFilterCollection: /* csgo_turkish.txt */"Koleksiyon",
  InventoryFilterContainers: /* csgo_turkish.txt */"KONTEYNERLER",
  InventoryFilterDisplay: /* csgo_turkish.txt */"VİTRİN",
  InventoryFilterEquipment: /* csgo_turkish.txt */"EKİPMAN",
  InventoryFilterEquipped: /* csgo_turkish.txt */"Kuşanılma",
  InventoryFilterEverything: /* csgo_turkish.txt */"HER ŞEY",
  InventoryFilterGloves: /* csgo_turkish.txt */"Eldiven",
  InventoryFilterGraffiti: /* csgo_turkish.txt */"Grafiti",
  InventoryFilterGraffitiBoxes: /* csgo_turkish.txt */"Grafiti Kutuları",
  InventoryFilterGraphicArt: /* csgo_turkish.txt */"GRAFİK",
  InventoryFilterMedals: /* csgo_turkish.txt */"Madalyalar",
  InventoryFilterMelee: /* csgo_turkish.txt */"Yakın Dövüş Silahı",
  InventoryFilterMidTier: /* csgo_turkish.txt */"Orta Seviye",
  InventoryFilterMisc: /* csgo_turkish.txt */"Çeşitli",
  InventoryFilterMusicKits: /* csgo_turkish.txt */"Müzik Kitleri",
  InventoryFilterNewest: /* csgo_turkish.txt */"En Yeni",
  InventoryFilterPatches: /* csgo_turkish.txt */"Yamalar",
  InventoryFilterPistols: /* csgo_turkish.txt */"Tabancalar",
  InventoryFilterQuality: /* csgo_turkish.txt */"Kalite",
  InventoryFilterRifles: /* csgo_turkish.txt */"Tüfekler",
  InventoryFilterSearch: /* csgo_turkish.txt */"Burada ara",
  InventoryFilterSouvenirCases: /* csgo_turkish.txt */"Hatıra Kasaları",
  InventoryFilterStickerCapsules: /* csgo_turkish.txt */"Çıkartma Kapsülleri",
  InventoryFilterStickers: /* csgo_turkish.txt */"Çıkartmalar",
  InventoryFilterTools: /* csgo_turkish.txt */"Araçlar",
  InventoryFilterType: /* csgo_turkish.txt */"Tür",
  InventoryFilterWeaponCases: /* csgo_turkish.txt */"Silah Kasaları",
  InventoryItemContainsOne: /* csgo_turkish.txt */"Aşağıdaki eşyalardan birini içerir:",
  InventoryItemDelete: /* csgo_turkish.txt */"Sil",
  InventoryItemDeleteConfirm: /* csgo_turkish.txt */"Eşyayı Sil",
  InventoryItemDeleteConfirmDesc: /* csgo_turkish.txt */"Bu eşyayı silmek istediğinize emin misiniz?",
  InventoryItemEdit: /* csgo_turkish.txt */"Düzenle",
  InventoryItemEquip: /* csgo_turkish.txt */"Kuşan",
  InventoryItemExterior: /* csgo_turkish.txt */"Dış Görünüş:",
  InventoryItemInspect: /* csgo_turkish.txt */"İncele",
  InventoryItemInspectFinishCatalog: /* csgo_turkish.txt */"Tasarım Kataloğu",
  InventoryItemInspectInGame: /* csgo_turkish.txt */"Oyunda incele...",
  InventoryItemInspectPatternTemplate: /* csgo_turkish.txt */"Kalıp Şablonu",
  InventoryItemInspectWearRating: /* csgo_turkish.txt */"Aşınma Durumu",
  InventoryItemMVPStatTrakCount: /* csgo_turkish.txt */"StatTrak™ Resmî Rekabetçi EDO'lar:",
  InventoryItemNew: /* csgo_turkish.txt */"Yeni!",
  InventoryItemRareItem: /* csgo_turkish.txt */"ya da Son Derece Nadir Özel Bir Eşya!",
  InventoryItemRarity: /* csgo_turkish.txt */"Nadirlik:",
  InventoryItemRemovePatch: /* csgo_turkish.txt */"Yamayı Sök",
  InventoryItemRename: /* csgo_turkish.txt */"Yeniden Adlandır",
  InventoryItemRenameStorageUnit: /* csgo_turkish.txt */"Etiketi Değiştir",
  InventoryItemScrapeSticker: /* csgo_turkish.txt */"Çıkartmayı Kazı",
  InventoryItemStatTrak: /* csgo_turkish.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_turkish.txt */"StatTrak™ Onaylı Leşler:",
  InventoryItemStatTrakDesc: /* csgo_turkish.txt */"Bu eşya, sahibi tarafından taşındığında belirli istatistikleri izleyen StatTrak™ teknolojisini içerir.",
  InventoryItemStorageUnitDeposit: /* csgo_turkish.txt */"Eşyaları Kaldır",
  InventoryItemStorageUnitEmptyBody: /* csgo_turkish.txt */"Depo sayesinde envanter limitini aşabilecek {1}'e kadar fazlalık eşyayı saklayabilirsin. Seçili depo boş. Eşyaları istediğin zaman normal envanter ve depo arasında transfer edebilir ya da topladığın eşyaları düzenlemek için kullanabilirsin.",
  InventoryItemStorageUnitEmptyClose: /* csgo_turkish.txt */"Tamam",
  InventoryItemStorageUnitEmptyTitle: /* csgo_turkish.txt */"Boş Depo",
  InventoryItemStorageUnitInspect: /* csgo_turkish.txt */"İncele",
  InventoryItemStorageUnitRetrieve: /* csgo_turkish.txt */"Eşyaları Al",
  InventoryItemSwapStatTrak: /* csgo_turkish.txt */"StatTrak™ Değiştirme Aracı'nı Aç",
  InventoryItemTeam: /* csgo_turkish.txt */"Takım:",
  InventoryItemTeamAny: /* csgo_turkish.txt */"Herhangi",
  InventoryItemTeamCT: /* csgo_turkish.txt */"Anti-Terörist",
  InventoryItemTeamT: /* csgo_turkish.txt */"Terörist",
  InventoryItemUnequip: /* csgo_turkish.txt */"Çıkart",
  InventoryItemUnlockContainer: /* csgo_turkish.txt */"Kasayı Aç",
  InventoryItemUseStorageUnit: /* csgo_turkish.txt */"Bu Depoyu Kullanmaya Başla",
  InventorySelectAnItem: /* csgo_turkish.txt */"Şununla kullanmak için bir öğe seçin:",
  InventorySelectInspectContents: /* csgo_turkish.txt */"Şunun içeriği inceleniyor:",
  InventorySelectItemToDeposit: /* csgo_turkish.txt */"Şuraya kaldırılacak eşyaları seç:",
  InventorySelectItemToRetrieve: /* csgo_turkish.txt */"Alınacak eşyaları seç",
  ItemRarityAncient: /* csgo_turkish.txt */"Olağandışı",
  ItemRarityCommon: /* csgo_turkish.txt */"Temel Sınıf",
  ItemRarityDefault: /* csgo_turkish.txt */"Varsayılan",
  ItemRarityImmortal: /* csgo_turkish.txt */"Kaçak",
  ItemRarityLegendary: /* csgo_turkish.txt */"Egzotik",
  ItemRarityMythical: /* csgo_turkish.txt */"Dikkat Çekici",
  ItemRarityNameAgent: /* csgo_turkish.txt */"Ajan",
  ItemRarityNameCollectible: /* csgo_turkish.txt */"Koleksiyon Öğesi",
  ItemRarityNameContainer: /* csgo_turkish.txt */"Kasa",
  ItemRarityNameContract: /* csgo_turkish.txt */"Kontrat",
  ItemRarityNameEquipment: /* csgo_turkish.txt */"Teçhizat",
  ItemRarityNameGloves: /* csgo_turkish.txt */"Eldivenler",
  ItemRarityNameGraffiti: /* csgo_turkish.txt */"Grafiti",
  ItemRarityNameKey: /* csgo_turkish.txt */"Anahtar",
  ItemRarityNameKnife: /* csgo_turkish.txt */"Bıçak",
  ItemRarityNameMachinegun: /* csgo_turkish.txt */"Makineli Tüfek",
  ItemRarityNameMusicKit: /* csgo_turkish.txt */"Müzik Kiti",
  ItemRarityNamePatch: /* csgo_turkish.txt */"Yama",
  ItemRarityNamePistol: /* csgo_turkish.txt */"Tabanca",
  ItemRarityNameRifle: /* csgo_turkish.txt */"Tüfek",
  ItemRarityNameSMG: /* csgo_turkish.txt */"Hafif Makineli",
  ItemRarityNameShotgun: /* csgo_turkish.txt */"Pompalı Tüfek",
  ItemRarityNameSniperRifle: /* csgo_turkish.txt */"Dürbünlü Tüfek",
  ItemRarityNameSticker: /* csgo_turkish.txt */"Çıkartma",
  ItemRarityNameTool: /* csgo_turkish.txt */"Araç",
  ItemRarityRare: /* csgo_turkish.txt */"Yüksek Sınıf",
  ItemRarityUncommon: /* csgo_turkish.txt */"Orta Sınıf",
  ItemSwapStatTrakAccept: /* csgo_turkish.txt */"KABUL ET",
  ItemSwapStatTrakClose: /* csgo_turkish.txt */"Kapat",
  ItemSwapStatTrakDesc: /* csgo_turkish.txt */"Bu eşya aynı iki eşya arasındaki StatTrak™ değerlerini değiştirir.",
  ItemSwapStatTrakUse: /* csgo_turkish.txt */"StatTrak™ Değiştirme Aracı",
  ItemSwapStatTrakWarn: /* csgo_turkish.txt */"Bu StatTrak™ Değiştirme Aracı sadece bir kez kullanılabilir",
  ItemWeaponRarityAncient: /* csgo_turkish.txt */"Çok Gizli",
  ItemWeaponRarityCommon: /* csgo_turkish.txt */"Tüketici Sınıfı",
  ItemWeaponRarityDefault: /* csgo_turkish.txt */"Standart",
  ItemWeaponRarityImmortal: /* csgo_turkish.txt */"Kaçak",
  ItemWeaponRarityLegendary: /* csgo_turkish.txt */"Gizli",
  ItemWeaponRarityMythical: /* csgo_turkish.txt */"Sınırlı",
  ItemWeaponRarityRare: /* csgo_turkish.txt */"Askeri Sınıf",
  ItemWeaponRarityUncommon: /* csgo_turkish.txt */"Endüstri Sınıfı",
  ItemWearBS: /* csgo_turkish.txt */"Savaş Görmüş",
  ItemWearFN: /* csgo_turkish.txt */"Fabrikadan Yeni Çıkmış",
  ItemWearFT: /* csgo_turkish.txt */"Görevde Kullanılmış",
  ItemWearMW: /* csgo_turkish.txt */"Az Aşınmış",
  ItemWearWW: /* csgo_turkish.txt */"Eskimiş",
  RemovePatchRemove: /* csgo_turkish.txt */"Yamayı Sök",
  RemovePatchRemoveDesc: /* csgo_turkish.txt */"Bu yamayı ajanından sökmek istediğini onaylamalısın. Sökülen yama yok olur.",
  RemovePatchUse: /* csgo_turkish.txt */"Yamayı Sök",
  RemovePatchWarn: /* csgo_turkish.txt */"Yamayı şundan sök:",
  RenameCancel: /* csgo_turkish.txt */"İptal",
  RenameEnterName: /* csgo_turkish.txt */"için yeni bir isim girin",
  RenameRename: /* csgo_turkish.txt */"Yeniden Adlandır",
  RenameStorageUnitClose: /* csgo_turkish.txt */"Kapat",
  RenameStorageUnitEnterName: /* csgo_turkish.txt */"için yeni bir isim girin",
  RenameStorageUnitFirstNameWarn: /* csgo_turkish.txt */"Depon için açıklayıcı bir etiket gir ve eşyalarını saklamak için kullanmaya başla.",
  RenameStorageUnitNewNameWarn: /* csgo_turkish.txt */"Bu depo için açıklayıcı yeni bir etiket gir.",
  RenameStorageUnitRename: /* csgo_turkish.txt */"Kişiselleştir",
  RenameStorageUnitUse: /* csgo_turkish.txt */"Deponu Kişiselleştir",
  RenameUse: /* csgo_turkish.txt */"İsim Etiketini Kullan",
  RenameWarn: /* csgo_turkish.txt */"Bir İsim Etiketi sadece bir kez kullanılabilir",
  ScrapeStickerCancel: /* csgo_turkish.txt */"İptal",
  ScrapeStickerClose: /* csgo_turkish.txt */"Kapat",
  ScrapeStickerRemove: /* csgo_turkish.txt */"Çıkartmayı Kaldır",
  ScrapeStickerRemoveDesc: /* csgo_turkish.txt */"Bu çıkartmayı daha fazla kazımak eşyadan sökülmesine neden olacak ve yok edilecek.",
  ScrapeStickerUse: /* csgo_turkish.txt */"Çıkartmayı Kazı",
  ScrapeStickerWarn: /* csgo_turkish.txt */"Çıkartmayı şundan kaldır:",
  SettingsMasterVolume: /* csgo_turkish.txt */"Ana Ses",
  StickerPickerRemove: /* csgo_turkish.txt */"Kaldır"
};
