/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const vietnamese = {
  ...english,
  ApplyPatchUse: /* csgo_vietnamese.txt */"Dùng phù hiệu",
  ApplyPatchWarn: /* csgo_vietnamese.txt */"Mỗi phù hiệu chỉ có thể dùng một lần",
  ApplyStickerCancel: /* csgo_vietnamese.txt */"Hủy",
  ApplyStickerUse: /* csgo_vietnamese.txt */"Dùng hình dán",
  ApplyStickerUseOn: /* csgo_vietnamese.txt */"Sử dụng lên",
  ApplyStickerWarn: /* csgo_vietnamese.txt */"Mỗi hình dán chỉ có thể dùng một lần",
  CaseAdd: /* csgo_vietnamese.txt */"Thêm",
  CaseClose: /* csgo_vietnamese.txt */"Đóng",
  CaseContainsOne: /* csgo_vietnamese.txt */"Chứa một trong những vật phẩm sau:",
  CaseNeed: /* csgo_vietnamese.txt */"Hành động này cần một",
  CaseOnceWarn: /* csgo_vietnamese.txt */"Hộp này chỉ có thể mở được một lần",
  CaseRareItem: /* csgo_vietnamese.txt */"★ Vật phẩm hiếm đặc biệt ★",
  CaseUnlock: /* csgo_vietnamese.txt */"Mở khóa",
  CaseUnlockContainer: /* csgo_vietnamese.txt */"Mở khóa",
  CaseUse: /* csgo_vietnamese.txt */"Dùng",
  CategoryAgent: /* csgo_vietnamese.txt */"Đặc vụ",
  CategoryCase: /* csgo_vietnamese.txt */"Đồ chứa",
  CategoryCollectible: /* csgo_vietnamese.txt */"Vật phẩm thu thập",
  CategoryEquipment: /* csgo_vietnamese.txt */"Trang bị",
  CategoryGlove: /* csgo_vietnamese.txt */"Găng tay",
  CategoryGraffiti: /* csgo_vietnamese.txt */"Graffiti",
  CategoryHeavy: /* csgo_vietnamese.txt */"Hạng nặng",
  CategoryKey: /* csgo_vietnamese.txt */"Chìa khóa",
  CategoryKnife: /* csgo_vietnamese.txt */"Dao",
  CategoryMusicKit: /* csgo_vietnamese.txt */"Gói âm thanh",
  CategoryPatch: /* csgo_vietnamese.txt */"Phù hiệu",
  CategoryPistol: /* csgo_vietnamese.txt */"Súng lục",
  CategoryRifle: /* csgo_vietnamese.txt */"Súng trường",
  CategorySMG: /* csgo_vietnamese.txt */"Súng tiểu liên",
  CategorySticker: /* csgo_vietnamese.txt */"Hình dán",
  CategoryTool: /* csgo_vietnamese.txt */"Dụng cụ",
  EditorCancel: /* csgo_vietnamese.txt */"Hủy",
  EditorNametag: /* csgo_vietnamese.txt */"Thẻ tên",
  EditorPatches: /* csgo_vietnamese.txt */"Phù hiệu",
  EditorQuantity: /* csgo_vietnamese.txt */"Số lượng",
  EditorRandom: /* csgo_vietnamese.txt */"Ngẫu nhiên",
  EditorReset: /* csgo_vietnamese.txt */"Đặt lại",
  EditorSave: /* csgo_vietnamese.txt */"Lưu",
  EditorSeed: /* csgo_vietnamese.txt */"Họa tiết",
  EditorStatTrak: /* csgo_vietnamese.txt */"StatTrak™",
  EditorStickers: /* csgo_vietnamese.txt */"Hình dán",
  EditorWear: /* csgo_vietnamese.txt */"Mòn",
  InspectClose: /* csgo_vietnamese.txt */"Đóng",
  InventoryApplyPatch: /* csgo_vietnamese.txt */"Dùng phù hiệu",
  InventoryApplySticker: /* csgo_vietnamese.txt */"Dùng hình dán",
  InventoryFilterAgents: /* csgo_vietnamese.txt */"Đặc vụ",
  InventoryFilterAll: /* csgo_vietnamese.txt */"Tất cả",
  InventoryFilterAllEquipment: /* csgo_vietnamese.txt */"Toàn bộ trang bị",
  InventoryFilterAllGraphicArt: /* csgo_vietnamese.txt */"Toàn bộ ảnh đồ họa",
  InventoryFilterAlphabetical: /* csgo_vietnamese.txt */"Theo bảng chữ cái",
  InventoryFilterCollection: /* csgo_vietnamese.txt */"Bộ sưu tập",
  InventoryFilterContainers: /* csgo_vietnamese.txt */"HÒM",
  InventoryFilterDisplay: /* csgo_vietnamese.txt */"TRƯNG BÀY",
  InventoryFilterEquipment: /* csgo_vietnamese.txt */"TRANG BỊ",
  InventoryFilterEquipped: /* csgo_vietnamese.txt */"Đã trang bị",
  InventoryFilterEverything: /* csgo_vietnamese.txt */"TẤT CẢ",
  InventoryFilterGloves: /* csgo_vietnamese.txt */"Găng tay",
  InventoryFilterGraffiti: /* csgo_vietnamese.txt */"Graffiti",
  InventoryFilterGraffitiBoxes: /* csgo_vietnamese.txt */"Hộp graffiti",
  InventoryFilterGraphicArt: /* csgo_vietnamese.txt */"TÁC PHẨM ĐỒ HỌA",
  InventoryFilterMedals: /* csgo_vietnamese.txt */"Huy chương",
  InventoryFilterMelee: /* csgo_vietnamese.txt */"Cận chiến",
  InventoryFilterMidTier: /* csgo_vietnamese.txt */"Hạng trung",
  InventoryFilterMisc: /* csgo_vietnamese.txt */"Thông tin khác",
  InventoryFilterMusicKits: /* csgo_vietnamese.txt */"Gói âm thanh",
  InventoryFilterNewest: /* csgo_vietnamese.txt */"Mới nhất",
  InventoryFilterPatches: /* csgo_vietnamese.txt */"Phù hiệu",
  InventoryFilterPistols: /* csgo_vietnamese.txt */"Súng lục",
  InventoryFilterQuality: /* csgo_vietnamese.txt */"Chất lượng",
  InventoryFilterRifles: /* csgo_vietnamese.txt */"Súng trường",
  InventoryFilterSearch: /* csgo_vietnamese.txt */"Gõ tìm tại đây",
  InventoryFilterSouvenirCases: /* csgo_vietnamese.txt */"Hòm lưu niệm",
  InventoryFilterStickerCapsules: /* csgo_vietnamese.txt */"Gói hình dán",
  InventoryFilterStickers: /* csgo_vietnamese.txt */"Hình dán",
  InventoryFilterTools: /* csgo_vietnamese.txt */"Công cụ",
  InventoryFilterType: /* csgo_vietnamese.txt */"Loại",
  InventoryFilterWeaponCases: /* csgo_vietnamese.txt */"Hòm vũ khí",
  InventoryItemContainsOne: /* csgo_vietnamese.txt */"Chứa một trong những vật phẩm sau:",
  InventoryItemDelete: /* csgo_vietnamese.txt */"Xóa",
  InventoryItemEdit: /* csgo_vietnamese.txt */"Sửa",
  InventoryItemEquip: /* csgo_vietnamese.txt */"Trang bị",
  InventoryItemExterior: /* csgo_vietnamese.txt */"Độ bền:",
  InventoryItemInspect: /* csgo_vietnamese.txt */"Quan sát",
  InventoryItemInspectFinishCatalog: /* csgo_vietnamese.txt */"Catalog thiết kế số",
  InventoryItemInspectInGame: /* csgo_vietnamese.txt */"Xem trong trò chơi...",
  InventoryItemInspectPatternTemplate: /* csgo_vietnamese.txt */"Mẫu họa tiết",
  InventoryItemInspectWearRating: /* csgo_vietnamese.txt */"Độ mòn",
  InventoryItemMVPStatTrakCount: /* csgo_vietnamese.txt */"Lần MVP khi tranh đấu chính thức qua StatTrak™:",
  InventoryItemNew: /* csgo_vietnamese.txt */"Mới!",
  InventoryItemRareItem: /* csgo_vietnamese.txt */"hoặc VẬT PHẨM ĐẶC BIỆT CỰC KÌ HIẾM!",
  InventoryItemRarity: /* csgo_vietnamese.txt */"Độ hiếm:",
  InventoryItemRemovePatch: /* csgo_vietnamese.txt */"Gỡ phù hiệu",
  InventoryItemRename: /* csgo_vietnamese.txt */"Đổi tên",
  InventoryItemRenameStorageUnit: /* csgo_vietnamese.txt */"Đổi nhãn",
  InventoryItemScrapeSticker: /* csgo_vietnamese.txt */"Cào hình dán",
  InventoryItemStatTrak: /* csgo_vietnamese.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_vietnamese.txt */"Mạng xác nhận qua StatTrak™:",
  InventoryItemStatTrakDesc: /* csgo_vietnamese.txt */"Vật phẩm sử dụng công nghệ StatTrak™, ghi lại số liệu nhất định khi người dùng trang bị.",
  InventoryItemStorageUnitDeposit: /* csgo_vietnamese.txt */"Gửi vật phẩm",
  InventoryItemStorageUnitEmptyBody: /* csgo_vietnamese.txt */"Thùng chứa riêng cho phép bạn cất tới {1} món mà kho đồ không còn khả năng chứa. Thùng chứa riêng được chọn hiện trống không. Bạn có thể bất kỳ lúc nào chuyển đồ từ kho đồ sang thùng chứa riêng, nhận lại vào kho, hoặc dùng nó để sắp xếp bộ sưu tầm của mình.",
  InventoryItemStorageUnitEmptyClose: /* csgo_vietnamese.txt */"OK",
  InventoryItemStorageUnitEmptyTitle: /* csgo_vietnamese.txt */"Thùng chứa riêng trống",
  InventoryItemStorageUnitInspect: /* csgo_vietnamese.txt */"Quan sát",
  InventoryItemStorageUnitRetrieve: /* csgo_vietnamese.txt */"Lấy vật phẩm",
  InventoryItemSwapStatTrak: /* csgo_vietnamese.txt */"Sử dụng bộ chuyển đổi StatTrak™",
  InventoryItemTeam: /* csgo_vietnamese.txt */"Đội:",
  InventoryItemTeamAny: /* csgo_vietnamese.txt */"Bất kỳ",
  InventoryItemTeamCT: /* csgo_vietnamese.txt */"Chống khủng bố",
  InventoryItemTeamT: /* csgo_vietnamese.txt */"Khủng bố",
  InventoryItemUnequip: /* csgo_vietnamese.txt */"Bỏ trang bị",
  InventoryItemUnlockContainer: /* csgo_vietnamese.txt */"Mở khóa",
  InventoryItemUseStorageUnit: /* csgo_vietnamese.txt */"Bắt đầu dùng thùng này",
  InventorySelectAnItem: /* csgo_vietnamese.txt */"Chọn một vật phẩm để dùng cùng:",
  InventorySelectInspectContents: /* csgo_vietnamese.txt */"Xem vật phẩm bên trong",
  InventorySelectItemToDeposit: /* csgo_vietnamese.txt */"Chọn các món để chuyển vào",
  InventorySelectItemToRetrieve: /* csgo_vietnamese.txt */"Chọn các món để lấy ra",
  ItemRarityAncient: /* csgo_vietnamese.txt */"Phi thường",
  ItemRarityCommon: /* csgo_vietnamese.txt */"Hạng cơ bản",
  ItemRarityDefault: /* csgo_vietnamese.txt */"Mặc định",
  ItemRarityImmortal: /* csgo_vietnamese.txt */"Hàng cấm",
  ItemRarityLegendary: /* csgo_vietnamese.txt */"Ngoại nhập",
  ItemRarityMythical: /* csgo_vietnamese.txt */"Ấn tượng",
  ItemRarityNameAgent: /* csgo_vietnamese.txt */"Đặc vụ",
  ItemRarityNameCollectible: /* csgo_vietnamese.txt */"Vật phẩm thu thập",
  ItemRarityNameContainer: /* csgo_vietnamese.txt */"Đồ chứa",
  ItemRarityNameContract: /* csgo_vietnamese.txt */"Hợp đồng",
  ItemRarityNameEquipment: /* csgo_vietnamese.txt */"Trang bị",
  ItemRarityNameGloves: /* csgo_vietnamese.txt */"Găng tay",
  ItemRarityNameGraffiti: /* csgo_vietnamese.txt */"Graffiti",
  ItemRarityNameKey: /* csgo_vietnamese.txt */"Chìa khóa",
  ItemRarityNameKnife: /* csgo_vietnamese.txt */"Dao",
  ItemRarityNameMachinegun: /* csgo_vietnamese.txt */"Súng máy",
  ItemRarityNameMusicKit: /* csgo_vietnamese.txt */"Gói âm thanh",
  ItemRarityNamePatch: /* csgo_vietnamese.txt */"Phù hiệu",
  ItemRarityNamePistol: /* csgo_vietnamese.txt */"Súng lục",
  ItemRarityNameRifle: /* csgo_vietnamese.txt */"Súng trường",
  ItemRarityNameSMG: /* csgo_vietnamese.txt */"Súng tiểu liên",
  ItemRarityNameShotgun: /* csgo_vietnamese.txt */"Súng hoa cải",
  ItemRarityNameSniperRifle: /* csgo_vietnamese.txt */"Súng trường bắn tỉa",
  ItemRarityNameSticker: /* csgo_vietnamese.txt */"Hình dán",
  ItemRarityNameTool: /* csgo_vietnamese.txt */"Dụng cụ",
  ItemRarityRare: /* csgo_vietnamese.txt */"Hạng cao cấp",
  ItemRarityUncommon: /* csgo_vietnamese.txt */"Hạng trung bình",
  ItemSwapStatTrakAccept: /* csgo_vietnamese.txt */"CHẤP NHẬN",
  ItemSwapStatTrakClose: /* csgo_vietnamese.txt */"Đóng",
  ItemSwapStatTrakDesc: /* csgo_vietnamese.txt */"Vật phẩm sẽ đổi giá trị StatTrak™ giữa hai vật phẩm trong cùng thể loại.",
  ItemSwapStatTrakUse: /* csgo_vietnamese.txt */"Bộ chuyển đổi StatTrak™",
  ItemSwapStatTrakWarn: /* csgo_vietnamese.txt */"Bộ chuyển đổi StatTrak™ chỉ có thể sử dụng một lần",
  ItemWeaponRarityAncient: /* csgo_vietnamese.txt */"Mật vụ",
  ItemWeaponRarityCommon: /* csgo_vietnamese.txt */"Hạng tiêu dùng",
  ItemWeaponRarityDefault: /* csgo_vietnamese.txt */"Cơ bản",
  ItemWeaponRarityImmortal: /* csgo_vietnamese.txt */"Hàng cấm",
  ItemWeaponRarityLegendary: /* csgo_vietnamese.txt */"Hạng tuyệt mật",
  ItemWeaponRarityMythical: /* csgo_vietnamese.txt */"Hàng hạn chế",
  ItemWeaponRarityRare: /* csgo_vietnamese.txt */"Hạng Mil-Spec",
  ItemWeaponRarityUncommon: /* csgo_vietnamese.txt */"Hạng công nghiệp",
  ItemWearBS: /* csgo_vietnamese.txt */"BS - Mòn qua thực chiến",
  ItemWearFN: /* csgo_vietnamese.txt */"FN - Mới cứng",
  ItemWearFT: /* csgo_vietnamese.txt */"FT - Qua thực chiến",
  ItemWearMW: /* csgo_vietnamese.txt */"MW - Trầy ít",
  ItemWearWW: /* csgo_vietnamese.txt */"WW - Khá mòn",
  RemovePatchRemove: /* csgo_vietnamese.txt */"Gỡ phù hiệu",
  RemovePatchRemoveDesc: /* csgo_vietnamese.txt */"Xin hãy xác nhận rằng bạn muốn gỡ phù hiệu này khỏi đặc vụ. Sau khi gỡ, phù hiệu sẽ bị hủy.",
  RemovePatchUse: /* csgo_vietnamese.txt */"Gỡ phù hiệu",
  RemovePatchWarn: /* csgo_vietnamese.txt */"Gỡ một phù hiệu khỏi",
  RenameCancel: /* csgo_vietnamese.txt */"Hủy",
  RenameEnterName: /* csgo_vietnamese.txt */"Nhập tên mới cho:",
  RenameRename: /* csgo_vietnamese.txt */"Đổi tên",
  RenameStorageUnitClose: /* csgo_vietnamese.txt */"Đóng",
  RenameStorageUnitEnterName: /* csgo_vietnamese.txt */"Nhập tên mới cho:",
  RenameStorageUnitFirstNameWarn: /* csgo_vietnamese.txt */"Nhập nhãn mô tả cho thùng chứa cá nhân của mình rồi bắt đầu cất vật phẩm bên trong.",
  RenameStorageUnitNewNameWarn: /* csgo_vietnamese.txt */"Nhập một nhãn mô tả mới cho thùng chứa riêng này.",
  RenameStorageUnitRename: /* csgo_vietnamese.txt */"Cá nhân hóa",
  RenameStorageUnitUse: /* csgo_vietnamese.txt */"Cá nhân hóa thùng chứa của bạn",
  RenameUse: /* csgo_vietnamese.txt */"Sử dụng nhãn tên",
  RenameWarn: /* csgo_vietnamese.txt */"Nhãn tên chỉ có thể sử dụng một lần",
  ScrapeStickerCancel: /* csgo_vietnamese.txt */"Hủy",
  ScrapeStickerClose: /* csgo_vietnamese.txt */"Đóng",
  ScrapeStickerRemove: /* csgo_vietnamese.txt */"Gỡ hình dán",
  ScrapeStickerRemoveDesc: /* csgo_vietnamese.txt */"Cào hình dán này lần nữa sẽ loại bỏ nó khỏi vật phẩm và hình dán sẽ bị hủy bỏ.",
  ScrapeStickerUse: /* csgo_vietnamese.txt */"Cào hình dán",
  ScrapeStickerWarn: /* csgo_vietnamese.txt */"Cào hình dán trên",
  StickerPickerRemove: /* csgo_vietnamese.txt */"Gỡ bỏ"
};
